// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace KDPM_ReqnrollSeleniumAutomationTesting_Nhom5.Features
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::NUnit.Framework.TestFixtureAttribute()]
    [global::NUnit.Framework.DescriptionAttribute("Đăng ký vào hệ thống web bán thuốc MedForAll")]
    [global::NUnit.Framework.FixtureLifeCycleAttribute(global::NUnit.Framework.LifeCycle.InstancePerTestCase)]
    [global::NUnit.Framework.CategoryAttribute("dang_ky_feature")]
    public partial class DangKyVaoHệThốngWebBanThuốcMedForAllFeature
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = new string[] {
                "dang_ky_feature"};
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "Features", "Đăng ký vào hệ thống web bán thuốc MedForAll", "\tĐăng ký tài khoản vào hệ thống web bán thuốc MedForAll", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
#line 1 "DangKy.feature"
#line hidden
        
        [global::NUnit.Framework.OneTimeSetUpAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        [global::NUnit.Framework.OneTimeTearDownAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        [global::NUnit.Framework.SetUpAttribute()]
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        [global::NUnit.Framework.TearDownAttribute()]
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<global::NUnit.Framework.TestContext>(global::NUnit.Framework.TestContext.CurrentContext);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/DangKy.feature.ndjson", 31);
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Đăng ký thành công")]
        [global::NUnit.Framework.CategoryAttribute("luong_thanh_cong")]
        [global::NUnit.Framework.TestCaseAttribute("TC_USER_DANGKY_001", "TD_01_01", "MinhPham", "Minh@gmail.com", "Minh134@", "Minh134@", "Hệ thống thông báo đăng ký thành công và chuyển hướng.", "0", null)]
        public async global::System.Threading.Tasks.Task DangKyThanhCong(string tc_Id, string data_Id, string ten_Dang_Nhap, string email, string mat_Khau, string xac_Nhan_Mk, string ket_Qua_Mong_Doi, string @__pickleIndex, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "luong_thanh_cong"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("tc_id", tc_Id);
            argumentsOfScenario.Add("data_id", data_Id);
            argumentsOfScenario.Add("ten_dang_nhap", ten_Dang_Nhap);
            argumentsOfScenario.Add("email", email);
            argumentsOfScenario.Add("mat_khau", mat_Khau);
            argumentsOfScenario.Add("xac_nhan_mk", xac_Nhan_Mk);
            argumentsOfScenario.Add("ket_qua_mong_doi", ket_Qua_Mong_Doi);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Đăng ký thành công", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 5
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
 await testRunner.GivenAsync("người dùng truy cập vào trang web \"http://localhost:44317/\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 7
 await testRunner.AndAsync("người dùng nhấn vào nút Đăng ký", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 8
 await testRunner.WhenAsync(string.Format("người dùng nhập thông tin đăng ký bao gồm \"{0}\", \"{1}\", \"{2}\" và \"{3}\"", ten_Dang_Nhap, email, mat_Khau, xac_Nhan_Mk), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 9
 await testRunner.AndAsync("người dùng nhấn nút Đăng ký trên giao diện đăng ký", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 10
 await testRunner.AndAsync("hệ thống chuyển hướng sang trang đăng nhập", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Kiểm tra các ràng buộc đầu vào không hợp lệ (Mục 2, 4, 7)")]
        [global::NUnit.Framework.CategoryAttribute("kiem_tra_rang_buoc")]
        [global::NUnit.Framework.TestCaseAttribute("TC_USER_DANGKY_002", "TD_02_01", "", "Minh@gmail.com", "Minh134@", "Minh134@", "Yêu cầu nhập tên đăng nhập", "1", null)]
        [global::NUnit.Framework.TestCaseAttribute("TC_USER_DANGKY_003", "TD_03_01", "M", "Minh@gmail.com", "Minh134@", "Minh134@", "tối thiểu", "2", null)]
        [global::NUnit.Framework.TestCaseAttribute("TC_USER_DANGKY_004", "TD_04_01", "MinhPham [1000_ky_tu]", "Minh@gmail.com", "Minh134@", "Minh134@", "[gioi_han_ky_tu]", "3", null)]
        [global::NUnit.Framework.TestCaseAttribute("TC_USER_DANGKY_005", "TD_05_01", "!@#%", "Minh@gmail.com", "Minh134@", "Minh134@", "không được chứa ký tự đặc biệt", "4", null)]
        [global::NUnit.Framework.TestCaseAttribute("TC_USER_DANGKY_007", "TD_07_01", "MinhPham", "", "Minh134@", "Minh134@", "Email không được để trống", "5", null)]
        [global::NUnit.Framework.TestCaseAttribute("TC_USER_DANGKY_008", "TD_08_01", "MinhPham", "Minhgmail.com", "Minh134@", "Minh134@", "không đúng định dạng", "6", null)]
        [global::NUnit.Framework.TestCaseAttribute("TC_USER_DANGKY_008", "TD_08_02", "MinhPham", "Minh@.com", "Minh134@", "Minh134@", "không đúng định dạng", "7", null)]
        [global::NUnit.Framework.TestCaseAttribute("TC_USER_DANGKY_008", "TD_08_03", "MinhPham", "Minh@gmail", "Minh134@", "Minh134@", "không đúng định dạng", "8", null)]
        [global::NUnit.Framework.TestCaseAttribute("TC_USER_DANGKY_011", "TD_11_01", "MinhPham", "Minh@gmail.com", "", "Minh134@", "Yêu cầu nhập mật khẩu", "9", null)]
        [global::NUnit.Framework.TestCaseAttribute("TC_USER_DANGKY_011", "TD_11_02", "MinhPham", "Minh@gmail.com", "Minh134@", "", "Xác nhận mật khẩu không được trống", "10", null)]
        [global::NUnit.Framework.TestCaseAttribute("TC_USER_DANGKY_012", "TD_12_01", "MinhPham", "Minh@gmail.com", "Mi", "Mi", "Mật khẩu phải dài ít nhất 6 ký tự", "11", null)]
        [global::NUnit.Framework.TestCaseAttribute("TC_USER_DANGKY_013", "TD_13_01", "MinhPham", "Minh@gmail.com", "Minh134@ [1000_ky_tu]", "Minh134@ [1000_ky_tu]", "[gioi_han_ky_tu]", "12", null)]
        [global::NUnit.Framework.TestCaseAttribute("TC_USER_DANGKY_014", "TD_14_01", "MinhPham", "Minh@gmail.com", "minh134@", "minh134@", "thiếu chữ hoa", "13", null)]
        [global::NUnit.Framework.TestCaseAttribute("TC_USER_DANGKY_014", "TD_14_02", "MinhPham", "Minh@gmail.com", "M1334@", "M1334@", "thiếu chữ thường", "14", null)]
        [global::NUnit.Framework.TestCaseAttribute("TC_USER_DANGKY_014", "TD_14_03", "MinhPham", "Minh@gmail.com", "Minhhh@", "Minhhh@", "thiếu số", "15", null)]
        [global::NUnit.Framework.TestCaseAttribute("TC_USER_DANGKY_014", "TD_14_04", "MinhPham", "Minh@gmail.com", "Minh1344", "Minh1344", "thiếu ký tự đặc biệt", "16", null)]
        [global::NUnit.Framework.TestCaseAttribute("TC_USER_DANGKY_015", "TD_15_01", "MinhPham", "Minh@gmail.com", "Minh134@", "\"\"", "Yêu cầu nhập xác nhận mật khẩu", "17", null)]
        [global::NUnit.Framework.TestCaseAttribute("TC_USER_DANGKY_016", "TD_16_01", "MinhPham", "Minh@gmail.com", "Minh134@", "Minh134@a", "Mật khẩu xác nhận không khớp", "18", null)]
        [global::NUnit.Framework.TestCaseAttribute("TC_USER_DANGKY_017", "TD_17_01", "<script>alert(\'XSS\')</script>", "Minh@gmail.com", "Minh134@", "Minh134@", "[bao_mat_dau_vao_html]", "19", null)]
        [global::NUnit.Framework.TestCaseAttribute("TC_USER_DANGKY_017", "TD_17_02", "<h1>HTML được cấy thành công vào hệ thống</h1>", "Minh@gmail.com", "Minh134@", "Minh134@", "[bao_mat_dau_vao_html]", "20", null)]
        [global::NUnit.Framework.TestCaseAttribute("TC_USER_DANGKY_018", "TD_18_01", "\"", "Minh@gmail.com", "Minh134@", "Minh134@", "[bao_mat_dau_vao_sql]", "21", null)]
        [global::NUnit.Framework.TestCaseAttribute("TC_USER_DANGKY_018", "TD_18_02", "TRUNCATE TABLE THUOC", "Minh@gmail.com", "Minh134@", "Minh134@", "[bao_mat_dau_vao_sql]", "22", null)]
        [global::NUnit.Framework.TestCaseAttribute("TC_USER_DANGKY_023", "TD_23_01", "<script>alert(\'XSS\')</script>", "Minh@gmail.com", "Minh134@", "Minh134@", "[khong_hien_thi_loi_chi_tiet]", "23", null)]
        public async global::System.Threading.Tasks.Task KiểmTraCacRangBuộcDầuVaoKhongHợpLệMục247(string tc_Id, string data_Id, string ten_Dang_Nhap, string email, string mat_Khau, string xac_Nhan_Mk, string ket_Qua_Mong_Doi, string @__pickleIndex, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "kiem_tra_rang_buoc"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("tc_id", tc_Id);
            argumentsOfScenario.Add("data_id", data_Id);
            argumentsOfScenario.Add("ten_dang_nhap", ten_Dang_Nhap);
            argumentsOfScenario.Add("email", email);
            argumentsOfScenario.Add("mat_khau", mat_Khau);
            argumentsOfScenario.Add("xac_nhan_mk", xac_Nhan_Mk);
            argumentsOfScenario.Add("ket_qua_mong_doi", ket_Qua_Mong_Doi);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Kiểm tra các ràng buộc đầu vào không hợp lệ (Mục 2, 4, 7)", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 16
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 17
 await testRunner.GivenAsync("người dùng truy cập vào trang web \"http://localhost:44317/\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 18
 await testRunner.AndAsync("người dùng nhấn vào nút Đăng ký", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 19
 await testRunner.WhenAsync(string.Format("người dùng nhập thông tin đăng ký bao gồm \"{0}\", \"{1}\", \"{2}\" và \"{3}\"", ten_Dang_Nhap, email, mat_Khau, xac_Nhan_Mk), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 20
 await testRunner.AndAsync("người dùng nhấn nút Đăng ký trên giao diện đăng ký", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 21
 await testRunner.ThenAsync(string.Format("hệ thống thông báo lỗi \"{0}\"", ket_Qua_Mong_Doi), ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Kiểm tra trùng lặp")]
        [global::NUnit.Framework.CategoryAttribute("kiem_tra_trung_lap")]
        [global::NUnit.Framework.TestCaseAttribute("TC_USER_DANGKY_010", "TD_10_01", "MinhPham", "Minh@gmail.com", "Minh134@", "Minh134@", "Tên đăng nhập đã tồn tại", "24", null)]
        [global::NUnit.Framework.TestCaseAttribute("TC_USER_DANGKY_006", "TD_06_01", "MinhPham", "Minh@gmail.com", "Minh134@", "Minh134@", "Gmail đã tồn tại", "25", null)]
        public async global::System.Threading.Tasks.Task KiểmTraTrungLặp(string tc_Id, string data_Id, string ten_Dang_Nhap, string email, string mat_Khau, string xac_Nhan_Mk, string ket_Qua_Mong_Doi, string @__pickleIndex, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "kiem_tra_trung_lap"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("tc_id", tc_Id);
            argumentsOfScenario.Add("data_id", data_Id);
            argumentsOfScenario.Add("ten_dang_nhap", ten_Dang_Nhap);
            argumentsOfScenario.Add("email", email);
            argumentsOfScenario.Add("mat_khau", mat_Khau);
            argumentsOfScenario.Add("xac_nhan_mk", xac_Nhan_Mk);
            argumentsOfScenario.Add("ket_qua_mong_doi", ket_Qua_Mong_Doi);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Kiểm tra trùng lặp", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 66
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 67
 await testRunner.GivenAsync("người dùng truy cập vào trang web \"http://localhost:44317/\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 68
 await testRunner.AndAsync("người dùng nhấn vào nút Đăng ký", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 69
 await testRunner.WhenAsync(string.Format("người dùng nhập thông tin đăng ký bao gồm \"{0}\", \"{1}\", \"{2}\" và \"{3}\"", ten_Dang_Nhap, email, mat_Khau, xac_Nhan_Mk), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 70
 await testRunner.AndAsync("người dùng nhấn nút Đăng ký trên giao diện đăng ký", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 71
 await testRunner.AndAsync("người dùng nhấn vào nút Đăng ký", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 72
 await testRunner.AndAsync(string.Format("người dùng nhập thông tin đăng ký bao gồm \"{0}\", \"{1}\", \"{2}\" và \"{3}\"", ten_Dang_Nhap, email, mat_Khau, xac_Nhan_Mk), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 73
 await testRunner.AndAsync("người dùng nhấn nút Đăng ký trên giao diện đăng ký", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 74
 await testRunner.ThenAsync(string.Format("hệ thống thông báo lỗi \"{0}\"", ket_Qua_Mong_Doi), ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Kiểm tra vô hiệu hóa nút đăng ký để chống spam (TC_024)")]
        [global::NUnit.Framework.CategoryAttribute("bao_mat_ui_chong_spam")]
        [global::NUnit.Framework.TestCaseAttribute("TC_USER_DANGKY_024", "TD_24_01", "MinhPham", "Minh@gmail.com", "Minh134@", "Minh134@", "26", null)]
        public async global::System.Threading.Tasks.Task KiểmTraVoHiệuHoaNutDangKyDểChốngSpamTC_024(string tc_Id, string data_Id, string ten_Dang_Nhap, string email, string mat_Khau, string xac_Nhan_Mk, string @__pickleIndex, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "bao_mat_ui_chong_spam"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("tc_id", tc_Id);
            argumentsOfScenario.Add("data_id", data_Id);
            argumentsOfScenario.Add("ten_dang_nhap", ten_Dang_Nhap);
            argumentsOfScenario.Add("email", email);
            argumentsOfScenario.Add("mat_khau", mat_Khau);
            argumentsOfScenario.Add("xac_nhan_mk", xac_Nhan_Mk);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Kiểm tra vô hiệu hóa nút đăng ký để chống spam (TC_024)", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 82
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 83
 await testRunner.GivenAsync("người dùng truy cập vào trang web \"http://localhost:44317/\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 84
 await testRunner.AndAsync("người dùng nhấn vào nút Đăng ký", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 85
 await testRunner.WhenAsync(string.Format("người dùng nhập thông tin đăng ký bao gồm \"{0}\", \"{1}\", \"{2}\" và \"{3}\"", ten_Dang_Nhap, email, mat_Khau, xac_Nhan_Mk), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 86
 await testRunner.AndAsync("người dùng nhấn nút Đăng ký trên giao diện đăng ký", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 87
 await testRunner.ThenAsync("nút Đăng ký phải bị vô hiệu hóa trong lúc chờ xử lý", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Kiểm tra hiển thị cảnh báo đỏ khi để trống các trường bắt buộc (TC_025)")]
        [global::NUnit.Framework.CategoryAttribute("hien_thi_ui_canh_bao")]
        [global::NUnit.Framework.TestCaseAttribute("TC_USER_DANGKY_025", "TD_25_01", "\"\"", "\"\"", "\"\"", "\"\"", "[loi_canh_bao_do]", "27", null)]
        public async global::System.Threading.Tasks.Task KiểmTraHiểnThịCảnhBaoDỏKhiDểTrốngCacTrườngBắtBuộcTC_025(string tc_Id, string data_Id, string ten_Dang_Nhap, string email, string mat_Khau, string xac_Nhan_Mk, string ket_Qua_Mong_Doi, string @__pickleIndex, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "hien_thi_ui_canh_bao"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("tc_id", tc_Id);
            argumentsOfScenario.Add("data_id", data_Id);
            argumentsOfScenario.Add("ten_dang_nhap", ten_Dang_Nhap);
            argumentsOfScenario.Add("email", email);
            argumentsOfScenario.Add("mat_khau", mat_Khau);
            argumentsOfScenario.Add("xac_nhan_mk", xac_Nhan_Mk);
            argumentsOfScenario.Add("ket_qua_mong_doi", ket_Qua_Mong_Doi);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Kiểm tra hiển thị cảnh báo đỏ khi để trống các trường bắt buộc (TC_025)", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 94
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 95
 await testRunner.GivenAsync("người dùng truy cập vào trang web \"http://localhost:44317/\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 96
 await testRunner.AndAsync("người dùng nhấn vào nút Đăng ký", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 97
 await testRunner.WhenAsync(string.Format("người dùng nhập thông tin đăng ký bao gồm \"{0}\", \"{1}\", \"{2}\" và \"{3}\"", ten_Dang_Nhap, email, mat_Khau, xac_Nhan_Mk), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 98
 await testRunner.AndAsync("người dùng nhấn nút Đăng ký trên giao diện đăng ký", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 99
 await testRunner.ThenAsync("hệ thống hiển thị cảnh báo đỏ cho tất cả các trường", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Kiểm tra xem vùng nhập mật khẩu có phải là type password")]
        [global::NUnit.Framework.CategoryAttribute("hien_thi_ui_an_mat_khau")]
        [global::NUnit.Framework.TestCaseAttribute("TC_USER_DANGKY_026", "TD_26_01", "MinhPham", "Minh@gmail.com", "Minh134@", "Minh134@", "28", null)]
        public async global::System.Threading.Tasks.Task KiểmTraXemVungNhậpMậtKhẩuCoPhảiLaTypePassword(string tc_Id, string data_Id, string ten_Dang_Nhap, string email, string mat_Khau, string xac_Nhan_Mk, string @__pickleIndex, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "hien_thi_ui_an_mat_khau"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("tc_id", tc_Id);
            argumentsOfScenario.Add("data_id", data_Id);
            argumentsOfScenario.Add("ten_dang_nhap", ten_Dang_Nhap);
            argumentsOfScenario.Add("email", email);
            argumentsOfScenario.Add("mat_khau", mat_Khau);
            argumentsOfScenario.Add("xac_nhan_mk", xac_Nhan_Mk);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Kiểm tra xem vùng nhập mật khẩu có phải là type password", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 106
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 107
 await testRunner.GivenAsync("người dùng truy cập vào trang web \"http://localhost:44317/\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 108
 await testRunner.AndAsync("người dùng nhấn vào nút Đăng ký", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 109
 await testRunner.WhenAsync(string.Format("người dùng nhập thông tin đăng ký bao gồm \"{0}\", \"{1}\", \"{2}\" và \"{3}\"", ten_Dang_Nhap, email, mat_Khau, xac_Nhan_Mk), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 110
 await testRunner.AndAsync("mật khẩu phải ở dạng dấu chấm", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
    }
}
#pragma warning restore
#endregion
