// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace KDPM_ReqnrollSeleniumAutomationTesting_Nhom5.Features
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::NUnit.Framework.TestFixtureAttribute()]
    [global::NUnit.Framework.DescriptionAttribute("Giỏ hàng")]
    [global::NUnit.Framework.FixtureLifeCycleAttribute(global::NUnit.Framework.LifeCycle.InstancePerTestCase)]
    public partial class GiỏHangFeature
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "Features", "Giỏ hàng", "Kiểm thử chức năng Giỏ hàng của hệ thống MedForAll.\r\nCác scenario trong file này " +
                "được đồng bộ theo test case Selenium Python đã chạy.", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
#line 1 "GioHang.feature"
#line hidden
        
        [global::NUnit.Framework.OneTimeSetUpAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        [global::NUnit.Framework.OneTimeTearDownAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        [global::NUnit.Framework.SetUpAttribute()]
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        [global::NUnit.Framework.TearDownAttribute()]
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<global::NUnit.Framework.TestContext>(global::NUnit.Framework.TestContext.CurrentContext);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/GioHang.feature.ndjson", 37);
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("TC_CART_001 - Mở trang giỏ hàng")]
        [global::NUnit.Framework.CategoryAttribute("Cart")]
        [global::NUnit.Framework.CategoryAttribute("TC_CART_001")]
        [global::NUnit.Framework.CategoryAttribute("Severity_LOW")]
        [global::NUnit.Framework.CategoryAttribute("Priority_LOW")]
        public async global::System.Threading.Tasks.Task TC_CART_001_MởTrangGiỏHang()
        {
            string[] tagsOfScenario = new string[] {
                    "Cart",
                    "TC_CART_001",
                    "Severity_LOW",
                    "Priority_LOW"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "0";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("TC_CART_001 - Mở trang giỏ hàng", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 6
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 7
await testRunner.WhenAsync("User truy cập trang giỏ hàng", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 8
await testRunner.ThenAsync("trang giỏ hàng mở được và không hiển thị lỗi hệ thống", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("TC_CART_002 - Thêm thuốc còn hàng vào giỏ bằng Ajax")]
        [global::NUnit.Framework.CategoryAttribute("Cart")]
        [global::NUnit.Framework.CategoryAttribute("TC_CART_002")]
        [global::NUnit.Framework.CategoryAttribute("Severity_HIGH")]
        [global::NUnit.Framework.CategoryAttribute("Priority_HIGH")]
        public async global::System.Threading.Tasks.Task TC_CART_002_ThemThuốcConHangVaoGiỏBằngAjax()
        {
            string[] tagsOfScenario = new string[] {
                    "Cart",
                    "TC_CART_002",
                    "Severity_HIGH",
                    "Priority_HIGH"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "1";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("TC_CART_002 - Thêm thuốc còn hàng vào giỏ bằng Ajax", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 11
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 12
await testRunner.WhenAsync("User thêm thuốc còn hàng vào giỏ bằng Ajax", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 13
await testRunner.ThenAsync("giỏ hàng hiển thị thuốc vừa thêm", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("TC_CART_003 - Thêm trùng cùng một thuốc")]
        [global::NUnit.Framework.CategoryAttribute("Cart")]
        [global::NUnit.Framework.CategoryAttribute("TC_CART_003")]
        [global::NUnit.Framework.CategoryAttribute("Severity_MEDIUM")]
        [global::NUnit.Framework.CategoryAttribute("Priority_MEDIUM")]
        public async global::System.Threading.Tasks.Task TC_CART_003_ThemTrungCungMộtThuốc()
        {
            string[] tagsOfScenario = new string[] {
                    "Cart",
                    "TC_CART_003",
                    "Severity_MEDIUM",
                    "Priority_MEDIUM"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "2";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("TC_CART_003 - Thêm trùng cùng một thuốc", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 16
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 17
await testRunner.GivenAsync("trong giỏ hàng đã có thuốc còn hàng", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 18
await testRunner.WhenAsync("User thêm trùng cùng một thuốc vào giỏ", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 19
await testRunner.ThenAsync("số lượng thuốc trong giỏ phải tăng lên", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("TC_CART_004 - Giỏ hàng có nhiều sản phẩm")]
        [global::NUnit.Framework.CategoryAttribute("Cart")]
        [global::NUnit.Framework.CategoryAttribute("TC_CART_004")]
        [global::NUnit.Framework.CategoryAttribute("Severity_MEDIUM")]
        [global::NUnit.Framework.CategoryAttribute("Priority_MEDIUM")]
        public async global::System.Threading.Tasks.Task TC_CART_004_GiỏHangCoNhiềuSảnPhẩm()
        {
            string[] tagsOfScenario = new string[] {
                    "Cart",
                    "TC_CART_004",
                    "Severity_MEDIUM",
                    "Priority_MEDIUM"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "3";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("TC_CART_004 - Giỏ hàng có nhiều sản phẩm", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 22
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 23
await testRunner.WhenAsync("User thêm nhiều thuốc khác nhau vào giỏ", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 24
await testRunner.ThenAsync("giỏ hàng hiển thị đủ nhiều thuốc khác nhau", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("TC_CART_005 - Kiểm tra tổng tiền bằng tổng thành tiền các dòng")]
        [global::NUnit.Framework.CategoryAttribute("Cart")]
        [global::NUnit.Framework.CategoryAttribute("TC_CART_005")]
        [global::NUnit.Framework.CategoryAttribute("Severity_HIGH")]
        [global::NUnit.Framework.CategoryAttribute("Priority_HIGH")]
        public async global::System.Threading.Tasks.Task TC_CART_005_KiểmTraTổngTiềnBằngTổngThanhTiềnCacDong()
        {
            string[] tagsOfScenario = new string[] {
                    "Cart",
                    "TC_CART_005",
                    "Severity_HIGH",
                    "Priority_HIGH"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "4";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("TC_CART_005 - Kiểm tra tổng tiền bằng tổng thành tiền các dòng", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 27
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 28
await testRunner.GivenAsync("trong giỏ hàng có nhiều thuốc", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 29
await testRunner.WhenAsync("User truy cập trang giỏ hàng", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 30
await testRunner.ThenAsync("tổng tiền giỏ hàng phải bằng tổng thành tiền các dòng sản phẩm", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("TC_CART_006 - Hover mini cart")]
        [global::NUnit.Framework.CategoryAttribute("Cart")]
        [global::NUnit.Framework.CategoryAttribute("TC_CART_006")]
        [global::NUnit.Framework.CategoryAttribute("Severity_LOW")]
        [global::NUnit.Framework.CategoryAttribute("Priority_LOW")]
        public async global::System.Threading.Tasks.Task TC_CART_006_HoverMiniCart()
        {
            string[] tagsOfScenario = new string[] {
                    "Cart",
                    "TC_CART_006",
                    "Severity_LOW",
                    "Priority_LOW"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "5";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("TC_CART_006 - Hover mini cart", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 33
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 34
await testRunner.GivenAsync("trong giỏ hàng đã có thuốc còn hàng", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 35
await testRunner.WhenAsync("User hover vào mini cart", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 36
await testRunner.ThenAsync("mini cart hiển thị danh sách sản phẩm", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("TC_CART_007 - Nhấn tên thuốc trong mini cart")]
        [global::NUnit.Framework.CategoryAttribute("Cart")]
        [global::NUnit.Framework.CategoryAttribute("TC_CART_007")]
        [global::NUnit.Framework.CategoryAttribute("Severity_HIGH")]
        [global::NUnit.Framework.CategoryAttribute("Priority_MEDIUM")]
        public async global::System.Threading.Tasks.Task TC_CART_007_NhấnTenThuốcTrongMiniCart()
        {
            string[] tagsOfScenario = new string[] {
                    "Cart",
                    "TC_CART_007",
                    "Severity_HIGH",
                    "Priority_MEDIUM"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "6";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("TC_CART_007 - Nhấn tên thuốc trong mini cart", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 39
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 40
await testRunner.GivenAsync("trong giỏ hàng đã có thuốc còn hàng", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 41
await testRunner.WhenAsync("User nhấn tên thuốc trong mini cart", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 42
await testRunner.ThenAsync("hệ thống chuyển sang trang chi tiết thuốc và không hiển thị lỗi hệ thống", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("TC_CART_008 - Nhấn tên thuốc trong trang giỏ hàng chi tiết")]
        [global::NUnit.Framework.CategoryAttribute("Cart")]
        [global::NUnit.Framework.CategoryAttribute("TC_CART_008")]
        [global::NUnit.Framework.CategoryAttribute("Severity_HIGH")]
        [global::NUnit.Framework.CategoryAttribute("Priority_MEDIUM")]
        public async global::System.Threading.Tasks.Task TC_CART_008_NhấnTenThuốcTrongTrangGiỏHangChiTiết()
        {
            string[] tagsOfScenario = new string[] {
                    "Cart",
                    "TC_CART_008",
                    "Severity_HIGH",
                    "Priority_MEDIUM"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "7";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("TC_CART_008 - Nhấn tên thuốc trong trang giỏ hàng chi tiết", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 45
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 46
await testRunner.GivenAsync("trong giỏ hàng đã có thuốc còn hàng", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 47
await testRunner.WhenAsync("User nhấn tên thuốc trong trang giỏ hàng chi tiết", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 48
await testRunner.ThenAsync("hệ thống chuyển sang trang chi tiết thuốc và không hiển thị lỗi hệ thống", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("TC_CART_009 - Tăng số lượng bằng nút cộng")]
        [global::NUnit.Framework.CategoryAttribute("Cart")]
        [global::NUnit.Framework.CategoryAttribute("TC_CART_009")]
        [global::NUnit.Framework.CategoryAttribute("Severity_HIGH")]
        [global::NUnit.Framework.CategoryAttribute("Priority_HIGH")]
        public async global::System.Threading.Tasks.Task TC_CART_009_TangSốLượngBằngNutCộng()
        {
            string[] tagsOfScenario = new string[] {
                    "Cart",
                    "TC_CART_009",
                    "Severity_HIGH",
                    "Priority_HIGH"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "8";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("TC_CART_009 - Tăng số lượng bằng nút cộng", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 51
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 52
await testRunner.GivenAsync("trong giỏ hàng đã có thuốc còn hàng", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 53
await testRunner.WhenAsync("User tăng số lượng thuốc bằng nút cộng", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 54
await testRunner.ThenAsync("số lượng thuốc tăng lên", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 55
await testRunner.AndAsync("tổng tiền giỏ hàng tăng lên", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("TC_CART_010 - Giảm số lượng bằng nút trừ")]
        [global::NUnit.Framework.CategoryAttribute("Cart")]
        [global::NUnit.Framework.CategoryAttribute("TC_CART_010")]
        [global::NUnit.Framework.CategoryAttribute("Severity_HIGH")]
        [global::NUnit.Framework.CategoryAttribute("Priority_HIGH")]
        public async global::System.Threading.Tasks.Task TC_CART_010_GiảmSốLượngBằngNutTrừ()
        {
            string[] tagsOfScenario = new string[] {
                    "Cart",
                    "TC_CART_010",
                    "Severity_HIGH",
                    "Priority_HIGH"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "9";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("TC_CART_010 - Giảm số lượng bằng nút trừ", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 58
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 59
await testRunner.GivenAsync("trong giỏ hàng đã có thuốc còn hàng với số lượng lớn hơn 1", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 60
await testRunner.WhenAsync("User giảm số lượng thuốc bằng nút trừ", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 61
await testRunner.ThenAsync("số lượng thuốc giảm xuống", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 62
await testRunner.AndAsync("tổng tiền giỏ hàng giảm xuống", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("TC_CART_011 - Không cho giảm số lượng dưới 1")]
        [global::NUnit.Framework.CategoryAttribute("Cart")]
        [global::NUnit.Framework.CategoryAttribute("TC_CART_011")]
        [global::NUnit.Framework.CategoryAttribute("Severity_HIGH")]
        [global::NUnit.Framework.CategoryAttribute("Priority_HIGH")]
        public async global::System.Threading.Tasks.Task TC_CART_011_KhongChoGiảmSốLượngDưới1()
        {
            string[] tagsOfScenario = new string[] {
                    "Cart",
                    "TC_CART_011",
                    "Severity_HIGH",
                    "Priority_HIGH"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "10";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("TC_CART_011 - Không cho giảm số lượng dưới 1", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 65
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 66
await testRunner.GivenAsync("trong giỏ hàng đã có thuốc còn hàng với số lượng bằng 1", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 67
await testRunner.WhenAsync("User giảm số lượng thuốc bằng nút trừ", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 68
await testRunner.ThenAsync("số lượng thuốc không được nhỏ hơn 1", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("TC_CART_012 - Bấm cộng liên tục nhiều lần")]
        [global::NUnit.Framework.CategoryAttribute("Cart")]
        [global::NUnit.Framework.CategoryAttribute("TC_CART_012")]
        [global::NUnit.Framework.CategoryAttribute("Severity_MEDIUM")]
        [global::NUnit.Framework.CategoryAttribute("Priority_MEDIUM")]
        public async global::System.Threading.Tasks.Task TC_CART_012_BấmCộngLienTụcNhiềuLần()
        {
            string[] tagsOfScenario = new string[] {
                    "Cart",
                    "TC_CART_012",
                    "Severity_MEDIUM",
                    "Priority_MEDIUM"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "11";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("TC_CART_012 - Bấm cộng liên tục nhiều lần", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 71
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 72
await testRunner.GivenAsync("trong giỏ hàng đã có thuốc còn hàng", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 73
await testRunner.WhenAsync("User bấm nút cộng liên tục nhiều lần", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 74
await testRunner.ThenAsync("số lượng thuốc vẫn được cập nhật hợp lệ", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 75
await testRunner.AndAsync("tổng tiền giỏ hàng vẫn hợp lệ", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("TC_CART_013 - Không cho cập nhật số lượng vượt tồn kho")]
        [global::NUnit.Framework.CategoryAttribute("Cart")]
        [global::NUnit.Framework.CategoryAttribute("TC_CART_013")]
        [global::NUnit.Framework.CategoryAttribute("Severity_CRITICAL")]
        [global::NUnit.Framework.CategoryAttribute("Priority_HIGH")]
        public async global::System.Threading.Tasks.Task TC_CART_013_KhongChoCậpNhậtSốLượngVượtTồnKho()
        {
            string[] tagsOfScenario = new string[] {
                    "Cart",
                    "TC_CART_013",
                    "Severity_CRITICAL",
                    "Priority_HIGH"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "12";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("TC_CART_013 - Không cho cập nhật số lượng vượt tồn kho", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 78
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 79
await testRunner.GivenAsync("trong giỏ hàng đã có thuốc còn hàng", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 80
await testRunner.WhenAsync("User cập nhật số lượng thuốc vượt tồn kho bằng Ajax", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 81
await testRunner.ThenAsync("hệ thống phải chặn số lượng vượt tồn kho", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("TC_CART_014 - Không cho thêm thuốc hết hàng vào giỏ")]
        [global::NUnit.Framework.CategoryAttribute("Cart")]
        [global::NUnit.Framework.CategoryAttribute("TC_CART_014")]
        [global::NUnit.Framework.CategoryAttribute("Severity_CRITICAL")]
        [global::NUnit.Framework.CategoryAttribute("Priority_HIGH")]
        public async global::System.Threading.Tasks.Task TC_CART_014_KhongChoThemThuốcHếtHangVaoGiỏ()
        {
            string[] tagsOfScenario = new string[] {
                    "Cart",
                    "TC_CART_014",
                    "Severity_CRITICAL",
                    "Priority_HIGH"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "13";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("TC_CART_014 - Không cho thêm thuốc hết hàng vào giỏ", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 84
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 85
await testRunner.WhenAsync("User thêm thuốc hết hàng vào giỏ bằng Ajax", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 86
await testRunner.ThenAsync("hệ thống không được thêm thuốc hết hàng vào giỏ", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("TC_CART_015 - Mở modal xóa rồi bấm Đóng")]
        [global::NUnit.Framework.CategoryAttribute("Cart")]
        [global::NUnit.Framework.CategoryAttribute("TC_CART_015")]
        [global::NUnit.Framework.CategoryAttribute("Severity_MEDIUM")]
        [global::NUnit.Framework.CategoryAttribute("Priority_MEDIUM")]
        public async global::System.Threading.Tasks.Task TC_CART_015_MởModalXoaRồiBấmDong()
        {
            string[] tagsOfScenario = new string[] {
                    "Cart",
                    "TC_CART_015",
                    "Severity_MEDIUM",
                    "Priority_MEDIUM"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "14";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("TC_CART_015 - Mở modal xóa rồi bấm Đóng", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 89
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 90
await testRunner.GivenAsync("trong giỏ hàng đã có thuốc còn hàng", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 91
await testRunner.WhenAsync("User mở modal xóa sản phẩm rồi bấm Đóng", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 92
await testRunner.ThenAsync("modal xóa được đóng lại", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 93
await testRunner.AndAsync("sản phẩm không bị xóa khỏi giỏ hàng", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("TC_CART_016 - Xác nhận xóa sản phẩm khỏi giỏ")]
        [global::NUnit.Framework.CategoryAttribute("Cart")]
        [global::NUnit.Framework.CategoryAttribute("TC_CART_016")]
        [global::NUnit.Framework.CategoryAttribute("Severity_MEDIUM")]
        [global::NUnit.Framework.CategoryAttribute("Priority_LOW")]
        [global::NUnit.Framework.CategoryAttribute("Skip_DataChanging")]
        public async global::System.Threading.Tasks.Task TC_CART_016_XacNhậnXoaSảnPhẩmKhỏiGiỏ()
        {
            string[] tagsOfScenario = new string[] {
                    "Cart",
                    "TC_CART_016",
                    "Severity_MEDIUM",
                    "Priority_LOW",
                    "Skip_DataChanging"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "15";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("TC_CART_016 - Xác nhận xóa sản phẩm khỏi giỏ", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 96
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 97
await testRunner.GivenAsync("trong giỏ hàng đã có thuốc dùng để kiểm thử xóa", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 98
await testRunner.WhenAsync("User xác nhận xóa sản phẩm khỏi giỏ hàng", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 99
await testRunner.ThenAsync("sản phẩm bị xóa khỏi giỏ hàng", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("TC_CART_017 - Chuyển đổi Giao hàng và Nhận tại nhà thuốc")]
        [global::NUnit.Framework.CategoryAttribute("Cart")]
        [global::NUnit.Framework.CategoryAttribute("TC_CART_017")]
        [global::NUnit.Framework.CategoryAttribute("Severity_MEDIUM")]
        [global::NUnit.Framework.CategoryAttribute("Priority_MEDIUM")]
        public async global::System.Threading.Tasks.Task TC_CART_017_ChuyểnDổiGiaoHangVaNhậnTạiNhaThuốc()
        {
            string[] tagsOfScenario = new string[] {
                    "Cart",
                    "TC_CART_017",
                    "Severity_MEDIUM",
                    "Priority_MEDIUM"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "16";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("TC_CART_017 - Chuyển đổi Giao hàng và Nhận tại nhà thuốc", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 102
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 103
await testRunner.GivenAsync("trong giỏ hàng đã có thuốc còn hàng", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 104
await testRunner.WhenAsync("User chuyển đổi giữa Giao hàng tận nơi và Nhận tại nhà thuốc", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 105
await testRunner.ThenAsync("form giao hàng và form nhận tại nhà thuốc hiển thị đúng theo lựa chọn", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("TC_CART_018 - Bắt buộc nhập họ tên")]
        [global::NUnit.Framework.CategoryAttribute("Cart")]
        [global::NUnit.Framework.CategoryAttribute("TC_CART_018")]
        [global::NUnit.Framework.CategoryAttribute("Severity_MEDIUM")]
        [global::NUnit.Framework.CategoryAttribute("Priority_MEDIUM")]
        public async global::System.Threading.Tasks.Task TC_CART_018_BắtBuộcNhậpHọTen()
        {
            string[] tagsOfScenario = new string[] {
                    "Cart",
                    "TC_CART_018",
                    "Severity_MEDIUM",
                    "Priority_MEDIUM"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "17";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("TC_CART_018 - Bắt buộc nhập họ tên", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 108
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 109
await testRunner.GivenAsync("trong giỏ hàng đã có thuốc còn hàng", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 110
await testRunner.WhenAsync("User đặt hàng nhưng để trống họ tên", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 111
await testRunner.ThenAsync("hệ thống hiển thị validation cho trường họ tên", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("TC_CART_019 - Họ tên chỉ nhập khoảng trắng")]
        [global::NUnit.Framework.CategoryAttribute("Cart")]
        [global::NUnit.Framework.CategoryAttribute("TC_CART_019")]
        [global::NUnit.Framework.CategoryAttribute("Severity_HIGH")]
        [global::NUnit.Framework.CategoryAttribute("Priority_HIGH")]
        public async global::System.Threading.Tasks.Task TC_CART_019_HọTenChỉNhậpKhoảngTrắng()
        {
            string[] tagsOfScenario = new string[] {
                    "Cart",
                    "TC_CART_019",
                    "Severity_HIGH",
                    "Priority_HIGH"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "18";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("TC_CART_019 - Họ tên chỉ nhập khoảng trắng", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 114
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 115
await testRunner.GivenAsync("trong giỏ hàng đã có thuốc còn hàng", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 116
await testRunner.WhenAsync("User đặt hàng với họ tên chỉ toàn khoảng trắng", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 117
await testRunner.ThenAsync("hệ thống phải chặn họ tên không hợp lệ", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("TC_CART_020 - Số điện thoại sai định dạng")]
        [global::NUnit.Framework.CategoryAttribute("Cart")]
        [global::NUnit.Framework.CategoryAttribute("TC_CART_020")]
        [global::NUnit.Framework.CategoryAttribute("Severity_MEDIUM")]
        [global::NUnit.Framework.CategoryAttribute("Priority_MEDIUM")]
        public async global::System.Threading.Tasks.Task TC_CART_020_SốDiệnThoạiSaiDịnhDạng()
        {
            string[] tagsOfScenario = new string[] {
                    "Cart",
                    "TC_CART_020",
                    "Severity_MEDIUM",
                    "Priority_MEDIUM"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "19";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("TC_CART_020 - Số điện thoại sai định dạng", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 120
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 121
await testRunner.GivenAsync("trong giỏ hàng đã có thuốc còn hàng", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 122
await testRunner.WhenAsync("User đặt hàng với số điện thoại sai định dạng", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 123
await testRunner.ThenAsync("hệ thống hiển thị validation cho trường số điện thoại", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("TC_CART_021 - Email sai định dạng")]
        [global::NUnit.Framework.CategoryAttribute("Cart")]
        [global::NUnit.Framework.CategoryAttribute("TC_CART_021")]
        [global::NUnit.Framework.CategoryAttribute("Severity_MEDIUM")]
        [global::NUnit.Framework.CategoryAttribute("Priority_MEDIUM")]
        public async global::System.Threading.Tasks.Task TC_CART_021_EmailSaiDịnhDạng()
        {
            string[] tagsOfScenario = new string[] {
                    "Cart",
                    "TC_CART_021",
                    "Severity_MEDIUM",
                    "Priority_MEDIUM"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "20";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("TC_CART_021 - Email sai định dạng", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 126
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 127
await testRunner.GivenAsync("trong giỏ hàng đã có thuốc còn hàng", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 128
await testRunner.WhenAsync("User đặt hàng với email sai định dạng", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 129
await testRunner.ThenAsync("hệ thống hiển thị validation cho trường email", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("TC_CART_022 - Giao hàng nhưng chưa chọn Tỉnh Thành")]
        [global::NUnit.Framework.CategoryAttribute("Cart")]
        [global::NUnit.Framework.CategoryAttribute("TC_CART_022")]
        [global::NUnit.Framework.CategoryAttribute("Severity_MEDIUM")]
        [global::NUnit.Framework.CategoryAttribute("Priority_MEDIUM")]
        public async global::System.Threading.Tasks.Task TC_CART_022_GiaoHangNhưngChưaChọnTỉnhThanh()
        {
            string[] tagsOfScenario = new string[] {
                    "Cart",
                    "TC_CART_022",
                    "Severity_MEDIUM",
                    "Priority_MEDIUM"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "21";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("TC_CART_022 - Giao hàng nhưng chưa chọn Tỉnh Thành", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 132
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 133
await testRunner.GivenAsync("trong giỏ hàng đã có thuốc còn hàng", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 134
await testRunner.WhenAsync("User chọn giao hàng tận nơi nhưng chưa chọn Tỉnh Thành", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 135
await testRunner.ThenAsync("hệ thống hiển thị validation cho trường Tỉnh Thành", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("TC_CART_023 - Giao hàng nhưng chưa chọn Phường Xã")]
        [global::NUnit.Framework.CategoryAttribute("Cart")]
        [global::NUnit.Framework.CategoryAttribute("TC_CART_023")]
        [global::NUnit.Framework.CategoryAttribute("Severity_MEDIUM")]
        [global::NUnit.Framework.CategoryAttribute("Priority_MEDIUM")]
        public async global::System.Threading.Tasks.Task TC_CART_023_GiaoHangNhưngChưaChọnPhườngXa()
        {
            string[] tagsOfScenario = new string[] {
                    "Cart",
                    "TC_CART_023",
                    "Severity_MEDIUM",
                    "Priority_MEDIUM"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "22";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("TC_CART_023 - Giao hàng nhưng chưa chọn Phường Xã", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 138
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 139
await testRunner.GivenAsync("trong giỏ hàng đã có thuốc còn hàng", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 140
await testRunner.WhenAsync("User chọn giao hàng tận nơi nhưng chưa chọn Phường Xã", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 141
await testRunner.ThenAsync("hệ thống hiển thị validation cho trường Phường Xã", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("TC_CART_024 - Giao hàng nhưng chưa nhập số nhà")]
        [global::NUnit.Framework.CategoryAttribute("Cart")]
        [global::NUnit.Framework.CategoryAttribute("TC_CART_024")]
        [global::NUnit.Framework.CategoryAttribute("Severity_MEDIUM")]
        [global::NUnit.Framework.CategoryAttribute("Priority_MEDIUM")]
        public async global::System.Threading.Tasks.Task TC_CART_024_GiaoHangNhưngChưaNhậpSốNha()
        {
            string[] tagsOfScenario = new string[] {
                    "Cart",
                    "TC_CART_024",
                    "Severity_MEDIUM",
                    "Priority_MEDIUM"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "23";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("TC_CART_024 - Giao hàng nhưng chưa nhập số nhà", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 144
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 145
await testRunner.GivenAsync("trong giỏ hàng đã có thuốc còn hàng", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 146
await testRunner.WhenAsync("User chọn giao hàng tận nơi nhưng chưa nhập số nhà tên đường", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 147
await testRunner.ThenAsync("hệ thống hiển thị validation cho trường địa chỉ cụ thể", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("TC_CART_025 - Nhận tại nhà thuốc nhưng chưa chọn nhà thuốc")]
        [global::NUnit.Framework.CategoryAttribute("Cart")]
        [global::NUnit.Framework.CategoryAttribute("TC_CART_025")]
        [global::NUnit.Framework.CategoryAttribute("Severity_MEDIUM")]
        [global::NUnit.Framework.CategoryAttribute("Priority_MEDIUM")]
        public async global::System.Threading.Tasks.Task TC_CART_025_NhậnTạiNhaThuốcNhưngChưaChọnNhaThuốc()
        {
            string[] tagsOfScenario = new string[] {
                    "Cart",
                    "TC_CART_025",
                    "Severity_MEDIUM",
                    "Priority_MEDIUM"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "24";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("TC_CART_025 - Nhận tại nhà thuốc nhưng chưa chọn nhà thuốc", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 150
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 151
await testRunner.GivenAsync("trong giỏ hàng đã có thuốc còn hàng", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 152
await testRunner.WhenAsync("User chọn nhận tại nhà thuốc nhưng chưa chọn nhà thuốc", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 153
await testRunner.ThenAsync("hệ thống hiển thị thông báo yêu cầu chọn nhà thuốc", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("TC_CART_026 - Chọn thanh toán QR Code")]
        [global::NUnit.Framework.CategoryAttribute("Cart")]
        [global::NUnit.Framework.CategoryAttribute("TC_CART_026")]
        [global::NUnit.Framework.CategoryAttribute("Severity_HIGH")]
        [global::NUnit.Framework.CategoryAttribute("Priority_HIGH")]
        public async global::System.Threading.Tasks.Task TC_CART_026_ChọnThanhToanQRCode()
        {
            string[] tagsOfScenario = new string[] {
                    "Cart",
                    "TC_CART_026",
                    "Severity_HIGH",
                    "Priority_HIGH"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "25";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("TC_CART_026 - Chọn thanh toán QR Code", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 156
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 157
await testRunner.GivenAsync("trong giỏ hàng đã có thuốc còn hàng", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 158
await testRunner.WhenAsync("User đặt hàng bằng phương thức thanh toán QR Code", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 159
await testRunner.ThenAsync("modal QR Code được hiển thị", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 160
await testRunner.AndAsync("QR Code có thông tin thanh toán hợp lệ", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("TC_CART_027 - Bấm Tôi đã chuyển tiền khi test QR")]
        [global::NUnit.Framework.CategoryAttribute("Cart")]
        [global::NUnit.Framework.CategoryAttribute("TC_CART_027")]
        [global::NUnit.Framework.CategoryAttribute("Severity_MEDIUM")]
        [global::NUnit.Framework.CategoryAttribute("Priority_MEDIUM")]
        public async global::System.Threading.Tasks.Task TC_CART_027_BấmToiDaChuyểnTiềnKhiTestQR()
        {
            string[] tagsOfScenario = new string[] {
                    "Cart",
                    "TC_CART_027",
                    "Severity_MEDIUM",
                    "Priority_MEDIUM"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "26";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("TC_CART_027 - Bấm Tôi đã chuyển tiền khi test QR", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 163
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 164
await testRunner.GivenAsync("modal QR Code đang được hiển thị", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 165
await testRunner.WhenAsync("User bấm nút Tôi đã chuyển tiền", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 166
await testRunner.ThenAsync("hệ thống hiển thị trạng thái kiểm tra thanh toán", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("TC_CART_028 - Double click nút Đặt hàng ngay với QR")]
        [global::NUnit.Framework.CategoryAttribute("Cart")]
        [global::NUnit.Framework.CategoryAttribute("TC_CART_028")]
        [global::NUnit.Framework.CategoryAttribute("Severity_MEDIUM")]
        [global::NUnit.Framework.CategoryAttribute("Priority_MEDIUM")]
        public async global::System.Threading.Tasks.Task TC_CART_028_DoubleClickNutDặtHangNgayVớiQR()
        {
            string[] tagsOfScenario = new string[] {
                    "Cart",
                    "TC_CART_028",
                    "Severity_MEDIUM",
                    "Priority_MEDIUM"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "27";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("TC_CART_028 - Double click nút Đặt hàng ngay với QR", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 169
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 170
await testRunner.GivenAsync("trong giỏ hàng đã có thuốc còn hàng", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 171
await testRunner.WhenAsync("User double click nút Đặt hàng ngay với QR", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 172
await testRunner.ThenAsync("modal QR Code vẫn hiển thị hợp lệ", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 173
await testRunner.AndAsync("hệ thống không hiển thị lỗi Server Error", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("TC_CART_029 - Hover nút Mua thêm thuốc khác")]
        [global::NUnit.Framework.CategoryAttribute("Cart")]
        [global::NUnit.Framework.CategoryAttribute("TC_CART_029")]
        [global::NUnit.Framework.CategoryAttribute("Severity_LOW")]
        [global::NUnit.Framework.CategoryAttribute("Priority_LOW")]
        public async global::System.Threading.Tasks.Task TC_CART_029_HoverNutMuaThemThuốcKhac()
        {
            string[] tagsOfScenario = new string[] {
                    "Cart",
                    "TC_CART_029",
                    "Severity_LOW",
                    "Priority_LOW"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "28";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("TC_CART_029 - Hover nút Mua thêm thuốc khác", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 176
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 177
await testRunner.GivenAsync("trong giỏ hàng đã có thuốc còn hàng", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 178
await testRunner.WhenAsync("User hover nút Mua thêm thuốc khác", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 179
await testRunner.ThenAsync("chữ trên nút vẫn dễ đọc sau khi hover", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("TC_CART_030 - Responsive mobile màn hình 390px")]
        [global::NUnit.Framework.CategoryAttribute("Cart")]
        [global::NUnit.Framework.CategoryAttribute("TC_CART_030")]
        [global::NUnit.Framework.CategoryAttribute("Severity_LOW")]
        [global::NUnit.Framework.CategoryAttribute("Priority_LOW")]
        public async global::System.Threading.Tasks.Task TC_CART_030_ResponsiveMobileManHinh390Px()
        {
            string[] tagsOfScenario = new string[] {
                    "Cart",
                    "TC_CART_030",
                    "Severity_LOW",
                    "Priority_LOW"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "29";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("TC_CART_030 - Responsive mobile màn hình 390px", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 182
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 183
await testRunner.GivenAsync("trình duyệt đang ở kích thước màn hình mobile 390px", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 184
await testRunner.WhenAsync("User truy cập trang giỏ hàng", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 185
await testRunner.ThenAsync("giao diện giỏ hàng không bị tràn ngang nghiêm trọng trên mobile", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("TC_CART_031 - Nhập dữ liệu XSS vào họ tên")]
        [global::NUnit.Framework.CategoryAttribute("Cart")]
        [global::NUnit.Framework.CategoryAttribute("TC_CART_031")]
        [global::NUnit.Framework.CategoryAttribute("Severity_HIGH")]
        [global::NUnit.Framework.CategoryAttribute("Priority_HIGH")]
        public async global::System.Threading.Tasks.Task TC_CART_031_NhậpDữLiệuXSSVaoHọTen()
        {
            string[] tagsOfScenario = new string[] {
                    "Cart",
                    "TC_CART_031",
                    "Severity_HIGH",
                    "Priority_HIGH"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "30";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("TC_CART_031 - Nhập dữ liệu XSS vào họ tên", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 188
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 189
await testRunner.GivenAsync("trong giỏ hàng đã có thuốc còn hàng", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 190
await testRunner.WhenAsync("User nhập dữ liệu XSS vào họ tên khi đặt hàng", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 191
await testRunner.ThenAsync("hệ thống không được thực thi script XSS", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("TC_CART_032 - Nhập chuỗi đặc biệt vào địa chỉ")]
        [global::NUnit.Framework.CategoryAttribute("Cart")]
        [global::NUnit.Framework.CategoryAttribute("TC_CART_032")]
        [global::NUnit.Framework.CategoryAttribute("Severity_HIGH")]
        [global::NUnit.Framework.CategoryAttribute("Priority_HIGH")]
        public async global::System.Threading.Tasks.Task TC_CART_032_NhậpChuỗiDặcBiệtVaoDịaChỉ()
        {
            string[] tagsOfScenario = new string[] {
                    "Cart",
                    "TC_CART_032",
                    "Severity_HIGH",
                    "Priority_HIGH"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "31";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("TC_CART_032 - Nhập chuỗi đặc biệt vào địa chỉ", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 194
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 195
await testRunner.GivenAsync("trong giỏ hàng đã có thuốc còn hàng", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 196
await testRunner.WhenAsync("User nhập chuỗi đặc biệt giống SQL injection vào địa chỉ", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 197
await testRunner.ThenAsync("hệ thống không hiển thị lỗi Server Error", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("TC_CART_033 - Đồng bộ số lượng khi mở 2 tab")]
        [global::NUnit.Framework.CategoryAttribute("Cart")]
        [global::NUnit.Framework.CategoryAttribute("TC_CART_033")]
        [global::NUnit.Framework.CategoryAttribute("Severity_MEDIUM")]
        [global::NUnit.Framework.CategoryAttribute("Priority_MEDIUM")]
        public async global::System.Threading.Tasks.Task TC_CART_033_DồngBộSốLượngKhiMở2Tab()
        {
            string[] tagsOfScenario = new string[] {
                    "Cart",
                    "TC_CART_033",
                    "Severity_MEDIUM",
                    "Priority_MEDIUM"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "32";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("TC_CART_033 - Đồng bộ số lượng khi mở 2 tab", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 200
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 201
await testRunner.GivenAsync("trong giỏ hàng đã có thuốc còn hàng", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 202
await testRunner.WhenAsync("User cập nhật số lượng giỏ hàng ở tab thứ nhất", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 203
await testRunner.ThenAsync("tab thứ hai sau khi reload phải hiển thị số lượng mới", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("TC_CART_034 - Admin tắt bán online rồi user thêm vào giỏ")]
        [global::NUnit.Framework.CategoryAttribute("Cart")]
        [global::NUnit.Framework.CategoryAttribute("TC_CART_034")]
        [global::NUnit.Framework.CategoryAttribute("Severity_CRITICAL")]
        [global::NUnit.Framework.CategoryAttribute("Priority_HIGH")]
        [global::NUnit.Framework.CategoryAttribute("Skip_DataChanging")]
        public async global::System.Threading.Tasks.Task TC_CART_034_AdminTắtBanOnlineRồiUserThemVaoGiỏ()
        {
            string[] tagsOfScenario = new string[] {
                    "Cart",
                    "TC_CART_034",
                    "Severity_CRITICAL",
                    "Priority_HIGH",
                    "Skip_DataChanging"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "33";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("TC_CART_034 - Admin tắt bán online rồi user thêm vào giỏ", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 206
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 207
await testRunner.GivenAsync("Admin đã tắt bán online cho thuốc kiểm thử", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 208
await testRunner.WhenAsync("User thêm thuốc đã bị tắt bán online vào giỏ", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 209
await testRunner.ThenAsync("hệ thống không được thêm thuốc đã tắt bán online vào giỏ", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("TC_CART_035 - Đặt hàng COD dữ liệu hợp lệ")]
        [global::NUnit.Framework.CategoryAttribute("Cart")]
        [global::NUnit.Framework.CategoryAttribute("TC_CART_035")]
        [global::NUnit.Framework.CategoryAttribute("Severity_MEDIUM")]
        [global::NUnit.Framework.CategoryAttribute("Priority_LOW")]
        [global::NUnit.Framework.CategoryAttribute("Skip_CreateOrder")]
        public async global::System.Threading.Tasks.Task TC_CART_035_DặtHangCODDữLiệuHợpLệ()
        {
            string[] tagsOfScenario = new string[] {
                    "Cart",
                    "TC_CART_035",
                    "Severity_MEDIUM",
                    "Priority_LOW",
                    "Skip_CreateOrder"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "34";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("TC_CART_035 - Đặt hàng COD dữ liệu hợp lệ", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 212
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 213
await testRunner.GivenAsync("trong giỏ hàng đã có thuốc còn hàng", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 214
await testRunner.WhenAsync("User đặt hàng COD với dữ liệu hợp lệ", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 215
await testRunner.ThenAsync("hệ thống tạo đơn hàng thành công", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
    }
}
#pragma warning restore
#endregion
