// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace KDPM_ReqnrollSeleniumAutomationTesting_Nhom5.Features
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::NUnit.Framework.TestFixtureAttribute()]
    [global::NUnit.Framework.DescriptionAttribute("Xem Lịch sử và Chi tiết đơn hàng")]
    [global::NUnit.Framework.FixtureLifeCycleAttribute(global::NUnit.Framework.LifeCycle.InstancePerTestCase)]
    public partial class XemLịchSửVaChiTiếtDơnHangFeature
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "Features", "Xem Lịch sử và Chi tiết đơn hàng", null, global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
#line 1 "LichSuDonHang.feature"
#line hidden
        
        [global::NUnit.Framework.OneTimeSetUpAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        [global::NUnit.Framework.OneTimeTearDownAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        [global::NUnit.Framework.SetUpAttribute()]
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        [global::NUnit.Framework.TearDownAttribute()]
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<global::NUnit.Framework.TestContext>(global::NUnit.Framework.TestContext.CurrentContext);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/LichSuDonHang.feature.ndjson", 9);
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("TC01 - Hiển thị danh sách lịch sử đơn hàng của tôi thành công")]
        [global::NUnit.Framework.CategoryAttribute("TC_TC_001")]
        [global::NUnit.Framework.CategoryAttribute("Severity_High")]
        [global::NUnit.Framework.CategoryAttribute("Priority_High")]
        public async global::System.Threading.Tasks.Task TC01_HiểnThịDanhSachLịchSửDơnHangCủaToiThanhCong()
        {
            string[] tagsOfScenario = new string[] {
                    "TC_TC_001",
                    "Severity_High",
                    "Priority_High"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "0";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("TC01 - Hiển thị danh sách lịch sử đơn hàng của tôi thành công", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 4
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 5
    await testRunner.GivenAsync("Người dùng tiến hành đăng nhập vào hệ thống với tài khoản \"tduc\" và mật khẩu \"123" +
                        "456\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 6
    await testRunner.WhenAsync("Người dùng nhấp vào menu tài khoản và chọn \"Đơn hàng của tôi\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 7
    await testRunner.ThenAsync("Hệ thống phải điều hướng sang trang lịch sử đơn hàng và hiển thị danh sách gồm 4 " +
                        "đơn hàng", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("TC02 - Quan sát thứ tự dòng đơn hàng hiển thị mới nhất lên đầu")]
        [global::NUnit.Framework.CategoryAttribute("TC_TC_002")]
        [global::NUnit.Framework.CategoryAttribute("Severity_Medium")]
        [global::NUnit.Framework.CategoryAttribute("Priority_Medium")]
        public async global::System.Threading.Tasks.Task TC02_QuanSatThứTựDongDơnHangHiểnThịMớiNhấtLenDầu()
        {
            string[] tagsOfScenario = new string[] {
                    "TC_TC_002",
                    "Severity_Medium",
                    "Priority_Medium"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "1";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("TC02 - Quan sát thứ tự dòng đơn hàng hiển thị mới nhất lên đầu", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 10
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 11
    await testRunner.GivenAsync("Người dùng tiến hành đăng nhập vào hệ thống với tài khoản \"tduc\" và mật khẩu \"123" +
                        "456\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 12
    await testRunner.WhenAsync("Người dùng nhấp vào menu tài khoản và chọn \"Đơn hàng của tôi\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 13
    await testRunner.ThenAsync("Đơn hàng mới nhất phải xếp đầu tiên trong danh sách", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("TC06 - Xem thông tin chi tiết một đơn hàng hợp lệ (Đơn #4)")]
        [global::NUnit.Framework.CategoryAttribute("TC_TC_006")]
        [global::NUnit.Framework.CategoryAttribute("Severity_High")]
        [global::NUnit.Framework.CategoryAttribute("Priority_High")]
        public async global::System.Threading.Tasks.Task TC06_XemThongTinChiTiếtMộtDơnHangHợpLệDơn4()
        {
            string[] tagsOfScenario = new string[] {
                    "TC_TC_006",
                    "Severity_High",
                    "Priority_High"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "2";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("TC06 - Xem thông tin chi tiết một đơn hàng hợp lệ (Đơn #4)", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 16
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 17
    await testRunner.GivenAsync("Người dùng tiến hành đăng nhập vào hệ thống với tài khoản \"tduc\" và mật khẩu \"123" +
                        "456\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 18
    await testRunner.WhenAsync("Người dùng nhấp vào menu tài khoản và chọn \"Đơn hàng của tôi\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 19
    await testRunner.AndAsync("Người dùng nhấn vào nút \"Chi tiết\" của mã đơn hàng \"#4\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 20
    await testRunner.ThenAsync("Hệ thống phải hiển thị chi tiết đơn hàng thỏa mãn \"Mã hiển thị đúng Đơn hàng #4, " +
                        "thời gian 12/06/2026, tổng tiền 25.000 đ\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("TC07 - Kiểm tra lỗi ẩn dòng sản phẩm thuốc đã mua (Đơn #5)")]
        [global::NUnit.Framework.CategoryAttribute("TC_TC_007")]
        [global::NUnit.Framework.CategoryAttribute("Severity_High")]
        [global::NUnit.Framework.CategoryAttribute("Priority_High")]
        public async global::System.Threading.Tasks.Task TC07_KiểmTraLỗiẨnDongSảnPhẩmThuốcDaMuaDơn5()
        {
            string[] tagsOfScenario = new string[] {
                    "TC_TC_007",
                    "Severity_High",
                    "Priority_High"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "3";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("TC07 - Kiểm tra lỗi ẩn dòng sản phẩm thuốc đã mua (Đơn #5)", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 23
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 24
    await testRunner.GivenAsync("Người dùng tiến hành đăng nhập vào hệ thống với tài khoản \"tduc\" và mật khẩu \"123" +
                        "456\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 25
    await testRunner.WhenAsync("Người dùng nhấp vào menu tài khoản và chọn \"Đơn hàng của tôi\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 26
    await testRunner.AndAsync("Người dùng nhấn vào nút \"Chi tiết\" của mã đơn hàng \"#5\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 27
    await testRunner.ThenAsync("Hệ thống phải hiển thị cửa sổ hoặc trang thông tin chi tiết của đơn hàng đó và có" +
                        " sản phẩm", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("TC12 - Kiểm tra chặn truy cập lịch sử đơn hàng khi chưa đăng nhập")]
        [global::NUnit.Framework.CategoryAttribute("TC_TC_012")]
        [global::NUnit.Framework.CategoryAttribute("Severity_High")]
        [global::NUnit.Framework.CategoryAttribute("Priority_High")]
        public async global::System.Threading.Tasks.Task TC12_KiểmTraChặnTruyCậpLịchSửDơnHangKhiChưaDangNhập()
        {
            string[] tagsOfScenario = new string[] {
                    "TC_TC_012",
                    "Severity_High",
                    "Priority_High"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "4";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("TC12 - Kiểm tra chặn truy cập lịch sử đơn hàng khi chưa đăng nhập", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 30
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 31
    await testRunner.GivenAsync("Người dùng chưa thực hiện đăng nhập vào hệ thống", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 32
    await testRunner.WhenAsync("Người dùng cố tình truy cập trực tiếp vào URL đường dẫn \"/DonHang/LichSu\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 33
    await testRunner.ThenAsync("Hệ thống phải tự động chuyển hướng người dùng sang trang đăng nhập \"/Account/Logi" +
                        "n\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("TC13 - Tấn công thay đổi URL ID đơn hàng không thuộc sở hữu (Id #1)")]
        [global::NUnit.Framework.CategoryAttribute("TC_TC_013")]
        [global::NUnit.Framework.CategoryAttribute("Severity_Critical")]
        [global::NUnit.Framework.CategoryAttribute("Priority_High")]
        public async global::System.Threading.Tasks.Task TC13_TấnCongThayDổiURLIDDơnHangKhongThuộcSởHữuId1()
        {
            string[] tagsOfScenario = new string[] {
                    "TC_TC_013",
                    "Severity_Critical",
                    "Priority_High"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "5";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("TC13 - Tấn công thay đổi URL ID đơn hàng không thuộc sở hữu (Id #1)", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 36
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 37
    await testRunner.GivenAsync("Người dùng tiến hành đăng nhập vào hệ thống với tài khoản \"tduc\" và mật khẩu \"123" +
                        "456\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 38
    await testRunner.WhenAsync("Người dùng cố tình thay đổi URL trình duyệt sang đường dẫn \"/TaiKhoan/DonHang/Chi" +
                        "Tiet/1\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 39
    await testRunner.ThenAsync("Hệ thống phải từ chối truy cập và trả về kết quả hoặc thông báo lỗi \"403\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("TC14 - Tài khoản mới chưa có lịch sử mua hàng")]
        [global::NUnit.Framework.CategoryAttribute("TC_TC_014")]
        [global::NUnit.Framework.CategoryAttribute("Severity_Medium")]
        [global::NUnit.Framework.CategoryAttribute("Priority_Low")]
        public async global::System.Threading.Tasks.Task TC14_TaiKhoảnMớiChưaCoLịchSửMuaHang()
        {
            string[] tagsOfScenario = new string[] {
                    "TC_TC_014",
                    "Severity_Medium",
                    "Priority_Low"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "6";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("TC14 - Tài khoản mới chưa có lịch sử mua hàng", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 42
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 43
    await testRunner.GivenAsync("Người dùng tiến hành đăng nhập vào hệ thống với tài khoản \"test1\" và mật khẩu \"12" +
                        "3456\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 44
    await testRunner.WhenAsync("Người dùng nhấp vào menu tài khoản và chọn \"Đơn hàng của tôi\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 45
    await testRunner.ThenAsync("Hệ thống phải hiển thị thông báo trống \"Bạn chưa có đơn hàng nào\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
    }
}
#pragma warning restore
#endregion
