// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace KDPM_ReqnrollSeleniumAutomationTesting_Nhom5.Features
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::NUnit.Framework.TestFixtureAttribute()]
    [global::NUnit.Framework.DescriptionAttribute("Nhập lô thuốc")]
    [global::NUnit.Framework.FixtureLifeCycleAttribute(global::NUnit.Framework.LifeCycle.InstancePerTestCase)]
    public partial class NhậpLoThuốcFeature
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "Features", "Nhập lô thuốc", "Kiểm thử chức năng Nhập lô thuốc của hệ thống MedForAll.\r\nCác scenario trong file" +
                " này được đồng bộ theo test case Selenium đã chạy.", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
#line 1 "NhapHang.feature"
#line hidden
        
        [global::NUnit.Framework.OneTimeSetUpAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        [global::NUnit.Framework.OneTimeTearDownAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        [global::NUnit.Framework.SetUpAttribute()]
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        [global::NUnit.Framework.TearDownAttribute()]
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<global::NUnit.Framework.TestContext>(global::NUnit.Framework.TestContext.CurrentContext);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/NhapHang.feature.ndjson", 34);
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("TC_ADMIN_NHAPLO_001 - Mở trang Danh sách thuốc")]
        [global::NUnit.Framework.CategoryAttribute("NhapLo")]
        [global::NUnit.Framework.CategoryAttribute("TC_ADMIN_NHAPLO_001")]
        [global::NUnit.Framework.CategoryAttribute("Severity_LOW")]
        [global::NUnit.Framework.CategoryAttribute("Priority_LOW")]
        public async global::System.Threading.Tasks.Task TC_ADMIN_NHAPLO_001_MởTrangDanhSachThuốc()
        {
            string[] tagsOfScenario = new string[] {
                    "NhapLo",
                    "TC_ADMIN_NHAPLO_001",
                    "Severity_LOW",
                    "Priority_LOW"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "0";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("TC_ADMIN_NHAPLO_001 - Mở trang Danh sách thuốc", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 7
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 8
await testRunner.WhenAsync("Admin truy cập trang Danh sách thuốc", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 9
await testRunner.ThenAsync("trang Danh sách thuốc mở được, có nút Thêm thuốc mới, có nút Nhập và không hiển t" +
                        "hị lỗi hệ thống", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("TC_ADMIN_NHAPLO_002 - Kiểm tra sidebar active")]
        [global::NUnit.Framework.CategoryAttribute("NhapLo")]
        [global::NUnit.Framework.CategoryAttribute("TC_ADMIN_NHAPLO_002")]
        [global::NUnit.Framework.CategoryAttribute("Severity_LOW")]
        [global::NUnit.Framework.CategoryAttribute("Priority_LOW")]
        public async global::System.Threading.Tasks.Task TC_ADMIN_NHAPLO_002_KiểmTraSidebarActive()
        {
            string[] tagsOfScenario = new string[] {
                    "NhapLo",
                    "TC_ADMIN_NHAPLO_002",
                    "Severity_LOW",
                    "Priority_LOW"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "1";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("TC_ADMIN_NHAPLO_002 - Kiểm tra sidebar active", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 12
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 13
await testRunner.WhenAsync("Admin truy cập trang Danh sách thuốc", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 14
await testRunner.ThenAsync("menu Danh sách thuốc trên sidebar được active đúng", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("TC_ADMIN_NHAPLO_003 - Kiểm tra tiêu đề cột bảng thuốc")]
        [global::NUnit.Framework.CategoryAttribute("NhapLo")]
        [global::NUnit.Framework.CategoryAttribute("TC_ADMIN_NHAPLO_003")]
        [global::NUnit.Framework.CategoryAttribute("Severity_LOW")]
        [global::NUnit.Framework.CategoryAttribute("Priority_LOW")]
        public async global::System.Threading.Tasks.Task TC_ADMIN_NHAPLO_003_KiểmTraTieuDềCộtBảngThuốc()
        {
            string[] tagsOfScenario = new string[] {
                    "NhapLo",
                    "TC_ADMIN_NHAPLO_003",
                    "Severity_LOW",
                    "Priority_LOW"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "2";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("TC_ADMIN_NHAPLO_003 - Kiểm tra tiêu đề cột bảng thuốc", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 17
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 18
await testRunner.WhenAsync("Admin truy cập trang Danh sách thuốc", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 19
await testRunner.ThenAsync("bảng Danh sách thuốc hiển thị đủ các cột Ảnh, Tên thuốc, Danh mục, Tồn kho, Giá b" +
                        "án, Trạng thái và Hành động", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("TC_ADMIN_NHAPLO_004 - Kiểm tra bảng thuốc có dữ liệu")]
        [global::NUnit.Framework.CategoryAttribute("NhapLo")]
        [global::NUnit.Framework.CategoryAttribute("TC_ADMIN_NHAPLO_004")]
        [global::NUnit.Framework.CategoryAttribute("Severity_MEDIUM")]
        [global::NUnit.Framework.CategoryAttribute("Priority_MEDIUM")]
        public async global::System.Threading.Tasks.Task TC_ADMIN_NHAPLO_004_KiểmTraBảngThuốcCoDữLiệu()
        {
            string[] tagsOfScenario = new string[] {
                    "NhapLo",
                    "TC_ADMIN_NHAPLO_004",
                    "Severity_MEDIUM",
                    "Priority_MEDIUM"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "3";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("TC_ADMIN_NHAPLO_004 - Kiểm tra bảng thuốc có dữ liệu", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 22
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 23
await testRunner.WhenAsync("Admin truy cập trang Danh sách thuốc", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 24
await testRunner.ThenAsync("danh sách thuốc hiển thị dữ liệu hợp lệ và mỗi dòng thuốc có nút Nhập", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("TC_ADMIN_NHAPLO_005 - Tìm thuốc trước khi nhập lô")]
        [global::NUnit.Framework.CategoryAttribute("NhapLo")]
        [global::NUnit.Framework.CategoryAttribute("TC_ADMIN_NHAPLO_005")]
        [global::NUnit.Framework.CategoryAttribute("Severity_LOW")]
        [global::NUnit.Framework.CategoryAttribute("Priority_LOW")]
        public async global::System.Threading.Tasks.Task TC_ADMIN_NHAPLO_005_TimThuốcTrướcKhiNhậpLo()
        {
            string[] tagsOfScenario = new string[] {
                    "NhapLo",
                    "TC_ADMIN_NHAPLO_005",
                    "Severity_LOW",
                    "Priority_LOW"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "4";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("TC_ADMIN_NHAPLO_005 - Tìm thuốc trước khi nhập lô", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 27
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 28
await testRunner.WhenAsync("Admin tìm kiếm thuốc Amoxicillin trước khi nhập lô", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 29
await testRunner.ThenAsync("kết quả tìm kiếm chỉ hiển thị thuốc phù hợp với từ khóa Amoxicillin", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("TC_ADMIN_NHAPLO_006 - Lọc danh mục trước khi nhập lô")]
        [global::NUnit.Framework.CategoryAttribute("NhapLo")]
        [global::NUnit.Framework.CategoryAttribute("TC_ADMIN_NHAPLO_006")]
        [global::NUnit.Framework.CategoryAttribute("Severity_LOW")]
        [global::NUnit.Framework.CategoryAttribute("Priority_LOW")]
        public async global::System.Threading.Tasks.Task TC_ADMIN_NHAPLO_006_LọcDanhMụcTrướcKhiNhậpLo()
        {
            string[] tagsOfScenario = new string[] {
                    "NhapLo",
                    "TC_ADMIN_NHAPLO_006",
                    "Severity_LOW",
                    "Priority_LOW"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "5";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("TC_ADMIN_NHAPLO_006 - Lọc danh mục trước khi nhập lô", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 32
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 33
await testRunner.WhenAsync("Admin lọc danh sách thuốc theo danh mục Kháng sinh", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 34
await testRunner.ThenAsync("danh sách chỉ hiển thị các thuốc thuộc danh mục Kháng sinh", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("TC_ADMIN_NHAPLO_007 - Kiểm tra link nút Nhập")]
        [global::NUnit.Framework.CategoryAttribute("NhapLo")]
        [global::NUnit.Framework.CategoryAttribute("TC_ADMIN_NHAPLO_007")]
        [global::NUnit.Framework.CategoryAttribute("Severity_MEDIUM")]
        [global::NUnit.Framework.CategoryAttribute("Priority_MEDIUM")]
        public async global::System.Threading.Tasks.Task TC_ADMIN_NHAPLO_007_KiểmTraLinkNutNhập()
        {
            string[] tagsOfScenario = new string[] {
                    "NhapLo",
                    "TC_ADMIN_NHAPLO_007",
                    "Severity_MEDIUM",
                    "Priority_MEDIUM"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "6";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("TC_ADMIN_NHAPLO_007 - Kiểm tra link nút Nhập", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 37
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 38
await testRunner.WhenAsync("Admin kiểm tra nút Nhập của thuốc Amoxicillin", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 39
await testRunner.ThenAsync("nút Nhập trỏ đúng đến trang nhập hàng của thuốc Amoxicillin", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("TC_ADMIN_NHAPLO_008 - Bấm nút Nhập mở form nhập kho")]
        [global::NUnit.Framework.CategoryAttribute("NhapLo")]
        [global::NUnit.Framework.CategoryAttribute("TC_ADMIN_NHAPLO_008")]
        [global::NUnit.Framework.CategoryAttribute("Severity_MEDIUM")]
        [global::NUnit.Framework.CategoryAttribute("Priority_MEDIUM")]
        public async global::System.Threading.Tasks.Task TC_ADMIN_NHAPLO_008_BấmNutNhậpMởFormNhậpKho()
        {
            string[] tagsOfScenario = new string[] {
                    "NhapLo",
                    "TC_ADMIN_NHAPLO_008",
                    "Severity_MEDIUM",
                    "Priority_MEDIUM"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "7";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("TC_ADMIN_NHAPLO_008 - Bấm nút Nhập mở form nhập kho", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 42
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 43
await testRunner.WhenAsync("Admin bấm nút Nhập của thuốc Amoxicillin", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 44
await testRunner.ThenAsync("hệ thống chuyển sang màn hình Nhập lô hàng mới của thuốc Amoxicillin", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("TC_ADMIN_NHAPLO_009 - Kiểm tra thông tin thuốc trên trang nhập kho")]
        [global::NUnit.Framework.CategoryAttribute("NhapLo")]
        [global::NUnit.Framework.CategoryAttribute("TC_ADMIN_NHAPLO_009")]
        [global::NUnit.Framework.CategoryAttribute("Severity_MEDIUM")]
        [global::NUnit.Framework.CategoryAttribute("Priority_MEDIUM")]
        public async global::System.Threading.Tasks.Task TC_ADMIN_NHAPLO_009_KiểmTraThongTinThuốcTrenTrangNhậpKho()
        {
            string[] tagsOfScenario = new string[] {
                    "NhapLo",
                    "TC_ADMIN_NHAPLO_009",
                    "Severity_MEDIUM",
                    "Priority_MEDIUM"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "8";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("TC_ADMIN_NHAPLO_009 - Kiểm tra thông tin thuốc trên trang nhập kho", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 47
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 48
await testRunner.WhenAsync("Admin mở trang Nhập lô hàng mới của thuốc Amoxicillin", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 49
await testRunner.ThenAsync("trang nhập kho hiển thị đúng tên thuốc, đơn vị tính, tồn kho hiện tại và giá bán " +
                        "hiện tại", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("TC_ADMIN_NHAPLO_010 - Kiểm tra hidden field thuốc")]
        [global::NUnit.Framework.CategoryAttribute("NhapLo")]
        [global::NUnit.Framework.CategoryAttribute("TC_ADMIN_NHAPLO_010")]
        [global::NUnit.Framework.CategoryAttribute("Severity_MEDIUM")]
        [global::NUnit.Framework.CategoryAttribute("Priority_MEDIUM")]
        public async global::System.Threading.Tasks.Task TC_ADMIN_NHAPLO_010_KiểmTraHiddenFieldThuốc()
        {
            string[] tagsOfScenario = new string[] {
                    "NhapLo",
                    "TC_ADMIN_NHAPLO_010",
                    "Severity_MEDIUM",
                    "Priority_MEDIUM"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "9";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("TC_ADMIN_NHAPLO_010 - Kiểm tra hidden field thuốc", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 52
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 53
await testRunner.WhenAsync("Admin mở trang Nhập lô hàng mới của thuốc Amoxicillin", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 54
await testRunner.ThenAsync("các hidden field của thuốc chứa đúng IdThuoc, TenThuoc, DonViTinh, GiaBanHienTai " +
                        "và TongTonKho", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("TC_ADMIN_NHAPLO_011 - Kiểm tra form có đủ field nhập lô")]
        [global::NUnit.Framework.CategoryAttribute("NhapLo")]
        [global::NUnit.Framework.CategoryAttribute("TC_ADMIN_NHAPLO_011")]
        [global::NUnit.Framework.CategoryAttribute("Severity_MEDIUM")]
        [global::NUnit.Framework.CategoryAttribute("Priority_MEDIUM")]
        public async global::System.Threading.Tasks.Task TC_ADMIN_NHAPLO_011_KiểmTraFormCoDủFieldNhậpLo()
        {
            string[] tagsOfScenario = new string[] {
                    "NhapLo",
                    "TC_ADMIN_NHAPLO_011",
                    "Severity_MEDIUM",
                    "Priority_MEDIUM"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "10";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("TC_ADMIN_NHAPLO_011 - Kiểm tra form có đủ field nhập lô", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 57
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 58
await testRunner.WhenAsync("Admin mở trang Nhập lô hàng mới của thuốc Amoxicillin", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 59
await testRunner.ThenAsync("form nhập lô hiển thị đủ các field Số lô, Ngày sản xuất, Hạn sử dụng, Số lượng nh" +
                        "ập, Giá nhập và Thành tiền", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("TC_ADMIN_NHAPLO_012 - Kiểm tra name của các field")]
        [global::NUnit.Framework.CategoryAttribute("NhapLo")]
        [global::NUnit.Framework.CategoryAttribute("TC_ADMIN_NHAPLO_012")]
        [global::NUnit.Framework.CategoryAttribute("Severity_MEDIUM")]
        [global::NUnit.Framework.CategoryAttribute("Priority_MEDIUM")]
        public async global::System.Threading.Tasks.Task TC_ADMIN_NHAPLO_012_KiểmTraNameCủaCacField()
        {
            string[] tagsOfScenario = new string[] {
                    "NhapLo",
                    "TC_ADMIN_NHAPLO_012",
                    "Severity_MEDIUM",
                    "Priority_MEDIUM"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "11";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("TC_ADMIN_NHAPLO_012 - Kiểm tra name của các field", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 62
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 63
await testRunner.WhenAsync("Admin mở trang Nhập lô hàng mới của thuốc Amoxicillin", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 64
await testRunner.ThenAsync("các field nhập lô có thuộc tính name đúng để gửi POST", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("TC_ADMIN_NHAPLO_013 - Kiểm tra bắt buộc nhập Số lô")]
        [global::NUnit.Framework.CategoryAttribute("NhapLo")]
        [global::NUnit.Framework.CategoryAttribute("TC_ADMIN_NHAPLO_013")]
        [global::NUnit.Framework.CategoryAttribute("Severity_MEDIUM")]
        [global::NUnit.Framework.CategoryAttribute("Priority_MEDIUM")]
        public async global::System.Threading.Tasks.Task TC_ADMIN_NHAPLO_013_KiểmTraBắtBuộcNhậpSốLo()
        {
            string[] tagsOfScenario = new string[] {
                    "NhapLo",
                    "TC_ADMIN_NHAPLO_013",
                    "Severity_MEDIUM",
                    "Priority_MEDIUM"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "12";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("TC_ADMIN_NHAPLO_013 - Kiểm tra bắt buộc nhập Số lô", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 67
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 68
await testRunner.WhenAsync("Admin kiểm tra ràng buộc bắt buộc của field Số lô", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 69
await testRunner.ThenAsync("field Số lô có cấu hình validate bắt buộc và thông báo lỗi phù hợp", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("TC_ADMIN_NHAPLO_014 - Kiểm tra min Số lượng nhập")]
        [global::NUnit.Framework.CategoryAttribute("NhapLo")]
        [global::NUnit.Framework.CategoryAttribute("TC_ADMIN_NHAPLO_014")]
        [global::NUnit.Framework.CategoryAttribute("Severity_MEDIUM")]
        [global::NUnit.Framework.CategoryAttribute("Priority_MEDIUM")]
        public async global::System.Threading.Tasks.Task TC_ADMIN_NHAPLO_014_KiểmTraMinSốLượngNhập()
        {
            string[] tagsOfScenario = new string[] {
                    "NhapLo",
                    "TC_ADMIN_NHAPLO_014",
                    "Severity_MEDIUM",
                    "Priority_MEDIUM"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "13";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("TC_ADMIN_NHAPLO_014 - Kiểm tra min Số lượng nhập", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 72
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 73
await testRunner.WhenAsync("Admin kiểm tra ràng buộc min của field Số lượng nhập", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 74
await testRunner.ThenAsync("field Số lượng nhập phải có min bằng 1", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("TC_ADMIN_NHAPLO_015 - Kiểm tra min Giá nhập")]
        [global::NUnit.Framework.CategoryAttribute("NhapLo")]
        [global::NUnit.Framework.CategoryAttribute("TC_ADMIN_NHAPLO_015")]
        [global::NUnit.Framework.CategoryAttribute("Severity_MEDIUM")]
        [global::NUnit.Framework.CategoryAttribute("Priority_MEDIUM")]
        public async global::System.Threading.Tasks.Task TC_ADMIN_NHAPLO_015_KiểmTraMinGiaNhập()
        {
            string[] tagsOfScenario = new string[] {
                    "NhapLo",
                    "TC_ADMIN_NHAPLO_015",
                    "Severity_MEDIUM",
                    "Priority_MEDIUM"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "14";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("TC_ADMIN_NHAPLO_015 - Kiểm tra min Giá nhập", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 77
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 78
await testRunner.WhenAsync("Admin kiểm tra ràng buộc min của field Giá nhập", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 79
await testRunner.ThenAsync("field Giá nhập phải có min bằng 1 vì giá nhập phải lớn hơn 0", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("TC_ADMIN_NHAPLO_016 - Kiểm tra giá trị mặc định Số lượng")]
        [global::NUnit.Framework.CategoryAttribute("NhapLo")]
        [global::NUnit.Framework.CategoryAttribute("TC_ADMIN_NHAPLO_016")]
        [global::NUnit.Framework.CategoryAttribute("Severity_MEDIUM")]
        [global::NUnit.Framework.CategoryAttribute("Priority_MEDIUM")]
        public async global::System.Threading.Tasks.Task TC_ADMIN_NHAPLO_016_KiểmTraGiaTrịMặcDịnhSốLượng()
        {
            string[] tagsOfScenario = new string[] {
                    "NhapLo",
                    "TC_ADMIN_NHAPLO_016",
                    "Severity_MEDIUM",
                    "Priority_MEDIUM"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "15";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("TC_ADMIN_NHAPLO_016 - Kiểm tra giá trị mặc định Số lượng", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 82
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 83
await testRunner.WhenAsync("Admin kiểm tra giá trị mặc định của field Số lượng nhập", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 84
await testRunner.ThenAsync("giá trị mặc định của Số lượng nhập không được nhỏ hơn min", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("TC_ADMIN_NHAPLO_017 - Kiểm tra giá trị mặc định Giá nhập")]
        [global::NUnit.Framework.CategoryAttribute("NhapLo")]
        [global::NUnit.Framework.CategoryAttribute("TC_ADMIN_NHAPLO_017")]
        [global::NUnit.Framework.CategoryAttribute("Severity_MEDIUM")]
        [global::NUnit.Framework.CategoryAttribute("Priority_MEDIUM")]
        public async global::System.Threading.Tasks.Task TC_ADMIN_NHAPLO_017_KiểmTraGiaTrịMặcDịnhGiaNhập()
        {
            string[] tagsOfScenario = new string[] {
                    "NhapLo",
                    "TC_ADMIN_NHAPLO_017",
                    "Severity_MEDIUM",
                    "Priority_MEDIUM"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "16";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("TC_ADMIN_NHAPLO_017 - Kiểm tra giá trị mặc định Giá nhập", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 87
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 88
await testRunner.WhenAsync("Admin kiểm tra giá trị mặc định của field Giá nhập", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 89
await testRunner.ThenAsync("giá trị mặc định của Giá nhập không được nhỏ hơn min", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("TC_ADMIN_NHAPLO_018 - Tự động tính tổng giá trị lô hàng")]
        [global::NUnit.Framework.CategoryAttribute("NhapLo")]
        [global::NUnit.Framework.CategoryAttribute("TC_ADMIN_NHAPLO_018")]
        [global::NUnit.Framework.CategoryAttribute("Severity_HIGH")]
        [global::NUnit.Framework.CategoryAttribute("Priority_HIGH")]
        public async global::System.Threading.Tasks.Task TC_ADMIN_NHAPLO_018_TựDộngTinhTổngGiaTrịLoHang()
        {
            string[] tagsOfScenario = new string[] {
                    "NhapLo",
                    "TC_ADMIN_NHAPLO_018",
                    "Severity_HIGH",
                    "Priority_HIGH"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "17";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("TC_ADMIN_NHAPLO_018 - Tự động tính tổng giá trị lô hàng", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 92
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 93
await testRunner.WhenAsync("Admin nhập số lượng 5 và giá nhập 22000", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 94
await testRunner.ThenAsync("hệ thống tự động tính đúng tổng giá trị lô hàng", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("TC_ADMIN_NHAPLO_019 - Tính tổng giá trị lô hàng với số lớn")]
        [global::NUnit.Framework.CategoryAttribute("NhapLo")]
        [global::NUnit.Framework.CategoryAttribute("TC_ADMIN_NHAPLO_019")]
        [global::NUnit.Framework.CategoryAttribute("Severity_HIGH")]
        [global::NUnit.Framework.CategoryAttribute("Priority_HIGH")]
        public async global::System.Threading.Tasks.Task TC_ADMIN_NHAPLO_019_TinhTổngGiaTrịLoHangVớiSốLớn()
        {
            string[] tagsOfScenario = new string[] {
                    "NhapLo",
                    "TC_ADMIN_NHAPLO_019",
                    "Severity_HIGH",
                    "Priority_HIGH"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "18";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("TC_ADMIN_NHAPLO_019 - Tính tổng giá trị lô hàng với số lớn", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 97
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 98
await testRunner.WhenAsync("Admin nhập số lượng lớn và giá nhập lớn trên form nhập lô", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 99
await testRunner.ThenAsync("hệ thống vẫn tính đúng tổng giá trị lô hàng", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("TC_ADMIN_NHAPLO_020 - Cảnh báo giá nhập cao hơn giá bán")]
        [global::NUnit.Framework.CategoryAttribute("NhapLo")]
        [global::NUnit.Framework.CategoryAttribute("TC_ADMIN_NHAPLO_020")]
        [global::NUnit.Framework.CategoryAttribute("Severity_MEDIUM")]
        [global::NUnit.Framework.CategoryAttribute("Priority_MEDIUM")]
        public async global::System.Threading.Tasks.Task TC_ADMIN_NHAPLO_020_CảnhBaoGiaNhậpCaoHơnGiaBan()
        {
            string[] tagsOfScenario = new string[] {
                    "NhapLo",
                    "TC_ADMIN_NHAPLO_020",
                    "Severity_MEDIUM",
                    "Priority_MEDIUM"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "19";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("TC_ADMIN_NHAPLO_020 - Cảnh báo giá nhập cao hơn giá bán", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 102
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 103
await testRunner.WhenAsync("Admin nhập giá nhập cao hơn giá bán hiện tại", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 104
await testRunner.ThenAsync("hệ thống hiển thị cảnh báo giá nhập cao hơn giá bán", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("TC_ADMIN_NHAPLO_021 - Ẩn cảnh báo khi giá nhập hợp lệ lại")]
        [global::NUnit.Framework.CategoryAttribute("NhapLo")]
        [global::NUnit.Framework.CategoryAttribute("TC_ADMIN_NHAPLO_021")]
        [global::NUnit.Framework.CategoryAttribute("Severity_MEDIUM")]
        [global::NUnit.Framework.CategoryAttribute("Priority_MEDIUM")]
        public async global::System.Threading.Tasks.Task TC_ADMIN_NHAPLO_021_ẨnCảnhBaoKhiGiaNhậpHợpLệLại()
        {
            string[] tagsOfScenario = new string[] {
                    "NhapLo",
                    "TC_ADMIN_NHAPLO_021",
                    "Severity_MEDIUM",
                    "Priority_MEDIUM"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "20";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("TC_ADMIN_NHAPLO_021 - Ẩn cảnh báo khi giá nhập hợp lệ lại", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 107
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 108
await testRunner.WhenAsync("Admin nhập giá nhập cao hơn giá bán rồi sửa lại thành giá hợp lệ", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 109
await testRunner.ThenAsync("cảnh báo giá nhập cao hơn giá bán phải biến mất", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("TC_ADMIN_NHAPLO_022 - Kiểm tra input ngày là type date")]
        [global::NUnit.Framework.CategoryAttribute("NhapLo")]
        [global::NUnit.Framework.CategoryAttribute("TC_ADMIN_NHAPLO_022")]
        [global::NUnit.Framework.CategoryAttribute("Severity_LOW")]
        [global::NUnit.Framework.CategoryAttribute("Priority_LOW")]
        public async global::System.Threading.Tasks.Task TC_ADMIN_NHAPLO_022_KiểmTraInputNgayLaTypeDate()
        {
            string[] tagsOfScenario = new string[] {
                    "NhapLo",
                    "TC_ADMIN_NHAPLO_022",
                    "Severity_LOW",
                    "Priority_LOW"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "21";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("TC_ADMIN_NHAPLO_022 - Kiểm tra input ngày là type date", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 112
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 113
await testRunner.WhenAsync("Admin mở trang Nhập lô hàng mới của thuốc Amoxicillin", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 114
await testRunner.ThenAsync("field Ngày sản xuất và Hạn sử dụng phải là input type date", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("TC_ADMIN_NHAPLO_023 - Kiểm tra format value input date")]
        [global::NUnit.Framework.CategoryAttribute("NhapLo")]
        [global::NUnit.Framework.CategoryAttribute("TC_ADMIN_NHAPLO_023")]
        [global::NUnit.Framework.CategoryAttribute("Severity_LOW")]
        [global::NUnit.Framework.CategoryAttribute("Priority_LOW")]
        public async global::System.Threading.Tasks.Task TC_ADMIN_NHAPLO_023_KiểmTraFormatValueInputDate()
        {
            string[] tagsOfScenario = new string[] {
                    "NhapLo",
                    "TC_ADMIN_NHAPLO_023",
                    "Severity_LOW",
                    "Priority_LOW"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "22";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("TC_ADMIN_NHAPLO_023 - Kiểm tra format value input date", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 117
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 118
await testRunner.WhenAsync("Admin mở trang Nhập lô hàng mới của thuốc Amoxicillin", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 119
await testRunner.ThenAsync("giá trị của input date phải có format yyyy-MM-dd hoặc để rỗng", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("TC_ADMIN_NHAPLO_024 - Kiểm tra nút Hủy bỏ")]
        [global::NUnit.Framework.CategoryAttribute("NhapLo")]
        [global::NUnit.Framework.CategoryAttribute("TC_ADMIN_NHAPLO_024")]
        [global::NUnit.Framework.CategoryAttribute("Severity_LOW")]
        [global::NUnit.Framework.CategoryAttribute("Priority_LOW")]
        public async global::System.Threading.Tasks.Task TC_ADMIN_NHAPLO_024_KiểmTraNutHủyBỏ()
        {
            string[] tagsOfScenario = new string[] {
                    "NhapLo",
                    "TC_ADMIN_NHAPLO_024",
                    "Severity_LOW",
                    "Priority_LOW"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "23";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("TC_ADMIN_NHAPLO_024 - Kiểm tra nút Hủy bỏ", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 122
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 123
await testRunner.WhenAsync("Admin mở trang Nhập lô hàng mới của thuốc Amoxicillin", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 124
await testRunner.ThenAsync("nút Hủy bỏ trỏ đúng về trang Danh sách thuốc", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("TC_ADMIN_NHAPLO_025 - Bấm Hủy bỏ quay về Danh sách thuốc")]
        [global::NUnit.Framework.CategoryAttribute("NhapLo")]
        [global::NUnit.Framework.CategoryAttribute("TC_ADMIN_NHAPLO_025")]
        [global::NUnit.Framework.CategoryAttribute("Severity_LOW")]
        [global::NUnit.Framework.CategoryAttribute("Priority_LOW")]
        public async global::System.Threading.Tasks.Task TC_ADMIN_NHAPLO_025_BấmHủyBỏQuayVềDanhSachThuốc()
        {
            string[] tagsOfScenario = new string[] {
                    "NhapLo",
                    "TC_ADMIN_NHAPLO_025",
                    "Severity_LOW",
                    "Priority_LOW"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "24";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("TC_ADMIN_NHAPLO_025 - Bấm Hủy bỏ quay về Danh sách thuốc", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 127
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 128
await testRunner.WhenAsync("Admin bấm nút Hủy bỏ trên trang nhập lô", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 129
await testRunner.ThenAsync("hệ thống quay về trang Danh sách thuốc và không lưu dữ liệu nhập lô", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("TC_ADMIN_NHAPLO_026 - Kiểm tra form action và method")]
        [global::NUnit.Framework.CategoryAttribute("NhapLo")]
        [global::NUnit.Framework.CategoryAttribute("TC_ADMIN_NHAPLO_026")]
        [global::NUnit.Framework.CategoryAttribute("Severity_MEDIUM")]
        [global::NUnit.Framework.CategoryAttribute("Priority_MEDIUM")]
        public async global::System.Threading.Tasks.Task TC_ADMIN_NHAPLO_026_KiểmTraFormActionVaMethod()
        {
            string[] tagsOfScenario = new string[] {
                    "NhapLo",
                    "TC_ADMIN_NHAPLO_026",
                    "Severity_MEDIUM",
                    "Priority_MEDIUM"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "25";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("TC_ADMIN_NHAPLO_026 - Kiểm tra form action và method", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 132
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 133
await testRunner.WhenAsync("Admin mở trang Nhập lô hàng mới của thuốc Amoxicillin", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 134
await testRunner.ThenAsync("form nhập kho gửi POST đúng action của thuốc Amoxicillin", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("TC_ADMIN_NHAPLO_027 - Kiểm tra Anti-forgery token")]
        [global::NUnit.Framework.CategoryAttribute("NhapLo")]
        [global::NUnit.Framework.CategoryAttribute("TC_ADMIN_NHAPLO_027")]
        [global::NUnit.Framework.CategoryAttribute("Severity_MEDIUM")]
        [global::NUnit.Framework.CategoryAttribute("Priority_MEDIUM")]
        public async global::System.Threading.Tasks.Task TC_ADMIN_NHAPLO_027_KiểmTraAnti_ForgeryToken()
        {
            string[] tagsOfScenario = new string[] {
                    "NhapLo",
                    "TC_ADMIN_NHAPLO_027",
                    "Severity_MEDIUM",
                    "Priority_MEDIUM"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "26";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("TC_ADMIN_NHAPLO_027 - Kiểm tra Anti-forgery token", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 137
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 138
await testRunner.WhenAsync("Admin mở trang Nhập lô hàng mới của thuốc Amoxicillin", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 139
await testRunner.ThenAsync("form nhập kho có Anti-forgery token hợp lệ", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("TC_ADMIN_NHAPLO_028 - Mở nhập kho với ID thuốc không tồn tại")]
        [global::NUnit.Framework.CategoryAttribute("NhapLo")]
        [global::NUnit.Framework.CategoryAttribute("TC_ADMIN_NHAPLO_028")]
        [global::NUnit.Framework.CategoryAttribute("Severity_HIGH")]
        [global::NUnit.Framework.CategoryAttribute("Priority_HIGH")]
        public async global::System.Threading.Tasks.Task TC_ADMIN_NHAPLO_028_MởNhậpKhoVớiIDThuốcKhongTồnTại()
        {
            string[] tagsOfScenario = new string[] {
                    "NhapLo",
                    "TC_ADMIN_NHAPLO_028",
                    "Severity_HIGH",
                    "Priority_HIGH"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "27";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("TC_ADMIN_NHAPLO_028 - Mở nhập kho với ID thuốc không tồn tại", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 142
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 143
await testRunner.WhenAsync("Admin mở trang Nhập lô hàng mới với ID thuốc không tồn tại", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 144
await testRunner.ThenAsync("hệ thống không được phát sinh lỗi hệ thống", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("TC_ADMIN_NHAPLO_029 - Kiểm tra ảnh ở trang nhập kho")]
        [global::NUnit.Framework.CategoryAttribute("NhapLo")]
        [global::NUnit.Framework.CategoryAttribute("TC_ADMIN_NHAPLO_029")]
        [global::NUnit.Framework.CategoryAttribute("Severity_LOW")]
        [global::NUnit.Framework.CategoryAttribute("Priority_LOW")]
        public async global::System.Threading.Tasks.Task TC_ADMIN_NHAPLO_029_KiểmTraẢnhỞTrangNhậpKho()
        {
            string[] tagsOfScenario = new string[] {
                    "NhapLo",
                    "TC_ADMIN_NHAPLO_029",
                    "Severity_LOW",
                    "Priority_LOW"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "28";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("TC_ADMIN_NHAPLO_029 - Kiểm tra ảnh ở trang nhập kho", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 147
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 148
await testRunner.WhenAsync("Admin mở trang Nhập lô hàng mới của thuốc Amoxicillin", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 149
await testRunner.ThenAsync("ảnh thuốc ở trang nhập kho tải được và không bị vỡ", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("TC_ADMIN_NHAPLO_030 - Kiểm tra không hiển thị số âm")]
        [global::NUnit.Framework.CategoryAttribute("NhapLo")]
        [global::NUnit.Framework.CategoryAttribute("TC_ADMIN_NHAPLO_030")]
        [global::NUnit.Framework.CategoryAttribute("Severity_MEDIUM")]
        [global::NUnit.Framework.CategoryAttribute("Priority_MEDIUM")]
        public async global::System.Threading.Tasks.Task TC_ADMIN_NHAPLO_030_KiểmTraKhongHiểnThịSốAm()
        {
            string[] tagsOfScenario = new string[] {
                    "NhapLo",
                    "TC_ADMIN_NHAPLO_030",
                    "Severity_MEDIUM",
                    "Priority_MEDIUM"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "29";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("TC_ADMIN_NHAPLO_030 - Kiểm tra không hiển thị số âm", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 152
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 153
await testRunner.WhenAsync("Admin nhập dữ liệu hợp lệ trên trang nhập lô", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 154
await testRunner.ThenAsync("trang nhập kho không hiển thị số âm bất thường", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("TC_ADMIN_NHAPLO_031 - Responsive trang nhập kho")]
        [global::NUnit.Framework.CategoryAttribute("NhapLo")]
        [global::NUnit.Framework.CategoryAttribute("TC_ADMIN_NHAPLO_031")]
        [global::NUnit.Framework.CategoryAttribute("Severity_LOW")]
        [global::NUnit.Framework.CategoryAttribute("Priority_LOW")]
        public async global::System.Threading.Tasks.Task TC_ADMIN_NHAPLO_031_ResponsiveTrangNhậpKho()
        {
            string[] tagsOfScenario = new string[] {
                    "NhapLo",
                    "TC_ADMIN_NHAPLO_031",
                    "Severity_LOW",
                    "Priority_LOW"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "30";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("TC_ADMIN_NHAPLO_031 - Responsive trang nhập kho", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 157
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 158
await testRunner.WhenAsync("Admin mở trang Nhập lô hàng mới trên màn hình mobile", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 159
await testRunner.ThenAsync("trang nhập kho không bị tràn ngang nghiêm trọng", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("TC_ADMIN_NHAPLO_032 - Nhập kho thật với dữ liệu hợp lệ")]
        [global::NUnit.Framework.CategoryAttribute("NhapLo")]
        [global::NUnit.Framework.CategoryAttribute("TC_ADMIN_NHAPLO_032")]
        [global::NUnit.Framework.CategoryAttribute("Severity_HIGH")]
        [global::NUnit.Framework.CategoryAttribute("Priority_MEDIUM")]
        [global::NUnit.Framework.CategoryAttribute("Skip")]
        public async global::System.Threading.Tasks.Task TC_ADMIN_NHAPLO_032_NhậpKhoThậtVớiDữLiệuHợpLệ()
        {
            string[] tagsOfScenario = new string[] {
                    "NhapLo",
                    "TC_ADMIN_NHAPLO_032",
                    "Severity_HIGH",
                    "Priority_MEDIUM",
                    "Skip"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "31";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("TC_ADMIN_NHAPLO_032 - Nhập kho thật với dữ liệu hợp lệ", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 162
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 163
await testRunner.WhenAsync("Admin submit nhập kho thật với dữ liệu hợp lệ", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 164
await testRunner.ThenAsync("hệ thống tạo lô thuốc mới và lô xuất hiện trong danh sách lô thuốc", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
    }
}
#pragma warning restore
#endregion
