// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace KDPM_ReqnrollSeleniumAutomationTesting_Nhom5.Features
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::NUnit.Framework.TestFixtureAttribute()]
    [global::NUnit.Framework.DescriptionAttribute("Quản lý thuốc bán online")]
    [global::NUnit.Framework.FixtureLifeCycleAttribute(global::NUnit.Framework.LifeCycle.InstancePerTestCase)]
    public partial class QuảnLyThuốcBanOnlineFeature
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "Features", "Quản lý thuốc bán online", "Kiểm thử chức năng Quản lý thuốc bán online của hệ thống MedForAll.\r\nCác scenario" +
                " trong file này được đồng bộ theo test case Selenium Python đã chạy.", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
#line 1 "QuanLyThuocBanOnline.feature"
#line hidden
        
        [global::NUnit.Framework.OneTimeSetUpAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        [global::NUnit.Framework.OneTimeTearDownAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        [global::NUnit.Framework.SetUpAttribute()]
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        [global::NUnit.Framework.TearDownAttribute()]
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<global::NUnit.Framework.TestContext>(global::NUnit.Framework.TestContext.CurrentContext);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        public virtual async global::System.Threading.Tasks.Task FeatureBackgroundAsync()
        {
#line 5
#line hidden
#line 6
await testRunner.GivenAsync("Admin đã đăng nhập vào hệ thống MedForAll", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/QuanLyThuocBanOnline.feature.ndjson", 37);
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("TC_ONLINE_001 - Mở trang Quản lý thuốc bán online")]
        [global::NUnit.Framework.CategoryAttribute("Online")]
        [global::NUnit.Framework.CategoryAttribute("TC_ONLINE_001")]
        [global::NUnit.Framework.CategoryAttribute("Severity_LOW")]
        [global::NUnit.Framework.CategoryAttribute("Priority_LOW")]
        public async global::System.Threading.Tasks.Task TC_ONLINE_001_MởTrangQuảnLyThuốcBanOnline()
        {
            string[] tagsOfScenario = new string[] {
                    "Online",
                    "TC_ONLINE_001",
                    "Severity_LOW",
                    "Priority_LOW"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "0";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("TC_ONLINE_001 - Mở trang Quản lý thuốc bán online", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 9
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 5
await this.FeatureBackgroundAsync();
#line hidden
#line 10
await testRunner.WhenAsync("Admin truy cập trang Quản lý thuốc bán online", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 11
await testRunner.ThenAsync("trang Quản lý thuốc bán online mở được và không hiển thị lỗi hệ thống", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 12
await testRunner.AndAsync("trang hiển thị tiêu đề Quản lý thuốc bán online", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 13
await testRunner.AndAsync("trang hiển thị cột hoặc trạng thái Cho phép bán online", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("TC_ONLINE_002 - Kiểm tra sidebar active")]
        [global::NUnit.Framework.CategoryAttribute("Online")]
        [global::NUnit.Framework.CategoryAttribute("TC_ONLINE_002")]
        [global::NUnit.Framework.CategoryAttribute("Severity_LOW")]
        [global::NUnit.Framework.CategoryAttribute("Priority_LOW")]
        public async global::System.Threading.Tasks.Task TC_ONLINE_002_KiểmTraSidebarActive()
        {
            string[] tagsOfScenario = new string[] {
                    "Online",
                    "TC_ONLINE_002",
                    "Severity_LOW",
                    "Priority_LOW"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "1";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("TC_ONLINE_002 - Kiểm tra sidebar active", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 16
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 5
await this.FeatureBackgroundAsync();
#line hidden
#line 17
await testRunner.WhenAsync("Admin truy cập trang Quản lý thuốc bán online", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 18
await testRunner.ThenAsync("menu Quản lý thuốc bán online đang ở trạng thái active", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("TC_ONLINE_003 - Kiểm tra tiêu đề cột bảng")]
        [global::NUnit.Framework.CategoryAttribute("Online")]
        [global::NUnit.Framework.CategoryAttribute("TC_ONLINE_003")]
        [global::NUnit.Framework.CategoryAttribute("Severity_LOW")]
        [global::NUnit.Framework.CategoryAttribute("Priority_LOW")]
        public async global::System.Threading.Tasks.Task TC_ONLINE_003_KiểmTraTieuDềCộtBảng()
        {
            string[] tagsOfScenario = new string[] {
                    "Online",
                    "TC_ONLINE_003",
                    "Severity_LOW",
                    "Priority_LOW"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "2";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("TC_ONLINE_003 - Kiểm tra tiêu đề cột bảng", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 21
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 5
await this.FeatureBackgroundAsync();
#line hidden
#line 22
await testRunner.WhenAsync("Admin truy cập trang Quản lý thuốc bán online", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 23
await testRunner.ThenAsync("bảng thuốc online hiển thị đủ các cột cần thiết", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("TC_ONLINE_004 - Kiểm tra bảng có dữ liệu thuốc")]
        [global::NUnit.Framework.CategoryAttribute("Online")]
        [global::NUnit.Framework.CategoryAttribute("TC_ONLINE_004")]
        [global::NUnit.Framework.CategoryAttribute("Severity_MEDIUM")]
        [global::NUnit.Framework.CategoryAttribute("Priority_MEDIUM")]
        public async global::System.Threading.Tasks.Task TC_ONLINE_004_KiểmTraBảngCoDữLiệuThuốc()
        {
            string[] tagsOfScenario = new string[] {
                    "Online",
                    "TC_ONLINE_004",
                    "Severity_MEDIUM",
                    "Priority_MEDIUM"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "3";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("TC_ONLINE_004 - Kiểm tra bảng có dữ liệu thuốc", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 26
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 5
await this.FeatureBackgroundAsync();
#line hidden
#line 27
await testRunner.WhenAsync("Admin truy cập trang Quản lý thuốc bán online", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 28
await testRunner.ThenAsync("bảng thuốc online có dữ liệu thuốc hợp lệ", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("TC_ONLINE_005 - Tìm kiếm thuốc theo tên chính xác")]
        [global::NUnit.Framework.CategoryAttribute("Online")]
        [global::NUnit.Framework.CategoryAttribute("TC_ONLINE_005")]
        [global::NUnit.Framework.CategoryAttribute("Severity_MEDIUM")]
        [global::NUnit.Framework.CategoryAttribute("Priority_MEDIUM")]
        public async global::System.Threading.Tasks.Task TC_ONLINE_005_TimKiếmThuốcTheoTenChinhXac()
        {
            string[] tagsOfScenario = new string[] {
                    "Online",
                    "TC_ONLINE_005",
                    "Severity_MEDIUM",
                    "Priority_MEDIUM"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "4";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("TC_ONLINE_005 - Tìm kiếm thuốc theo tên chính xác", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 31
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 5
await this.FeatureBackgroundAsync();
#line hidden
#line 32
await testRunner.WhenAsync("Admin tìm kiếm thuốc online với từ khóa \"Amoxicillin\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 33
await testRunner.ThenAsync("kết quả tìm kiếm chỉ hiển thị thuốc phù hợp với từ khóa \"Amoxicillin\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("TC_ONLINE_006 - Tìm kiếm thuốc theo từ khóa ngắn")]
        [global::NUnit.Framework.CategoryAttribute("Online")]
        [global::NUnit.Framework.CategoryAttribute("TC_ONLINE_006")]
        [global::NUnit.Framework.CategoryAttribute("Severity_LOW")]
        [global::NUnit.Framework.CategoryAttribute("Priority_MEDIUM")]
        public async global::System.Threading.Tasks.Task TC_ONLINE_006_TimKiếmThuốcTheoTừKhoaNgắn()
        {
            string[] tagsOfScenario = new string[] {
                    "Online",
                    "TC_ONLINE_006",
                    "Severity_LOW",
                    "Priority_MEDIUM"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "5";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("TC_ONLINE_006 - Tìm kiếm thuốc theo từ khóa ngắn", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 36
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 5
await this.FeatureBackgroundAsync();
#line hidden
#line 37
await testRunner.WhenAsync("Admin tìm kiếm thuốc online với từ khóa \"amo\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 38
await testRunner.ThenAsync("kết quả tìm kiếm có thuốc Amoxicillin", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("TC_ONLINE_007 - Tìm kiếm không phân biệt hoa thường")]
        [global::NUnit.Framework.CategoryAttribute("Online")]
        [global::NUnit.Framework.CategoryAttribute("TC_ONLINE_007")]
        [global::NUnit.Framework.CategoryAttribute("Severity_LOW")]
        [global::NUnit.Framework.CategoryAttribute("Priority_MEDIUM")]
        public async global::System.Threading.Tasks.Task TC_ONLINE_007_TimKiếmKhongPhanBiệtHoaThường()
        {
            string[] tagsOfScenario = new string[] {
                    "Online",
                    "TC_ONLINE_007",
                    "Severity_LOW",
                    "Priority_MEDIUM"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "6";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("TC_ONLINE_007 - Tìm kiếm không phân biệt hoa thường", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 41
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 5
await this.FeatureBackgroundAsync();
#line hidden
#line 42
await testRunner.WhenAsync("Admin tìm kiếm thuốc online với từ khóa \"AMOXICILLIN\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 43
await testRunner.ThenAsync("kết quả tìm kiếm có thuốc Amoxicillin", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("TC_ONLINE_008 - Tìm kiếm từ khóa không tồn tại")]
        [global::NUnit.Framework.CategoryAttribute("Online")]
        [global::NUnit.Framework.CategoryAttribute("TC_ONLINE_008")]
        [global::NUnit.Framework.CategoryAttribute("Severity_LOW")]
        [global::NUnit.Framework.CategoryAttribute("Priority_LOW")]
        public async global::System.Threading.Tasks.Task TC_ONLINE_008_TimKiếmTừKhoaKhongTồnTại()
        {
            string[] tagsOfScenario = new string[] {
                    "Online",
                    "TC_ONLINE_008",
                    "Severity_LOW",
                    "Priority_LOW"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "7";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("TC_ONLINE_008 - Tìm kiếm từ khóa không tồn tại", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 46
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 5
await this.FeatureBackgroundAsync();
#line hidden
#line 47
await testRunner.WhenAsync("Admin tìm kiếm thuốc online với từ khóa \"abcxyzkhongtontai\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 48
await testRunner.ThenAsync("danh sách kết quả tìm kiếm không hiển thị thuốc không liên quan", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("TC_ONLINE_009 - Tìm kiếm bằng chuỗi đặc biệt")]
        [global::NUnit.Framework.CategoryAttribute("Online")]
        [global::NUnit.Framework.CategoryAttribute("TC_ONLINE_009")]
        [global::NUnit.Framework.CategoryAttribute("Severity_HIGH")]
        [global::NUnit.Framework.CategoryAttribute("Priority_HIGH")]
        public async global::System.Threading.Tasks.Task TC_ONLINE_009_TimKiếmBằngChuỗiDặcBiệt()
        {
            string[] tagsOfScenario = new string[] {
                    "Online",
                    "TC_ONLINE_009",
                    "Severity_HIGH",
                    "Priority_HIGH"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "8";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("TC_ONLINE_009 - Tìm kiếm bằng chuỗi đặc biệt", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 51
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 5
await this.FeatureBackgroundAsync();
#line hidden
#line 52
await testRunner.WhenAsync("Admin tìm kiếm thuốc online với chuỗi đặc biệt \"<script>alert(1)</script>\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 53
await testRunner.ThenAsync("hệ thống không thực thi script", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 54
await testRunner.AndAsync("hệ thống không hiển thị lỗi Server Error", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("TC_ONLINE_010 - Lọc danh mục Kháng sinh")]
        [global::NUnit.Framework.CategoryAttribute("Online")]
        [global::NUnit.Framework.CategoryAttribute("TC_ONLINE_010")]
        [global::NUnit.Framework.CategoryAttribute("Severity_MEDIUM")]
        [global::NUnit.Framework.CategoryAttribute("Priority_MEDIUM")]
        public async global::System.Threading.Tasks.Task TC_ONLINE_010_LọcDanhMụcKhangSinh()
        {
            string[] tagsOfScenario = new string[] {
                    "Online",
                    "TC_ONLINE_010",
                    "Severity_MEDIUM",
                    "Priority_MEDIUM"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "9";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("TC_ONLINE_010 - Lọc danh mục Kháng sinh", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 57
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 5
await this.FeatureBackgroundAsync();
#line hidden
#line 58
await testRunner.WhenAsync("Admin lọc thuốc online theo danh mục Kháng sinh", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 59
await testRunner.ThenAsync("danh sách chỉ hiển thị thuốc thuộc danh mục Kháng sinh", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("TC_ONLINE_011 - Lọc danh mục Giảm đau Hạ sốt")]
        [global::NUnit.Framework.CategoryAttribute("Online")]
        [global::NUnit.Framework.CategoryAttribute("TC_ONLINE_011")]
        [global::NUnit.Framework.CategoryAttribute("Severity_MEDIUM")]
        [global::NUnit.Framework.CategoryAttribute("Priority_MEDIUM")]
        public async global::System.Threading.Tasks.Task TC_ONLINE_011_LọcDanhMụcGiảmDauHạSốt()
        {
            string[] tagsOfScenario = new string[] {
                    "Online",
                    "TC_ONLINE_011",
                    "Severity_MEDIUM",
                    "Priority_MEDIUM"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "10";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("TC_ONLINE_011 - Lọc danh mục Giảm đau Hạ sốt", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 62
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 5
await this.FeatureBackgroundAsync();
#line hidden
#line 63
await testRunner.WhenAsync("Admin lọc thuốc online theo danh mục Giảm đau Hạ sốt", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 64
await testRunner.ThenAsync("danh sách chỉ hiển thị thuốc thuộc danh mục Giảm đau Hạ sốt", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("TC_ONLINE_012 - Lọc danh mục Kháng viêm")]
        [global::NUnit.Framework.CategoryAttribute("Online")]
        [global::NUnit.Framework.CategoryAttribute("TC_ONLINE_012")]
        [global::NUnit.Framework.CategoryAttribute("Severity_MEDIUM")]
        [global::NUnit.Framework.CategoryAttribute("Priority_MEDIUM")]
        public async global::System.Threading.Tasks.Task TC_ONLINE_012_LọcDanhMụcKhangViem()
        {
            string[] tagsOfScenario = new string[] {
                    "Online",
                    "TC_ONLINE_012",
                    "Severity_MEDIUM",
                    "Priority_MEDIUM"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "11";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("TC_ONLINE_012 - Lọc danh mục Kháng viêm", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 67
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 5
await this.FeatureBackgroundAsync();
#line hidden
#line 68
await testRunner.WhenAsync("Admin lọc thuốc online theo danh mục Kháng viêm", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 69
await testRunner.ThenAsync("danh sách chỉ hiển thị thuốc thuộc danh mục Kháng viêm", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("TC_ONLINE_013 - Lọc danh mục Vitamin và khoáng chất")]
        [global::NUnit.Framework.CategoryAttribute("Online")]
        [global::NUnit.Framework.CategoryAttribute("TC_ONLINE_013")]
        [global::NUnit.Framework.CategoryAttribute("Severity_MEDIUM")]
        [global::NUnit.Framework.CategoryAttribute("Priority_MEDIUM")]
        public async global::System.Threading.Tasks.Task TC_ONLINE_013_LọcDanhMụcVitaminVaKhoangChất()
        {
            string[] tagsOfScenario = new string[] {
                    "Online",
                    "TC_ONLINE_013",
                    "Severity_MEDIUM",
                    "Priority_MEDIUM"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "12";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("TC_ONLINE_013 - Lọc danh mục Vitamin và khoáng chất", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 72
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 5
await this.FeatureBackgroundAsync();
#line hidden
#line 73
await testRunner.WhenAsync("Admin lọc thuốc online theo danh mục Vitamin và khoáng chất", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 74
await testRunner.ThenAsync("danh sách chỉ hiển thị thuốc thuộc danh mục Vitamin và khoáng chất", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("TC_ONLINE_014 - Lọc tất cả danh mục")]
        [global::NUnit.Framework.CategoryAttribute("Online")]
        [global::NUnit.Framework.CategoryAttribute("TC_ONLINE_014")]
        [global::NUnit.Framework.CategoryAttribute("Severity_LOW")]
        [global::NUnit.Framework.CategoryAttribute("Priority_LOW")]
        public async global::System.Threading.Tasks.Task TC_ONLINE_014_LọcTấtCảDanhMục()
        {
            string[] tagsOfScenario = new string[] {
                    "Online",
                    "TC_ONLINE_014",
                    "Severity_LOW",
                    "Priority_LOW"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "13";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("TC_ONLINE_014 - Lọc tất cả danh mục", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 77
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 5
await this.FeatureBackgroundAsync();
#line hidden
#line 78
await testRunner.WhenAsync("Admin chọn bộ lọc tất cả danh mục thuốc online", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 79
await testRunner.ThenAsync("hệ thống hiển thị lại danh sách thuốc online", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("TC_ONLINE_015 - Kết hợp tìm kiếm và đúng danh mục")]
        [global::NUnit.Framework.CategoryAttribute("Online")]
        [global::NUnit.Framework.CategoryAttribute("TC_ONLINE_015")]
        [global::NUnit.Framework.CategoryAttribute("Severity_MEDIUM")]
        [global::NUnit.Framework.CategoryAttribute("Priority_MEDIUM")]
        public async global::System.Threading.Tasks.Task TC_ONLINE_015_KếtHợpTimKiếmVaDungDanhMục()
        {
            string[] tagsOfScenario = new string[] {
                    "Online",
                    "TC_ONLINE_015",
                    "Severity_MEDIUM",
                    "Priority_MEDIUM"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "14";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("TC_ONLINE_015 - Kết hợp tìm kiếm và đúng danh mục", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 82
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 5
await this.FeatureBackgroundAsync();
#line hidden
#line 83
await testRunner.WhenAsync("Admin tìm kiếm thuốc \"Amoxicillin\" trong danh mục Kháng sinh", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 84
await testRunner.ThenAsync("danh sách hiển thị thuốc thỏa cả tên thuốc và danh mục", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("TC_ONLINE_016 - Kết hợp tìm kiếm và sai danh mục")]
        [global::NUnit.Framework.CategoryAttribute("Online")]
        [global::NUnit.Framework.CategoryAttribute("TC_ONLINE_016")]
        [global::NUnit.Framework.CategoryAttribute("Severity_MEDIUM")]
        [global::NUnit.Framework.CategoryAttribute("Priority_MEDIUM")]
        public async global::System.Threading.Tasks.Task TC_ONLINE_016_KếtHợpTimKiếmVaSaiDanhMục()
        {
            string[] tagsOfScenario = new string[] {
                    "Online",
                    "TC_ONLINE_016",
                    "Severity_MEDIUM",
                    "Priority_MEDIUM"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "15";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("TC_ONLINE_016 - Kết hợp tìm kiếm và sai danh mục", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 87
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 5
await this.FeatureBackgroundAsync();
#line hidden
#line 88
await testRunner.WhenAsync("Admin tìm kiếm thuốc \"Amoxicillin\" trong danh mục Giảm đau Hạ sốt", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 89
await testRunner.ThenAsync("danh sách không hiển thị thuốc sai danh mục", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("TC_ONLINE_017 - Lọc categoryId không hợp lệ")]
        [global::NUnit.Framework.CategoryAttribute("Online")]
        [global::NUnit.Framework.CategoryAttribute("TC_ONLINE_017")]
        [global::NUnit.Framework.CategoryAttribute("Severity_LOW")]
        [global::NUnit.Framework.CategoryAttribute("Priority_LOW")]
        public async global::System.Threading.Tasks.Task TC_ONLINE_017_LọcCategoryIdKhongHợpLệ()
        {
            string[] tagsOfScenario = new string[] {
                    "Online",
                    "TC_ONLINE_017",
                    "Severity_LOW",
                    "Priority_LOW"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "16";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("TC_ONLINE_017 - Lọc categoryId không hợp lệ", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 92
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 5
await this.FeatureBackgroundAsync();
#line hidden
#line 93
await testRunner.WhenAsync("Admin lọc thuốc online với categoryId không hợp lệ", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 94
await testRunner.ThenAsync("hệ thống không hiển thị lỗi Server Error", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("TC_ONLINE_018 - Kiểm tra combobox trạng thái")]
        [global::NUnit.Framework.CategoryAttribute("Online")]
        [global::NUnit.Framework.CategoryAttribute("TC_ONLINE_018")]
        [global::NUnit.Framework.CategoryAttribute("Severity_MEDIUM")]
        [global::NUnit.Framework.CategoryAttribute("Priority_MEDIUM")]
        public async global::System.Threading.Tasks.Task TC_ONLINE_018_KiểmTraComboboxTrạngThai()
        {
            string[] tagsOfScenario = new string[] {
                    "Online",
                    "TC_ONLINE_018",
                    "Severity_MEDIUM",
                    "Priority_MEDIUM"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "17";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("TC_ONLINE_018 - Kiểm tra combobox trạng thái", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 97
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 5
await this.FeatureBackgroundAsync();
#line hidden
#line 98
await testRunner.WhenAsync("Admin truy cập trang Quản lý thuốc bán online", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 99
await testRunner.ThenAsync("mỗi dòng thuốc có combobox trạng thái bán online", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 100
await testRunner.AndAsync("combobox có đủ lựa chọn Cho phép bán online và Không cho phép bán online", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("TC_ONLINE_019 - Tắt bán online và kiểm tra lưu trạng thái")]
        [global::NUnit.Framework.CategoryAttribute("Online")]
        [global::NUnit.Framework.CategoryAttribute("TC_ONLINE_019")]
        [global::NUnit.Framework.CategoryAttribute("Severity_HIGH")]
        [global::NUnit.Framework.CategoryAttribute("Priority_HIGH")]
        public async global::System.Threading.Tasks.Task TC_ONLINE_019_TắtBanOnlineVaKiểmTraLưuTrạngThai()
        {
            string[] tagsOfScenario = new string[] {
                    "Online",
                    "TC_ONLINE_019",
                    "Severity_HIGH",
                    "Priority_HIGH"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "18";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("TC_ONLINE_019 - Tắt bán online và kiểm tra lưu trạng thái", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 103
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 5
await this.FeatureBackgroundAsync();
#line hidden
#line 104
await testRunner.WhenAsync("Admin tắt bán online cho thuốc Amoxicillin", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 105
await testRunner.ThenAsync("trạng thái Không cho phép bán online được lưu sau khi reload", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("TC_ONLINE_020 - Bật bán online và kiểm tra lưu trạng thái")]
        [global::NUnit.Framework.CategoryAttribute("Online")]
        [global::NUnit.Framework.CategoryAttribute("TC_ONLINE_020")]
        [global::NUnit.Framework.CategoryAttribute("Severity_HIGH")]
        [global::NUnit.Framework.CategoryAttribute("Priority_HIGH")]
        public async global::System.Threading.Tasks.Task TC_ONLINE_020_BậtBanOnlineVaKiểmTraLưuTrạngThai()
        {
            string[] tagsOfScenario = new string[] {
                    "Online",
                    "TC_ONLINE_020",
                    "Severity_HIGH",
                    "Priority_HIGH"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "19";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("TC_ONLINE_020 - Bật bán online và kiểm tra lưu trạng thái", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 108
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 5
await this.FeatureBackgroundAsync();
#line hidden
#line 109
await testRunner.WhenAsync("Admin bật bán online cho thuốc Amoxicillin", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 110
await testRunner.ThenAsync("trạng thái Cho phép bán online được lưu sau khi reload", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("TC_ONLINE_021 - Kiểm tra màu trạng thái khi bật bán online")]
        [global::NUnit.Framework.CategoryAttribute("Online")]
        [global::NUnit.Framework.CategoryAttribute("TC_ONLINE_021")]
        [global::NUnit.Framework.CategoryAttribute("Severity_LOW")]
        [global::NUnit.Framework.CategoryAttribute("Priority_LOW")]
        public async global::System.Threading.Tasks.Task TC_ONLINE_021_KiểmTraMauTrạngThaiKhiBậtBanOnline()
        {
            string[] tagsOfScenario = new string[] {
                    "Online",
                    "TC_ONLINE_021",
                    "Severity_LOW",
                    "Priority_LOW"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "20";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("TC_ONLINE_021 - Kiểm tra màu trạng thái khi bật bán online", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 113
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 5
await this.FeatureBackgroundAsync();
#line hidden
#line 114
await testRunner.WhenAsync("Admin bật bán online cho thuốc Amoxicillin", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 115
await testRunner.ThenAsync("trạng thái bật bán online có value bằng 1", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 116
await testRunner.AndAsync("combobox trạng thái có style hiển thị", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("TC_ONLINE_022 - Kiểm tra màu trạng thái khi tắt bán online")]
        [global::NUnit.Framework.CategoryAttribute("Online")]
        [global::NUnit.Framework.CategoryAttribute("TC_ONLINE_022")]
        [global::NUnit.Framework.CategoryAttribute("Severity_LOW")]
        [global::NUnit.Framework.CategoryAttribute("Priority_LOW")]
        public async global::System.Threading.Tasks.Task TC_ONLINE_022_KiểmTraMauTrạngThaiKhiTắtBanOnline()
        {
            string[] tagsOfScenario = new string[] {
                    "Online",
                    "TC_ONLINE_022",
                    "Severity_LOW",
                    "Priority_LOW"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "21";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("TC_ONLINE_022 - Kiểm tra màu trạng thái khi tắt bán online", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 119
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 5
await this.FeatureBackgroundAsync();
#line hidden
#line 120
await testRunner.WhenAsync("Admin tắt bán online cho thuốc Amoxicillin", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 121
await testRunner.ThenAsync("trạng thái tắt bán online có value bằng 0", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 122
await testRunner.AndAsync("combobox trạng thái có style hiển thị", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("TC_ONLINE_023 - User UI khi thuốc cho phép bán online")]
        [global::NUnit.Framework.CategoryAttribute("Online")]
        [global::NUnit.Framework.CategoryAttribute("TC_ONLINE_023")]
        [global::NUnit.Framework.CategoryAttribute("Severity_HIGH")]
        [global::NUnit.Framework.CategoryAttribute("Priority_HIGH")]
        public async global::System.Threading.Tasks.Task TC_ONLINE_023_UserUIKhiThuốcChoPhepBanOnline()
        {
            string[] tagsOfScenario = new string[] {
                    "Online",
                    "TC_ONLINE_023",
                    "Severity_HIGH",
                    "Priority_HIGH"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "22";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("TC_ONLINE_023 - User UI khi thuốc cho phép bán online", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 125
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 5
await this.FeatureBackgroundAsync();
#line hidden
#line 126
await testRunner.WhenAsync("Admin bật bán online cho thuốc Amoxicillin", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 127
await testRunner.AndAsync("User tìm kiếm thuốc Amoxicillin trên giao diện người dùng", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 128
await testRunner.ThenAsync("giao diện User hiển thị nút mua hoặc thêm giỏ cho thuốc Amoxicillin", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("TC_ONLINE_024 - User UI khi thuốc không cho phép bán online")]
        [global::NUnit.Framework.CategoryAttribute("Online")]
        [global::NUnit.Framework.CategoryAttribute("TC_ONLINE_024")]
        [global::NUnit.Framework.CategoryAttribute("Severity_HIGH")]
        [global::NUnit.Framework.CategoryAttribute("Priority_HIGH")]
        public async global::System.Threading.Tasks.Task TC_ONLINE_024_UserUIKhiThuốcKhongChoPhepBanOnline()
        {
            string[] tagsOfScenario = new string[] {
                    "Online",
                    "TC_ONLINE_024",
                    "Severity_HIGH",
                    "Priority_HIGH"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "23";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("TC_ONLINE_024 - User UI khi thuốc không cho phép bán online", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 131
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 5
await this.FeatureBackgroundAsync();
#line hidden
#line 132
await testRunner.WhenAsync("Admin tắt bán online cho thuốc Amoxicillin", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 133
await testRunner.AndAsync("User tìm kiếm thuốc Amoxicillin trên giao diện người dùng", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 134
await testRunner.ThenAsync("giao diện User hiển thị trạng thái mua tại cửa hàng hoặc không bán online cho thu" +
                        "ốc Amoxicillin", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("TC_ONLINE_025 - Backend chặn thêm giỏ khi tắt bán online")]
        [global::NUnit.Framework.CategoryAttribute("Online")]
        [global::NUnit.Framework.CategoryAttribute("TC_ONLINE_025")]
        [global::NUnit.Framework.CategoryAttribute("Severity_CRITICAL")]
        [global::NUnit.Framework.CategoryAttribute("Priority_HIGH")]
        public async global::System.Threading.Tasks.Task TC_ONLINE_025_BackendChặnThemGiỏKhiTắtBanOnline()
        {
            string[] tagsOfScenario = new string[] {
                    "Online",
                    "TC_ONLINE_025",
                    "Severity_CRITICAL",
                    "Priority_HIGH"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "24";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("TC_ONLINE_025 - Backend chặn thêm giỏ khi tắt bán online", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 137
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 5
await this.FeatureBackgroundAsync();
#line hidden
#line 138
await testRunner.WhenAsync("Admin tắt bán online cho thuốc Amoxicillin", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 139
await testRunner.AndAsync("User gửi request Ajax thêm thuốc Amoxicillin vào giỏ hàng", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 140
await testRunner.ThenAsync("backend phải từ chối thêm thuốc đã tắt bán online vào giỏ", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("TC_ONLINE_026 - Backend cho thêm giỏ khi bật bán online")]
        [global::NUnit.Framework.CategoryAttribute("Online")]
        [global::NUnit.Framework.CategoryAttribute("TC_ONLINE_026")]
        [global::NUnit.Framework.CategoryAttribute("Severity_HIGH")]
        [global::NUnit.Framework.CategoryAttribute("Priority_HIGH")]
        public async global::System.Threading.Tasks.Task TC_ONLINE_026_BackendChoThemGiỏKhiBậtBanOnline()
        {
            string[] tagsOfScenario = new string[] {
                    "Online",
                    "TC_ONLINE_026",
                    "Severity_HIGH",
                    "Priority_HIGH"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "25";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("TC_ONLINE_026 - Backend cho thêm giỏ khi bật bán online", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 143
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 5
await this.FeatureBackgroundAsync();
#line hidden
#line 144
await testRunner.WhenAsync("Admin bật bán online cho thuốc Amoxicillin", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 145
await testRunner.AndAsync("User gửi request Ajax thêm thuốc Amoxicillin vào giỏ hàng", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 146
await testRunner.ThenAsync("backend cho phép thêm thuốc đã bật bán online vào giỏ", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("TC_ONLINE_027 - Hiển thị thuốc hết hàng trong Admin")]
        [global::NUnit.Framework.CategoryAttribute("Online")]
        [global::NUnit.Framework.CategoryAttribute("TC_ONLINE_027")]
        [global::NUnit.Framework.CategoryAttribute("Severity_MEDIUM")]
        [global::NUnit.Framework.CategoryAttribute("Priority_MEDIUM")]
        public async global::System.Threading.Tasks.Task TC_ONLINE_027_HiểnThịThuốcHếtHangTrongAdmin()
        {
            string[] tagsOfScenario = new string[] {
                    "Online",
                    "TC_ONLINE_027",
                    "Severity_MEDIUM",
                    "Priority_MEDIUM"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "26";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("TC_ONLINE_027 - Hiển thị thuốc hết hàng trong Admin", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 149
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 5
await this.FeatureBackgroundAsync();
#line hidden
#line 150
await testRunner.WhenAsync("Admin tìm kiếm thuốc online với từ khóa \"Paracetamol\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 151
await testRunner.ThenAsync("thuốc Paracetamol hiển thị trạng thái Hết hàng trong trang Admin", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("TC_ONLINE_028 - Hiển thị cảnh báo lô sắp hết hạn")]
        [global::NUnit.Framework.CategoryAttribute("Online")]
        [global::NUnit.Framework.CategoryAttribute("TC_ONLINE_028")]
        [global::NUnit.Framework.CategoryAttribute("Severity_MEDIUM")]
        [global::NUnit.Framework.CategoryAttribute("Priority_MEDIUM")]
        public async global::System.Threading.Tasks.Task TC_ONLINE_028_HiểnThịCảnhBaoLoSắpHếtHạn()
        {
            string[] tagsOfScenario = new string[] {
                    "Online",
                    "TC_ONLINE_028",
                    "Severity_MEDIUM",
                    "Priority_MEDIUM"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "27";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("TC_ONLINE_028 - Hiển thị cảnh báo lô sắp hết hạn", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 154
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 5
await this.FeatureBackgroundAsync();
#line hidden
#line 155
await testRunner.WhenAsync("Admin tìm kiếm thuốc online với từ khóa \"Amoxicillin\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 156
await testRunner.ThenAsync("thuốc Amoxicillin có cảnh báo lô sắp hết hạn", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("TC_ONLINE_029 - Kiểm tra ảnh thuốc có src")]
        [global::NUnit.Framework.CategoryAttribute("Online")]
        [global::NUnit.Framework.CategoryAttribute("TC_ONLINE_029")]
        [global::NUnit.Framework.CategoryAttribute("Severity_LOW")]
        [global::NUnit.Framework.CategoryAttribute("Priority_LOW")]
        public async global::System.Threading.Tasks.Task TC_ONLINE_029_KiểmTraẢnhThuốcCoSrc()
        {
            string[] tagsOfScenario = new string[] {
                    "Online",
                    "TC_ONLINE_029",
                    "Severity_LOW",
                    "Priority_LOW"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "28";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("TC_ONLINE_029 - Kiểm tra ảnh thuốc có src", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 159
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 5
await this.FeatureBackgroundAsync();
#line hidden
#line 160
await testRunner.WhenAsync("Admin truy cập trang Quản lý thuốc bán online", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 161
await testRunner.ThenAsync("ảnh thuốc trong bảng có đường dẫn src", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("TC_ONLINE_030 - Kiểm tra ảnh thuốc tải được")]
        [global::NUnit.Framework.CategoryAttribute("Online")]
        [global::NUnit.Framework.CategoryAttribute("TC_ONLINE_030")]
        [global::NUnit.Framework.CategoryAttribute("Severity_MEDIUM")]
        [global::NUnit.Framework.CategoryAttribute("Priority_MEDIUM")]
        public async global::System.Threading.Tasks.Task TC_ONLINE_030_KiểmTraẢnhThuốcTảiDược()
        {
            string[] tagsOfScenario = new string[] {
                    "Online",
                    "TC_ONLINE_030",
                    "Severity_MEDIUM",
                    "Priority_MEDIUM"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "29";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("TC_ONLINE_030 - Kiểm tra ảnh thuốc tải được", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 164
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 5
await this.FeatureBackgroundAsync();
#line hidden
#line 165
await testRunner.WhenAsync("Admin truy cập trang Quản lý thuốc bán online", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 166
await testRunner.ThenAsync("ảnh thuốc trong bảng không bị vỡ hoặc không tải được", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("TC_ONLINE_031 - Kiểm tra định dạng giá bán")]
        [global::NUnit.Framework.CategoryAttribute("Online")]
        [global::NUnit.Framework.CategoryAttribute("TC_ONLINE_031")]
        [global::NUnit.Framework.CategoryAttribute("Severity_LOW")]
        [global::NUnit.Framework.CategoryAttribute("Priority_LOW")]
        public async global::System.Threading.Tasks.Task TC_ONLINE_031_KiểmTraDịnhDạngGiaBan()
        {
            string[] tagsOfScenario = new string[] {
                    "Online",
                    "TC_ONLINE_031",
                    "Severity_LOW",
                    "Priority_LOW"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "30";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("TC_ONLINE_031 - Kiểm tra định dạng giá bán", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 169
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 5
await this.FeatureBackgroundAsync();
#line hidden
#line 170
await testRunner.WhenAsync("Admin truy cập trang Quản lý thuốc bán online", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 171
await testRunner.ThenAsync("giá bán trong bảng là số dương", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 172
await testRunner.AndAsync("giá bán trong bảng có ký hiệu đ", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("TC_ONLINE_032 - Kiểm tra định dạng tồn kho")]
        [global::NUnit.Framework.CategoryAttribute("Online")]
        [global::NUnit.Framework.CategoryAttribute("TC_ONLINE_032")]
        [global::NUnit.Framework.CategoryAttribute("Severity_LOW")]
        [global::NUnit.Framework.CategoryAttribute("Priority_LOW")]
        public async global::System.Threading.Tasks.Task TC_ONLINE_032_KiểmTraDịnhDạngTồnKho()
        {
            string[] tagsOfScenario = new string[] {
                    "Online",
                    "TC_ONLINE_032",
                    "Severity_LOW",
                    "Priority_LOW"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "31";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("TC_ONLINE_032 - Kiểm tra định dạng tồn kho", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 175
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 5
await this.FeatureBackgroundAsync();
#line hidden
#line 176
await testRunner.WhenAsync("Admin truy cập trang Quản lý thuốc bán online", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 177
await testRunner.ThenAsync("tồn kho trong bảng là số không âm hoặc nhãn Hết hàng", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("TC_ONLINE_033 - Kiểm tra tooltip cảnh báo lô sắp hết hạn")]
        [global::NUnit.Framework.CategoryAttribute("Online")]
        [global::NUnit.Framework.CategoryAttribute("TC_ONLINE_033")]
        [global::NUnit.Framework.CategoryAttribute("Severity_LOW")]
        [global::NUnit.Framework.CategoryAttribute("Priority_LOW")]
        public async global::System.Threading.Tasks.Task TC_ONLINE_033_KiểmTraTooltipCảnhBaoLoSắpHếtHạn()
        {
            string[] tagsOfScenario = new string[] {
                    "Online",
                    "TC_ONLINE_033",
                    "Severity_LOW",
                    "Priority_LOW"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "32";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("TC_ONLINE_033 - Kiểm tra tooltip cảnh báo lô sắp hết hạn", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 180
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 5
await this.FeatureBackgroundAsync();
#line hidden
#line 181
await testRunner.WhenAsync("Admin tìm kiếm thuốc online với từ khóa \"Amoxicillin\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 182
await testRunner.ThenAsync("cảnh báo lô sắp hết hạn có tooltip mô tả đúng", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("TC_ONLINE_034 - Kiểm tra nhiều điều kiện tìm kiếm lọc liên tục")]
        [global::NUnit.Framework.CategoryAttribute("Online")]
        [global::NUnit.Framework.CategoryAttribute("TC_ONLINE_034")]
        [global::NUnit.Framework.CategoryAttribute("Severity_HIGH")]
        [global::NUnit.Framework.CategoryAttribute("Priority_HIGH")]
        public async global::System.Threading.Tasks.Task TC_ONLINE_034_KiểmTraNhiềuDiềuKiệnTimKiếmLọcLienTục()
        {
            string[] tagsOfScenario = new string[] {
                    "Online",
                    "TC_ONLINE_034",
                    "Severity_HIGH",
                    "Priority_HIGH"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "33";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("TC_ONLINE_034 - Kiểm tra nhiều điều kiện tìm kiếm lọc liên tục", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 185
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 5
await this.FeatureBackgroundAsync();
#line hidden
#line 186
await testRunner.WhenAsync("Admin thực hiện nhiều điều kiện tìm kiếm và lọc thuốc online liên tục", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 187
await testRunner.ThenAsync("không điều kiện nào gây lỗi Server Error", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("TC_ONLINE_035 - Responsive trang Quản lý thuốc online")]
        [global::NUnit.Framework.CategoryAttribute("Online")]
        [global::NUnit.Framework.CategoryAttribute("TC_ONLINE_035")]
        [global::NUnit.Framework.CategoryAttribute("Severity_LOW")]
        [global::NUnit.Framework.CategoryAttribute("Priority_LOW")]
        public async global::System.Threading.Tasks.Task TC_ONLINE_035_ResponsiveTrangQuảnLyThuốcOnline()
        {
            string[] tagsOfScenario = new string[] {
                    "Online",
                    "TC_ONLINE_035",
                    "Severity_LOW",
                    "Priority_LOW"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "34";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("TC_ONLINE_035 - Responsive trang Quản lý thuốc online", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 190
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 5
await this.FeatureBackgroundAsync();
#line hidden
#line 191
await testRunner.GivenAsync("trình duyệt đang ở kích thước màn hình mobile 390px", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 192
await testRunner.WhenAsync("Admin truy cập trang Quản lý thuốc bán online", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 193
await testRunner.ThenAsync("trang Quản lý thuốc online không bị tràn ngang nghiêm trọng trên mobile", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
    }
}
#pragma warning restore
#endregion
