// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace KDPM_ReqnrollSeleniumAutomationTesting_Nhom5.Features
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::NUnit.Framework.TestFixtureAttribute()]
    [global::NUnit.Framework.DescriptionAttribute("Quản lý lô tiêu hủy")]
    [global::NUnit.Framework.FixtureLifeCycleAttribute(global::NUnit.Framework.LifeCycle.InstancePerTestCase)]
    public partial class QuảnLyLoTieuHủyFeature
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "Features", "Quản lý lô tiêu hủy", "Kiểm thử chức năng Quản lý lô tiêu hủy của hệ thống MedForAll.\r\nCác scenario tron" +
                "g file này được đồng bộ theo test case Selenium đã chạy.", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
#line 1 "QuanLyLoTieuHuy.feature"
#line hidden
        
        [global::NUnit.Framework.OneTimeSetUpAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        [global::NUnit.Framework.OneTimeTearDownAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        [global::NUnit.Framework.SetUpAttribute()]
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        [global::NUnit.Framework.TearDownAttribute()]
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<global::NUnit.Framework.TestContext>(global::NUnit.Framework.TestContext.CurrentContext);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/QuanLyLoTieuHuy.feature.ndjson", 26);
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("TC_ADMIN_LOTIEUHUY_001 - Mở trang Quản lý Lô tiêu hủy")]
        [global::NUnit.Framework.CategoryAttribute("LoTieuHuy")]
        [global::NUnit.Framework.CategoryAttribute("TC_ADMIN_LOTIEUHUY_001")]
        [global::NUnit.Framework.CategoryAttribute("Severity_LOW")]
        [global::NUnit.Framework.CategoryAttribute("Priority_LOW")]
        public async global::System.Threading.Tasks.Task TC_ADMIN_LOTIEUHUY_001_MởTrangQuảnLyLoTieuHủy()
        {
            string[] tagsOfScenario = new string[] {
                    "LoTieuHuy",
                    "TC_ADMIN_LOTIEUHUY_001",
                    "Severity_LOW",
                    "Priority_LOW"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "0";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("TC_ADMIN_LOTIEUHUY_001 - Mở trang Quản lý Lô tiêu hủy", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 7
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 8
await testRunner.WhenAsync("Admin truy cập trang Quản lý Lô tiêu hủy", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 9
await testRunner.ThenAsync("trang Quản lý Lô tiêu hủy mở được, có tiêu đề và không hiển thị lỗi hệ thống", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("TC_ADMIN_LOTIEUHUY_002 - Kiểm tra sidebar active")]
        [global::NUnit.Framework.CategoryAttribute("LoTieuHuy")]
        [global::NUnit.Framework.CategoryAttribute("TC_ADMIN_LOTIEUHUY_002")]
        [global::NUnit.Framework.CategoryAttribute("Severity_LOW")]
        [global::NUnit.Framework.CategoryAttribute("Priority_LOW")]
        public async global::System.Threading.Tasks.Task TC_ADMIN_LOTIEUHUY_002_KiểmTraSidebarActive()
        {
            string[] tagsOfScenario = new string[] {
                    "LoTieuHuy",
                    "TC_ADMIN_LOTIEUHUY_002",
                    "Severity_LOW",
                    "Priority_LOW"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "1";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("TC_ADMIN_LOTIEUHUY_002 - Kiểm tra sidebar active", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 12
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 13
await testRunner.WhenAsync("Admin truy cập trang Quản lý Lô tiêu hủy", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 14
await testRunner.ThenAsync("menu Quản lý Lô tiêu hủy trên sidebar được active đúng", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("TC_ADMIN_LOTIEUHUY_003 - Kiểm tra tiêu đề cột bảng")]
        [global::NUnit.Framework.CategoryAttribute("LoTieuHuy")]
        [global::NUnit.Framework.CategoryAttribute("TC_ADMIN_LOTIEUHUY_003")]
        [global::NUnit.Framework.CategoryAttribute("Severity_LOW")]
        [global::NUnit.Framework.CategoryAttribute("Priority_LOW")]
        public async global::System.Threading.Tasks.Task TC_ADMIN_LOTIEUHUY_003_KiểmTraTieuDềCộtBảng()
        {
            string[] tagsOfScenario = new string[] {
                    "LoTieuHuy",
                    "TC_ADMIN_LOTIEUHUY_003",
                    "Severity_LOW",
                    "Priority_LOW"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "2";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("TC_ADMIN_LOTIEUHUY_003 - Kiểm tra tiêu đề cột bảng", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 17
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 18
await testRunner.WhenAsync("Admin truy cập trang Quản lý Lô tiêu hủy", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 19
await testRunner.ThenAsync("bảng lô tiêu hủy hiển thị đủ các cột Thuốc, Số lô, Hạn sử dụng, Giá nhập, Nhập , " +
                        "Tồn và Trạng thái", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("TC_ADMIN_LOTIEUHUY_004 - Kiểm tra bảng có dữ liệu hợp lệ")]
        [global::NUnit.Framework.CategoryAttribute("LoTieuHuy")]
        [global::NUnit.Framework.CategoryAttribute("TC_ADMIN_LOTIEUHUY_004")]
        [global::NUnit.Framework.CategoryAttribute("Severity_MEDIUM")]
        [global::NUnit.Framework.CategoryAttribute("Priority_MEDIUM")]
        public async global::System.Threading.Tasks.Task TC_ADMIN_LOTIEUHUY_004_KiểmTraBảngCoDữLiệuHợpLệ()
        {
            string[] tagsOfScenario = new string[] {
                    "LoTieuHuy",
                    "TC_ADMIN_LOTIEUHUY_004",
                    "Severity_MEDIUM",
                    "Priority_MEDIUM"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "3";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("TC_ADMIN_LOTIEUHUY_004 - Kiểm tra bảng có dữ liệu hợp lệ", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 22
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 23
await testRunner.WhenAsync("Admin truy cập trang Quản lý Lô tiêu hủy", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 24
await testRunner.ThenAsync("danh sách lô tiêu hủy hiển thị dữ liệu hợp lệ gồm tên thuốc, số lô, hạn sử dụng, " +
                        "giá nhập và trạng thái", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("TC_ADMIN_LOTIEUHUY_005 - Kiểm tra chỉ hiển thị trạng thái Đã tiêu hủy")]
        [global::NUnit.Framework.CategoryAttribute("LoTieuHuy")]
        [global::NUnit.Framework.CategoryAttribute("TC_ADMIN_LOTIEUHUY_005")]
        [global::NUnit.Framework.CategoryAttribute("Severity_HIGH")]
        [global::NUnit.Framework.CategoryAttribute("Priority_HIGH")]
        public async global::System.Threading.Tasks.Task TC_ADMIN_LOTIEUHUY_005_KiểmTraChỉHiểnThịTrạngThaiDaTieuHủy()
        {
            string[] tagsOfScenario = new string[] {
                    "LoTieuHuy",
                    "TC_ADMIN_LOTIEUHUY_005",
                    "Severity_HIGH",
                    "Priority_HIGH"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "4";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("TC_ADMIN_LOTIEUHUY_005 - Kiểm tra chỉ hiển thị trạng thái Đã tiêu hủy", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 27
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 28
await testRunner.WhenAsync("Admin truy cập trang Quản lý Lô tiêu hủy", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 29
await testRunner.ThenAsync("tất cả dòng trong bảng phải có trạng thái Đã tiêu hủy", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("TC_ADMIN_LOTIEUHUY_006 - Kiểm tra tồn kho sau tiêu hủy bằng 0")]
        [global::NUnit.Framework.CategoryAttribute("LoTieuHuy")]
        [global::NUnit.Framework.CategoryAttribute("TC_ADMIN_LOTIEUHUY_006")]
        [global::NUnit.Framework.CategoryAttribute("Severity_HIGH")]
        [global::NUnit.Framework.CategoryAttribute("Priority_HIGH")]
        public async global::System.Threading.Tasks.Task TC_ADMIN_LOTIEUHUY_006_KiểmTraTồnKhoSauTieuHủyBằng0()
        {
            string[] tagsOfScenario = new string[] {
                    "LoTieuHuy",
                    "TC_ADMIN_LOTIEUHUY_006",
                    "Severity_HIGH",
                    "Priority_HIGH"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "5";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("TC_ADMIN_LOTIEUHUY_006 - Kiểm tra tồn kho sau tiêu hủy bằng 0", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 32
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 33
await testRunner.WhenAsync("Admin truy cập trang Quản lý Lô tiêu hủy", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 34
await testRunner.ThenAsync("tất cả lô đã tiêu hủy phải có tồn kho bằng 0", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("TC_ADMIN_LOTIEUHUY_007 - Kiểm tra không có nút tác vụ")]
        [global::NUnit.Framework.CategoryAttribute("LoTieuHuy")]
        [global::NUnit.Framework.CategoryAttribute("TC_ADMIN_LOTIEUHUY_007")]
        [global::NUnit.Framework.CategoryAttribute("Severity_HIGH")]
        [global::NUnit.Framework.CategoryAttribute("Priority_HIGH")]
        public async global::System.Threading.Tasks.Task TC_ADMIN_LOTIEUHUY_007_KiểmTraKhongCoNutTacVụ()
        {
            string[] tagsOfScenario = new string[] {
                    "LoTieuHuy",
                    "TC_ADMIN_LOTIEUHUY_007",
                    "Severity_HIGH",
                    "Priority_HIGH"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "6";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("TC_ADMIN_LOTIEUHUY_007 - Kiểm tra không có nút tác vụ", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 37
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 38
await testRunner.WhenAsync("Admin truy cập trang Quản lý Lô tiêu hủy", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 39
await testRunner.ThenAsync("trang lô tiêu hủy chỉ dùng để xem và không có nút xóa, sửa hoặc tiêu hủy lại", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("TC_ADMIN_LOTIEUHUY_008 - Lọc lô tiêu hủy Đã hết hạn")]
        [global::NUnit.Framework.CategoryAttribute("LoTieuHuy")]
        [global::NUnit.Framework.CategoryAttribute("TC_ADMIN_LOTIEUHUY_008")]
        [global::NUnit.Framework.CategoryAttribute("Severity_MEDIUM")]
        [global::NUnit.Framework.CategoryAttribute("Priority_MEDIUM")]
        public async global::System.Threading.Tasks.Task TC_ADMIN_LOTIEUHUY_008_LọcLoTieuHủyDaHếtHạn()
        {
            string[] tagsOfScenario = new string[] {
                    "LoTieuHuy",
                    "TC_ADMIN_LOTIEUHUY_008",
                    "Severity_MEDIUM",
                    "Priority_MEDIUM"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "7";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("TC_ADMIN_LOTIEUHUY_008 - Lọc lô tiêu hủy Đã hết hạn", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 42
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 43
await testRunner.WhenAsync("Admin lọc lô tiêu hủy theo trạng thái Đã hết hạn", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 44
await testRunner.ThenAsync("hệ thống chỉ hiển thị các lô tiêu hủy có hạn sử dụng nhỏ hơn ngày hiện tại", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("TC_ADMIN_LOTIEUHUY_009 - Lọc lô tiêu hủy Sắp hết hạn")]
        [global::NUnit.Framework.CategoryAttribute("LoTieuHuy")]
        [global::NUnit.Framework.CategoryAttribute("TC_ADMIN_LOTIEUHUY_009")]
        [global::NUnit.Framework.CategoryAttribute("Severity_MEDIUM")]
        [global::NUnit.Framework.CategoryAttribute("Priority_MEDIUM")]
        public async global::System.Threading.Tasks.Task TC_ADMIN_LOTIEUHUY_009_LọcLoTieuHủySắpHếtHạn()
        {
            string[] tagsOfScenario = new string[] {
                    "LoTieuHuy",
                    "TC_ADMIN_LOTIEUHUY_009",
                    "Severity_MEDIUM",
                    "Priority_MEDIUM"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "8";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("TC_ADMIN_LOTIEUHUY_009 - Lọc lô tiêu hủy Sắp hết hạn", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 47
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 48
await testRunner.WhenAsync("Admin lọc lô tiêu hủy theo trạng thái Sắp hết hạn", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 49
await testRunner.ThenAsync("hệ thống chỉ hiển thị các lô tiêu hủy có hạn sử dụng từ ngày hiện tại đến 90 ngày" +
                        " tới", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("TC_ADMIN_LOTIEUHUY_010 - Lọc Tất cả lô tiêu hủy")]
        [global::NUnit.Framework.CategoryAttribute("LoTieuHuy")]
        [global::NUnit.Framework.CategoryAttribute("TC_ADMIN_LOTIEUHUY_010")]
        [global::NUnit.Framework.CategoryAttribute("Severity_LOW")]
        [global::NUnit.Framework.CategoryAttribute("Priority_LOW")]
        public async global::System.Threading.Tasks.Task TC_ADMIN_LOTIEUHUY_010_LọcTấtCảLoTieuHủy()
        {
            string[] tagsOfScenario = new string[] {
                    "LoTieuHuy",
                    "TC_ADMIN_LOTIEUHUY_010",
                    "Severity_LOW",
                    "Priority_LOW"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "9";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("TC_ADMIN_LOTIEUHUY_010 - Lọc Tất cả lô tiêu hủy", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 52
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 53
await testRunner.WhenAsync("Admin chọn bộ lọc Tất cả lô tiêu hủy", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 54
await testRunner.ThenAsync("hệ thống hiển thị toàn bộ danh sách lô đã tiêu hủy", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("TC_ADMIN_LOTIEUHUY_011 - Kiểm tra đường dẫn 3 nút lọc")]
        [global::NUnit.Framework.CategoryAttribute("LoTieuHuy")]
        [global::NUnit.Framework.CategoryAttribute("TC_ADMIN_LOTIEUHUY_011")]
        [global::NUnit.Framework.CategoryAttribute("Severity_LOW")]
        [global::NUnit.Framework.CategoryAttribute("Priority_LOW")]
        public async global::System.Threading.Tasks.Task TC_ADMIN_LOTIEUHUY_011_KiểmTraDườngDẫn3NutLọc()
        {
            string[] tagsOfScenario = new string[] {
                    "LoTieuHuy",
                    "TC_ADMIN_LOTIEUHUY_011",
                    "Severity_LOW",
                    "Priority_LOW"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "10";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("TC_ADMIN_LOTIEUHUY_011 - Kiểm tra đường dẫn 3 nút lọc", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 57
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 58
await testRunner.WhenAsync("Admin truy cập trang Quản lý Lô tiêu hủy", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 59
await testRunner.ThenAsync("các nút Sắp hết hạn, Đã hết hạn và Tất cả có đường dẫn lọc đúng", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("TC_ADMIN_LOTIEUHUY_012 - Kiểm tra link sort Số lô không chuyển sai trang")]
        [global::NUnit.Framework.CategoryAttribute("LoTieuHuy")]
        [global::NUnit.Framework.CategoryAttribute("TC_ADMIN_LOTIEUHUY_012")]
        [global::NUnit.Framework.CategoryAttribute("Severity_MEDIUM")]
        [global::NUnit.Framework.CategoryAttribute("Priority_HIGH")]
        public async global::System.Threading.Tasks.Task TC_ADMIN_LOTIEUHUY_012_KiểmTraLinkSortSốLoKhongChuyểnSaiTrang()
        {
            string[] tagsOfScenario = new string[] {
                    "LoTieuHuy",
                    "TC_ADMIN_LOTIEUHUY_012",
                    "Severity_MEDIUM",
                    "Priority_HIGH"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "11";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("TC_ADMIN_LOTIEUHUY_012 - Kiểm tra link sort Số lô không chuyển sai trang", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 62
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 63
await testRunner.WhenAsync("Admin kiểm tra link sắp xếp Số lô ở trang Quản lý Lô tiêu hủy", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 64
await testRunner.ThenAsync("link sort Số lô phải ở lại trang Quản lý Lô tiêu hủy và không chuyển nhầm sang tr" +
                        "ang Quản lý Lô thuốc", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("TC_ADMIN_LOTIEUHUY_013 - Sắp xếp theo Số lô tăng dần")]
        [global::NUnit.Framework.CategoryAttribute("LoTieuHuy")]
        [global::NUnit.Framework.CategoryAttribute("TC_ADMIN_LOTIEUHUY_013")]
        [global::NUnit.Framework.CategoryAttribute("Severity_LOW")]
        [global::NUnit.Framework.CategoryAttribute("Priority_LOW")]
        public async global::System.Threading.Tasks.Task TC_ADMIN_LOTIEUHUY_013_SắpXếpTheoSốLoTangDần()
        {
            string[] tagsOfScenario = new string[] {
                    "LoTieuHuy",
                    "TC_ADMIN_LOTIEUHUY_013",
                    "Severity_LOW",
                    "Priority_LOW"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "12";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("TC_ADMIN_LOTIEUHUY_013 - Sắp xếp theo Số lô tăng dần", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 67
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 68
await testRunner.WhenAsync("Admin sắp xếp danh sách lô tiêu hủy theo Số lô tăng dần", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 69
await testRunner.ThenAsync("danh sách lô tiêu hủy được sắp xếp đúng theo số lô tăng dần", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("TC_ADMIN_LOTIEUHUY_014 - Kiểm tra phân loại hạn sử dụng")]
        [global::NUnit.Framework.CategoryAttribute("LoTieuHuy")]
        [global::NUnit.Framework.CategoryAttribute("TC_ADMIN_LOTIEUHUY_014")]
        [global::NUnit.Framework.CategoryAttribute("Severity_MEDIUM")]
        [global::NUnit.Framework.CategoryAttribute("Priority_MEDIUM")]
        public async global::System.Threading.Tasks.Task TC_ADMIN_LOTIEUHUY_014_KiểmTraPhanLoạiHạnSửDụng()
        {
            string[] tagsOfScenario = new string[] {
                    "LoTieuHuy",
                    "TC_ADMIN_LOTIEUHUY_014",
                    "Severity_MEDIUM",
                    "Priority_MEDIUM"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "13";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("TC_ADMIN_LOTIEUHUY_014 - Kiểm tra phân loại hạn sử dụng", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 72
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 73
await testRunner.WhenAsync("Admin truy cập trang Quản lý Lô tiêu hủy", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 74
await testRunner.ThenAsync("các lô hết hạn và sắp hết hạn được gắn nhãn hoặc đánh dấu phù hợp", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("TC_ADMIN_LOTIEUHUY_015 - Kiểm tra định dạng giá nhập")]
        [global::NUnit.Framework.CategoryAttribute("LoTieuHuy")]
        [global::NUnit.Framework.CategoryAttribute("TC_ADMIN_LOTIEUHUY_015")]
        [global::NUnit.Framework.CategoryAttribute("Severity_MEDIUM")]
        [global::NUnit.Framework.CategoryAttribute("Priority_MEDIUM")]
        public async global::System.Threading.Tasks.Task TC_ADMIN_LOTIEUHUY_015_KiểmTraDịnhDạngGiaNhập()
        {
            string[] tagsOfScenario = new string[] {
                    "LoTieuHuy",
                    "TC_ADMIN_LOTIEUHUY_015",
                    "Severity_MEDIUM",
                    "Priority_MEDIUM"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "14";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("TC_ADMIN_LOTIEUHUY_015 - Kiểm tra định dạng giá nhập", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 77
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 78
await testRunner.WhenAsync("Admin truy cập trang Quản lý Lô tiêu hủy", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 79
await testRunner.ThenAsync("giá nhập của các lô tiêu hủy là số dương và hiển thị đúng định dạng", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("TC_ADMIN_LOTIEUHUY_016 - Kiểm tra định dạng Nhập , Tồn")]
        [global::NUnit.Framework.CategoryAttribute("LoTieuHuy")]
        [global::NUnit.Framework.CategoryAttribute("TC_ADMIN_LOTIEUHUY_016")]
        [global::NUnit.Framework.CategoryAttribute("Severity_HIGH")]
        [global::NUnit.Framework.CategoryAttribute("Priority_HIGH")]
        public async global::System.Threading.Tasks.Task TC_ADMIN_LOTIEUHUY_016_KiểmTraDịnhDạngNhậpTồn()
        {
            string[] tagsOfScenario = new string[] {
                    "LoTieuHuy",
                    "TC_ADMIN_LOTIEUHUY_016",
                    "Severity_HIGH",
                    "Priority_HIGH"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "15";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("TC_ADMIN_LOTIEUHUY_016 - Kiểm tra định dạng Nhập , Tồn", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 82
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 83
await testRunner.WhenAsync("Admin truy cập trang Quản lý Lô tiêu hủy", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 84
await testRunner.ThenAsync("số nhập hiển thị hợp lệ và tồn kho của lô tiêu hủy phải bằng 0", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("TC_ADMIN_LOTIEUHUY_017 - Kiểm tra màu giao diện lô đã tiêu hủy")]
        [global::NUnit.Framework.CategoryAttribute("LoTieuHuy")]
        [global::NUnit.Framework.CategoryAttribute("TC_ADMIN_LOTIEUHUY_017")]
        [global::NUnit.Framework.CategoryAttribute("Severity_LOW")]
        [global::NUnit.Framework.CategoryAttribute("Priority_LOW")]
        public async global::System.Threading.Tasks.Task TC_ADMIN_LOTIEUHUY_017_KiểmTraMauGiaoDiệnLoDaTieuHủy()
        {
            string[] tagsOfScenario = new string[] {
                    "LoTieuHuy",
                    "TC_ADMIN_LOTIEUHUY_017",
                    "Severity_LOW",
                    "Priority_LOW"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "16";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("TC_ADMIN_LOTIEUHUY_017 - Kiểm tra màu giao diện lô đã tiêu hủy", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 87
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 88
await testRunner.WhenAsync("Admin truy cập trang Quản lý Lô tiêu hủy", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 89
await testRunner.ThenAsync("các lô đã tiêu hủy có màu xám và chữ mờ đúng giao diện", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("TC_ADMIN_LOTIEUHUY_018 - Kiểm tra ảnh thuốc có src")]
        [global::NUnit.Framework.CategoryAttribute("LoTieuHuy")]
        [global::NUnit.Framework.CategoryAttribute("TC_ADMIN_LOTIEUHUY_018")]
        [global::NUnit.Framework.CategoryAttribute("Severity_LOW")]
        [global::NUnit.Framework.CategoryAttribute("Priority_LOW")]
        public async global::System.Threading.Tasks.Task TC_ADMIN_LOTIEUHUY_018_KiểmTraẢnhThuốcCoSrc()
        {
            string[] tagsOfScenario = new string[] {
                    "LoTieuHuy",
                    "TC_ADMIN_LOTIEUHUY_018",
                    "Severity_LOW",
                    "Priority_LOW"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "17";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("TC_ADMIN_LOTIEUHUY_018 - Kiểm tra ảnh thuốc có src", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 92
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 93
await testRunner.WhenAsync("Admin truy cập trang Quản lý Lô tiêu hủy", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 94
await testRunner.ThenAsync("ảnh thuốc trong bảng lô tiêu hủy có đường dẫn src", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("TC_ADMIN_LOTIEUHUY_019 - Kiểm tra ảnh thuốc tải được")]
        [global::NUnit.Framework.CategoryAttribute("LoTieuHuy")]
        [global::NUnit.Framework.CategoryAttribute("TC_ADMIN_LOTIEUHUY_019")]
        [global::NUnit.Framework.CategoryAttribute("Severity_LOW")]
        [global::NUnit.Framework.CategoryAttribute("Priority_LOW")]
        public async global::System.Threading.Tasks.Task TC_ADMIN_LOTIEUHUY_019_KiểmTraẢnhThuốcTảiDược()
        {
            string[] tagsOfScenario = new string[] {
                    "LoTieuHuy",
                    "TC_ADMIN_LOTIEUHUY_019",
                    "Severity_LOW",
                    "Priority_LOW"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "18";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("TC_ADMIN_LOTIEUHUY_019 - Kiểm tra ảnh thuốc tải được", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 97
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 98
await testRunner.WhenAsync("Admin truy cập trang Quản lý Lô tiêu hủy", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 99
await testRunner.ThenAsync("không có ảnh thuốc bị vỡ trong bảng lô tiêu hủy", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("TC_ADMIN_LOTIEUHUY_020 - Kiểm tra không hiển thị số âm")]
        [global::NUnit.Framework.CategoryAttribute("LoTieuHuy")]
        [global::NUnit.Framework.CategoryAttribute("TC_ADMIN_LOTIEUHUY_020")]
        [global::NUnit.Framework.CategoryAttribute("Severity_MEDIUM")]
        [global::NUnit.Framework.CategoryAttribute("Priority_MEDIUM")]
        public async global::System.Threading.Tasks.Task TC_ADMIN_LOTIEUHUY_020_KiểmTraKhongHiểnThịSốAm()
        {
            string[] tagsOfScenario = new string[] {
                    "LoTieuHuy",
                    "TC_ADMIN_LOTIEUHUY_020",
                    "Severity_MEDIUM",
                    "Priority_MEDIUM"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "19";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("TC_ADMIN_LOTIEUHUY_020 - Kiểm tra không hiển thị số âm", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 102
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 103
await testRunner.WhenAsync("Admin truy cập trang Quản lý Lô tiêu hủy", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 104
await testRunner.ThenAsync("trang Quản lý Lô tiêu hủy không hiển thị số âm bất thường", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("TC_ADMIN_LOTIEUHUY_021 - Kiểm tra status param không hợp lệ")]
        [global::NUnit.Framework.CategoryAttribute("LoTieuHuy")]
        [global::NUnit.Framework.CategoryAttribute("TC_ADMIN_LOTIEUHUY_021")]
        [global::NUnit.Framework.CategoryAttribute("Severity_MEDIUM")]
        [global::NUnit.Framework.CategoryAttribute("Priority_MEDIUM")]
        public async global::System.Threading.Tasks.Task TC_ADMIN_LOTIEUHUY_021_KiểmTraStatusParamKhongHợpLệ()
        {
            string[] tagsOfScenario = new string[] {
                    "LoTieuHuy",
                    "TC_ADMIN_LOTIEUHUY_021",
                    "Severity_MEDIUM",
                    "Priority_MEDIUM"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "20";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("TC_ADMIN_LOTIEUHUY_021 - Kiểm tra status param không hợp lệ", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 107
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 108
await testRunner.WhenAsync("Admin truy cập trang Quản lý Lô tiêu hủy với status không hợp lệ", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 109
await testRunner.ThenAsync("hệ thống không phát sinh lỗi hệ thống", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("TC_ADMIN_LOTIEUHUY_022 - Kiểm tra không chứa thao tác xử lý lại")]
        [global::NUnit.Framework.CategoryAttribute("LoTieuHuy")]
        [global::NUnit.Framework.CategoryAttribute("TC_ADMIN_LOTIEUHUY_022")]
        [global::NUnit.Framework.CategoryAttribute("Severity_HIGH")]
        [global::NUnit.Framework.CategoryAttribute("Priority_HIGH")]
        public async global::System.Threading.Tasks.Task TC_ADMIN_LOTIEUHUY_022_KiểmTraKhongChứaThaoTacXửLyLại()
        {
            string[] tagsOfScenario = new string[] {
                    "LoTieuHuy",
                    "TC_ADMIN_LOTIEUHUY_022",
                    "Severity_HIGH",
                    "Priority_HIGH"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "21";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("TC_ADMIN_LOTIEUHUY_022 - Kiểm tra không chứa thao tác xử lý lại", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 112
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 113
await testRunner.WhenAsync("Admin truy cập trang Quản lý Lô tiêu hủy", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 114
await testRunner.ThenAsync("trang không chứa hàm hoặc endpoint xóa, sửa, tiêu hủy lại lô thuốc", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("TC_ADMIN_LOTIEUHUY_023 - Kiểm tra nút Thoát")]
        [global::NUnit.Framework.CategoryAttribute("LoTieuHuy")]
        [global::NUnit.Framework.CategoryAttribute("TC_ADMIN_LOTIEUHUY_023")]
        [global::NUnit.Framework.CategoryAttribute("Severity_LOW")]
        [global::NUnit.Framework.CategoryAttribute("Priority_LOW")]
        public async global::System.Threading.Tasks.Task TC_ADMIN_LOTIEUHUY_023_KiểmTraNutThoat()
        {
            string[] tagsOfScenario = new string[] {
                    "LoTieuHuy",
                    "TC_ADMIN_LOTIEUHUY_023",
                    "Severity_LOW",
                    "Priority_LOW"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "22";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("TC_ADMIN_LOTIEUHUY_023 - Kiểm tra nút Thoát", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 117
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 118
await testRunner.WhenAsync("Admin truy cập trang Quản lý Lô tiêu hủy", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 119
await testRunner.ThenAsync("nút Thoát hiển thị và có đường dẫn hợp lệ", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("TC_ADMIN_LOTIEUHUY_024 - Responsive trang Quản lý Lô tiêu hủy")]
        [global::NUnit.Framework.CategoryAttribute("LoTieuHuy")]
        [global::NUnit.Framework.CategoryAttribute("TC_ADMIN_LOTIEUHUY_024")]
        [global::NUnit.Framework.CategoryAttribute("Severity_LOW")]
        [global::NUnit.Framework.CategoryAttribute("Priority_LOW")]
        public async global::System.Threading.Tasks.Task TC_ADMIN_LOTIEUHUY_024_ResponsiveTrangQuảnLyLoTieuHủy()
        {
            string[] tagsOfScenario = new string[] {
                    "LoTieuHuy",
                    "TC_ADMIN_LOTIEUHUY_024",
                    "Severity_LOW",
                    "Priority_LOW"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "23";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("TC_ADMIN_LOTIEUHUY_024 - Responsive trang Quản lý Lô tiêu hủy", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 122
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 123
await testRunner.WhenAsync("Admin mở trang Quản lý Lô tiêu hủy trên màn hình mobile", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 124
await testRunner.ThenAsync("trang không bị tràn ngang nghiêm trọng", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
    }
}
#pragma warning restore
#endregion
