// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace KDPM_ReqnrollSeleniumAutomationTesting_Nhom5.Features
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::NUnit.Framework.TestFixtureAttribute()]
    [global::NUnit.Framework.DescriptionAttribute("Quản lý lô thuốc")]
    [global::NUnit.Framework.FixtureLifeCycleAttribute(global::NUnit.Framework.LifeCycle.InstancePerTestCase)]
    public partial class QuảnLyLoThuốcFeature
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "Features", "Quản lý lô thuốc", "Kiểm thử chức năng Quản lý lô thuốc của hệ thống MedForAll.\r\nCác scenario trong f" +
                "ile này được đồng bộ theo test case Selenium đã chạy.", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
#line 1 "QuanLyLoThuoc.feature"
#line hidden
        
        [global::NUnit.Framework.OneTimeSetUpAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        [global::NUnit.Framework.OneTimeTearDownAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        [global::NUnit.Framework.SetUpAttribute()]
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        [global::NUnit.Framework.TearDownAttribute()]
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<global::NUnit.Framework.TestContext>(global::NUnit.Framework.TestContext.CurrentContext);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/QuanLyLoThuoc.feature.ndjson", 28);
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("TC_ADMIN_QUANLYLOTHUOC_001 - Mở trang Quản lý Lô thuốc")]
        [global::NUnit.Framework.CategoryAttribute("LoThuoc")]
        [global::NUnit.Framework.CategoryAttribute("TC_ADMIN_QUANLYLOTHUOC_001")]
        [global::NUnit.Framework.CategoryAttribute("Severity_LOW")]
        [global::NUnit.Framework.CategoryAttribute("Priority_LOW")]
        public async global::System.Threading.Tasks.Task TC_ADMIN_QUANLYLOTHUOC_001_MởTrangQuảnLyLoThuốc()
        {
            string[] tagsOfScenario = new string[] {
                    "LoThuoc",
                    "TC_ADMIN_QUANLYLOTHUOC_001",
                    "Severity_LOW",
                    "Priority_LOW"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "0";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("TC_ADMIN_QUANLYLOTHUOC_001 - Mở trang Quản lý Lô thuốc", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 7
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 8
await testRunner.WhenAsync("Admin truy cập trang Quản lý Lô thuốc", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 9
await testRunner.ThenAsync("trang Quản lý Lô thuốc mở được, có tiêu đề và không hiển thị lỗi hệ thống", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("TC_ADMIN_QUANLYLOTHUOC_002 - Kiểm tra sidebar active")]
        [global::NUnit.Framework.CategoryAttribute("LoThuoc")]
        [global::NUnit.Framework.CategoryAttribute("TC_ADMIN_QUANLYLOTHUOC_002")]
        [global::NUnit.Framework.CategoryAttribute("Severity_LOW")]
        [global::NUnit.Framework.CategoryAttribute("Priority_LOW")]
        public async global::System.Threading.Tasks.Task TC_ADMIN_QUANLYLOTHUOC_002_KiểmTraSidebarActive()
        {
            string[] tagsOfScenario = new string[] {
                    "LoThuoc",
                    "TC_ADMIN_QUANLYLOTHUOC_002",
                    "Severity_LOW",
                    "Priority_LOW"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "1";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("TC_ADMIN_QUANLYLOTHUOC_002 - Kiểm tra sidebar active", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 12
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 13
await testRunner.WhenAsync("Admin truy cập trang Quản lý Lô thuốc", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 14
await testRunner.ThenAsync("menu Quản lý Lô thuốc trên sidebar được active đúng", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("TC_ADMIN_QUANLYLOTHUOC_003 - Kiểm tra tiêu đề cột bảng")]
        [global::NUnit.Framework.CategoryAttribute("LoThuoc")]
        [global::NUnit.Framework.CategoryAttribute("TC_ADMIN_QUANLYLOTHUOC_003")]
        [global::NUnit.Framework.CategoryAttribute("Severity_LOW")]
        [global::NUnit.Framework.CategoryAttribute("Priority_LOW")]
        public async global::System.Threading.Tasks.Task TC_ADMIN_QUANLYLOTHUOC_003_KiểmTraTieuDềCộtBảng()
        {
            string[] tagsOfScenario = new string[] {
                    "LoThuoc",
                    "TC_ADMIN_QUANLYLOTHUOC_003",
                    "Severity_LOW",
                    "Priority_LOW"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "2";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("TC_ADMIN_QUANLYLOTHUOC_003 - Kiểm tra tiêu đề cột bảng", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 17
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 18
await testRunner.WhenAsync("Admin truy cập trang Quản lý Lô thuốc", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 19
await testRunner.ThenAsync("bảng lô thuốc hiển thị đủ các cột Thuốc, Số lô, Hạn sử dụng, Giá nhập, Nhập tồn, " +
                        "Trạng thái và Tác vụ", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("TC_ADMIN_QUANLYLOTHUOC_004 - Kiểm tra bảng có dữ liệu hợp lệ")]
        [global::NUnit.Framework.CategoryAttribute("LoThuoc")]
        [global::NUnit.Framework.CategoryAttribute("TC_ADMIN_QUANLYLOTHUOC_004")]
        [global::NUnit.Framework.CategoryAttribute("Severity_MEDIUM")]
        [global::NUnit.Framework.CategoryAttribute("Priority_MEDIUM")]
        public async global::System.Threading.Tasks.Task TC_ADMIN_QUANLYLOTHUOC_004_KiểmTraBảngCoDữLiệuHợpLệ()
        {
            string[] tagsOfScenario = new string[] {
                    "LoThuoc",
                    "TC_ADMIN_QUANLYLOTHUOC_004",
                    "Severity_MEDIUM",
                    "Priority_MEDIUM"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "3";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("TC_ADMIN_QUANLYLOTHUOC_004 - Kiểm tra bảng có dữ liệu hợp lệ", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 22
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 23
await testRunner.WhenAsync("Admin truy cập trang Quản lý Lô thuốc", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 24
await testRunner.ThenAsync("danh sách lô thuốc hiển thị dữ liệu hợp lệ gồm tên thuốc, số lô, hạn sử dụng, giá" +
                        " nhập và trạng thái", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("TC_ADMIN_QUANLYLOTHUOC_005 - Lọc lô Sắp hết hạn")]
        [global::NUnit.Framework.CategoryAttribute("LoThuoc")]
        [global::NUnit.Framework.CategoryAttribute("TC_ADMIN_QUANLYLOTHUOC_005")]
        [global::NUnit.Framework.CategoryAttribute("Severity_MEDIUM")]
        [global::NUnit.Framework.CategoryAttribute("Priority_MEDIUM")]
        public async global::System.Threading.Tasks.Task TC_ADMIN_QUANLYLOTHUOC_005_LọcLoSắpHếtHạn()
        {
            string[] tagsOfScenario = new string[] {
                    "LoThuoc",
                    "TC_ADMIN_QUANLYLOTHUOC_005",
                    "Severity_MEDIUM",
                    "Priority_MEDIUM"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "4";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("TC_ADMIN_QUANLYLOTHUOC_005 - Lọc lô Sắp hết hạn", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 27
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 28
await testRunner.WhenAsync("Admin lọc lô thuốc theo trạng thái Sắp hết hạn", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 29
await testRunner.ThenAsync("hệ thống chỉ hiển thị các lô có hạn sử dụng từ ngày hiện tại đến 90 ngày tới", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("TC_ADMIN_QUANLYLOTHUOC_006 - Lọc lô Đã hết hạn")]
        [global::NUnit.Framework.CategoryAttribute("LoThuoc")]
        [global::NUnit.Framework.CategoryAttribute("TC_ADMIN_QUANLYLOTHUOC_006")]
        [global::NUnit.Framework.CategoryAttribute("Severity_MEDIUM")]
        [global::NUnit.Framework.CategoryAttribute("Priority_MEDIUM")]
        public async global::System.Threading.Tasks.Task TC_ADMIN_QUANLYLOTHUOC_006_LọcLoDaHếtHạn()
        {
            string[] tagsOfScenario = new string[] {
                    "LoThuoc",
                    "TC_ADMIN_QUANLYLOTHUOC_006",
                    "Severity_MEDIUM",
                    "Priority_MEDIUM"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "5";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("TC_ADMIN_QUANLYLOTHUOC_006 - Lọc lô Đã hết hạn", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 32
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 33
await testRunner.WhenAsync("Admin lọc lô thuốc theo trạng thái Đã hết hạn", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 34
await testRunner.ThenAsync("hệ thống chỉ hiển thị các lô có hạn sử dụng nhỏ hơn ngày hiện tại", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("TC_ADMIN_QUANLYLOTHUOC_007 - Lọc Tất cả lô thuốc")]
        [global::NUnit.Framework.CategoryAttribute("LoThuoc")]
        [global::NUnit.Framework.CategoryAttribute("TC_ADMIN_QUANLYLOTHUOC_007")]
        [global::NUnit.Framework.CategoryAttribute("Severity_LOW")]
        [global::NUnit.Framework.CategoryAttribute("Priority_LOW")]
        public async global::System.Threading.Tasks.Task TC_ADMIN_QUANLYLOTHUOC_007_LọcTấtCảLoThuốc()
        {
            string[] tagsOfScenario = new string[] {
                    "LoThuoc",
                    "TC_ADMIN_QUANLYLOTHUOC_007",
                    "Severity_LOW",
                    "Priority_LOW"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "6";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("TC_ADMIN_QUANLYLOTHUOC_007 - Lọc Tất cả lô thuốc", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 37
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 38
await testRunner.WhenAsync("Admin chọn bộ lọc Tất cả lô thuốc", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 39
await testRunner.ThenAsync("hệ thống hiển thị toàn bộ danh sách lô thuốc", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("TC_ADMIN_QUANLYLOTHUOC_008 - Kiểm tra đường dẫn 3 nút lọc")]
        [global::NUnit.Framework.CategoryAttribute("LoThuoc")]
        [global::NUnit.Framework.CategoryAttribute("TC_ADMIN_QUANLYLOTHUOC_008")]
        [global::NUnit.Framework.CategoryAttribute("Severity_LOW")]
        [global::NUnit.Framework.CategoryAttribute("Priority_LOW")]
        public async global::System.Threading.Tasks.Task TC_ADMIN_QUANLYLOTHUOC_008_KiểmTraDườngDẫn3NutLọc()
        {
            string[] tagsOfScenario = new string[] {
                    "LoThuoc",
                    "TC_ADMIN_QUANLYLOTHUOC_008",
                    "Severity_LOW",
                    "Priority_LOW"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "7";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("TC_ADMIN_QUANLYLOTHUOC_008 - Kiểm tra đường dẫn 3 nút lọc", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 42
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 43
await testRunner.WhenAsync("Admin truy cập trang Quản lý Lô thuốc", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 44
await testRunner.ThenAsync("các nút lọc của trang Quản lý Lô thuốc có đường dẫn đúng", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("TC_ADMIN_QUANLYLOTHUOC_009 - Sắp xếp theo Số lô tăng dần")]
        [global::NUnit.Framework.CategoryAttribute("LoThuoc")]
        [global::NUnit.Framework.CategoryAttribute("TC_ADMIN_QUANLYLOTHUOC_009")]
        [global::NUnit.Framework.CategoryAttribute("Severity_LOW")]
        [global::NUnit.Framework.CategoryAttribute("Priority_LOW")]
        public async global::System.Threading.Tasks.Task TC_ADMIN_QUANLYLOTHUOC_009_SắpXếpTheoSốLoTangDần()
        {
            string[] tagsOfScenario = new string[] {
                    "LoThuoc",
                    "TC_ADMIN_QUANLYLOTHUOC_009",
                    "Severity_LOW",
                    "Priority_LOW"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "8";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("TC_ADMIN_QUANLYLOTHUOC_009 - Sắp xếp theo Số lô tăng dần", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 47
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 48
await testRunner.WhenAsync("Admin sắp xếp danh sách lô thuốc theo Số lô tăng dần", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 49
await testRunner.ThenAsync("danh sách lô thuốc được sắp xếp đúng theo số lô tăng dần", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("TC_ADMIN_QUANLYLOTHUOC_010 - Kiểm tra phân loại ngày hết hạn")]
        [global::NUnit.Framework.CategoryAttribute("LoThuoc")]
        [global::NUnit.Framework.CategoryAttribute("TC_ADMIN_QUANLYLOTHUOC_010")]
        [global::NUnit.Framework.CategoryAttribute("Severity_MEDIUM")]
        [global::NUnit.Framework.CategoryAttribute("Priority_MEDIUM")]
        public async global::System.Threading.Tasks.Task TC_ADMIN_QUANLYLOTHUOC_010_KiểmTraPhanLoạiNgayHếtHạn()
        {
            string[] tagsOfScenario = new string[] {
                    "LoThuoc",
                    "TC_ADMIN_QUANLYLOTHUOC_010",
                    "Severity_MEDIUM",
                    "Priority_MEDIUM"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "9";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("TC_ADMIN_QUANLYLOTHUOC_010 - Kiểm tra phân loại ngày hết hạn", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 52
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 53
await testRunner.WhenAsync("Admin truy cập trang Quản lý Lô thuốc", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 54
await testRunner.ThenAsync("các lô hết hạn và sắp hết hạn được gắn nhãn hoặc tô màu đúng", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("TC_ADMIN_QUANLYLOTHUOC_011 - Kiểm tra định dạng giá nhập")]
        [global::NUnit.Framework.CategoryAttribute("LoThuoc")]
        [global::NUnit.Framework.CategoryAttribute("TC_ADMIN_QUANLYLOTHUOC_011")]
        [global::NUnit.Framework.CategoryAttribute("Severity_MEDIUM")]
        [global::NUnit.Framework.CategoryAttribute("Priority_MEDIUM")]
        public async global::System.Threading.Tasks.Task TC_ADMIN_QUANLYLOTHUOC_011_KiểmTraDịnhDạngGiaNhập()
        {
            string[] tagsOfScenario = new string[] {
                    "LoThuoc",
                    "TC_ADMIN_QUANLYLOTHUOC_011",
                    "Severity_MEDIUM",
                    "Priority_MEDIUM"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "10";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("TC_ADMIN_QUANLYLOTHUOC_011 - Kiểm tra định dạng giá nhập", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 57
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 58
await testRunner.WhenAsync("Admin truy cập trang Quản lý Lô thuốc", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 59
await testRunner.ThenAsync("giá nhập của các lô thuốc là số dương và hiển thị đúng định dạng", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("TC_ADMIN_QUANLYLOTHUOC_012 - Kiểm tra định dạng Nhập , Tồn")]
        [global::NUnit.Framework.CategoryAttribute("LoThuoc")]
        [global::NUnit.Framework.CategoryAttribute("TC_ADMIN_QUANLYLOTHUOC_012")]
        [global::NUnit.Framework.CategoryAttribute("Severity_MEDIUM")]
        [global::NUnit.Framework.CategoryAttribute("Priority_MEDIUM")]
        public async global::System.Threading.Tasks.Task TC_ADMIN_QUANLYLOTHUOC_012_KiểmTraDịnhDạngNhậpTồn()
        {
            string[] tagsOfScenario = new string[] {
                    "LoThuoc",
                    "TC_ADMIN_QUANLYLOTHUOC_012",
                    "Severity_MEDIUM",
                    "Priority_MEDIUM"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "11";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("TC_ADMIN_QUANLYLOTHUOC_012 - Kiểm tra định dạng Nhập , Tồn", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 62
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 63
await testRunner.WhenAsync("Admin truy cập trang Quản lý Lô thuốc", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 64
await testRunner.ThenAsync("số nhập và số tồn hiển thị hợp lệ, không âm và tồn không lớn hơn nhập", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("TC_ADMIN_QUANLYLOTHUOC_013 - Kiểm tra trạng thái lô")]
        [global::NUnit.Framework.CategoryAttribute("LoThuoc")]
        [global::NUnit.Framework.CategoryAttribute("TC_ADMIN_QUANLYLOTHUOC_013")]
        [global::NUnit.Framework.CategoryAttribute("Severity_MEDIUM")]
        [global::NUnit.Framework.CategoryAttribute("Priority_MEDIUM")]
        public async global::System.Threading.Tasks.Task TC_ADMIN_QUANLYLOTHUOC_013_KiểmTraTrạngThaiLo()
        {
            string[] tagsOfScenario = new string[] {
                    "LoThuoc",
                    "TC_ADMIN_QUANLYLOTHUOC_013",
                    "Severity_MEDIUM",
                    "Priority_MEDIUM"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "12";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("TC_ADMIN_QUANLYLOTHUOC_013 - Kiểm tra trạng thái lô", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 67
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 68
await testRunner.WhenAsync("Admin truy cập trang Quản lý Lô thuốc", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 69
await testRunner.ThenAsync("trạng thái lô thuốc thuộc nhóm Đang bán, Ngưng bán hoặc Đã tiêu hủy", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("TC_ADMIN_QUANLYLOTHUOC_014 - Kiểm tra mỗi dòng có nút tác vụ")]
        [global::NUnit.Framework.CategoryAttribute("LoThuoc")]
        [global::NUnit.Framework.CategoryAttribute("TC_ADMIN_QUANLYLOTHUOC_014")]
        [global::NUnit.Framework.CategoryAttribute("Severity_MEDIUM")]
        [global::NUnit.Framework.CategoryAttribute("Priority_MEDIUM")]
        public async global::System.Threading.Tasks.Task TC_ADMIN_QUANLYLOTHUOC_014_KiểmTraMỗiDongCoNutTacVụ()
        {
            string[] tagsOfScenario = new string[] {
                    "LoThuoc",
                    "TC_ADMIN_QUANLYLOTHUOC_014",
                    "Severity_MEDIUM",
                    "Priority_MEDIUM"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "13";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("TC_ADMIN_QUANLYLOTHUOC_014 - Kiểm tra mỗi dòng có nút tác vụ", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 72
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 73
await testRunner.WhenAsync("Admin truy cập trang Quản lý Lô thuốc", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 74
await testRunner.ThenAsync("mỗi lô thuốc có nút tác vụ phù hợp", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("TC_ADMIN_QUANLYLOTHUOC_015 - Kiểm tra nút Xóa gọi đúng hàm deleteLo")]
        [global::NUnit.Framework.CategoryAttribute("LoThuoc")]
        [global::NUnit.Framework.CategoryAttribute("TC_ADMIN_QUANLYLOTHUOC_015")]
        [global::NUnit.Framework.CategoryAttribute("Severity_MEDIUM")]
        [global::NUnit.Framework.CategoryAttribute("Priority_MEDIUM")]
        public async global::System.Threading.Tasks.Task TC_ADMIN_QUANLYLOTHUOC_015_KiểmTraNutXoaGọiDungHamDeleteLo()
        {
            string[] tagsOfScenario = new string[] {
                    "LoThuoc",
                    "TC_ADMIN_QUANLYLOTHUOC_015",
                    "Severity_MEDIUM",
                    "Priority_MEDIUM"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "14";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("TC_ADMIN_QUANLYLOTHUOC_015 - Kiểm tra nút Xóa gọi đúng hàm deleteLo", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 77
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 78
await testRunner.WhenAsync("Admin kiểm tra nút Xóa của lô thuốc", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 79
await testRunner.ThenAsync("nút Xóa gọi đúng hàm deleteLo", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("TC_ADMIN_QUANLYLOTHUOC_016 - Kiểm tra nút Tiêu hủy gọi đúng hàm tieuHuyLo")]
        [global::NUnit.Framework.CategoryAttribute("LoThuoc")]
        [global::NUnit.Framework.CategoryAttribute("TC_ADMIN_QUANLYLOTHUOC_016")]
        [global::NUnit.Framework.CategoryAttribute("Severity_MEDIUM")]
        [global::NUnit.Framework.CategoryAttribute("Priority_MEDIUM")]
        public async global::System.Threading.Tasks.Task TC_ADMIN_QUANLYLOTHUOC_016_KiểmTraNutTieuHủyGọiDungHamTieuHuyLo()
        {
            string[] tagsOfScenario = new string[] {
                    "LoThuoc",
                    "TC_ADMIN_QUANLYLOTHUOC_016",
                    "Severity_MEDIUM",
                    "Priority_MEDIUM"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "15";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("TC_ADMIN_QUANLYLOTHUOC_016 - Kiểm tra nút Tiêu hủy gọi đúng hàm tieuHuyLo", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 82
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 83
await testRunner.WhenAsync("Admin kiểm tra nút Tiêu hủy của lô thuốc", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 84
await testRunner.ThenAsync("nút Tiêu hủy gọi đúng hàm tieuHuyLo", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("TC_ADMIN_QUANLYLOTHUOC_017 - Hủy xóa lô thuốc")]
        [global::NUnit.Framework.CategoryAttribute("LoThuoc")]
        [global::NUnit.Framework.CategoryAttribute("TC_ADMIN_QUANLYLOTHUOC_017")]
        [global::NUnit.Framework.CategoryAttribute("Severity_MEDIUM")]
        [global::NUnit.Framework.CategoryAttribute("Priority_MEDIUM")]
        public async global::System.Threading.Tasks.Task TC_ADMIN_QUANLYLOTHUOC_017_HủyXoaLoThuốc()
        {
            string[] tagsOfScenario = new string[] {
                    "LoThuoc",
                    "TC_ADMIN_QUANLYLOTHUOC_017",
                    "Severity_MEDIUM",
                    "Priority_MEDIUM"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "16";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("TC_ADMIN_QUANLYLOTHUOC_017 - Hủy xóa lô thuốc", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 87
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 88
await testRunner.WhenAsync("Admin bấm Xóa lô thuốc nhưng chọn Cancel ở hộp xác nhận", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 89
await testRunner.ThenAsync("hệ thống không xóa lô thuốc và dữ liệu không thay đổi", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("TC_ADMIN_QUANLYLOTHUOC_018 - Hủy tiêu hủy lô thuốc")]
        [global::NUnit.Framework.CategoryAttribute("LoThuoc")]
        [global::NUnit.Framework.CategoryAttribute("TC_ADMIN_QUANLYLOTHUOC_018")]
        [global::NUnit.Framework.CategoryAttribute("Severity_MEDIUM")]
        [global::NUnit.Framework.CategoryAttribute("Priority_MEDIUM")]
        public async global::System.Threading.Tasks.Task TC_ADMIN_QUANLYLOTHUOC_018_HủyTieuHủyLoThuốc()
        {
            string[] tagsOfScenario = new string[] {
                    "LoThuoc",
                    "TC_ADMIN_QUANLYLOTHUOC_018",
                    "Severity_MEDIUM",
                    "Priority_MEDIUM"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "17";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("TC_ADMIN_QUANLYLOTHUOC_018 - Hủy tiêu hủy lô thuốc", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 92
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 93
await testRunner.WhenAsync("Admin bấm Tiêu hủy lô thuốc nhưng chọn Cancel ở hộp xác nhận", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 94
await testRunner.ThenAsync("hệ thống không tiêu hủy lô thuốc và dữ liệu không thay đổi", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("TC_ADMIN_QUANLYLOTHUOC_019 - Backend chặn xóa ID không tồn tại")]
        [global::NUnit.Framework.CategoryAttribute("LoThuoc")]
        [global::NUnit.Framework.CategoryAttribute("TC_ADMIN_QUANLYLOTHUOC_019")]
        [global::NUnit.Framework.CategoryAttribute("Severity_HIGH")]
        [global::NUnit.Framework.CategoryAttribute("Priority_HIGH")]
        public async global::System.Threading.Tasks.Task TC_ADMIN_QUANLYLOTHUOC_019_BackendChặnXoaIDKhongTồnTại()
        {
            string[] tagsOfScenario = new string[] {
                    "LoThuoc",
                    "TC_ADMIN_QUANLYLOTHUOC_019",
                    "Severity_HIGH",
                    "Priority_HIGH"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "18";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("TC_ADMIN_QUANLYLOTHUOC_019 - Backend chặn xóa ID không tồn tại", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 97
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 98
await testRunner.WhenAsync("Admin gửi request xóa lô thuốc với ID không tồn tại", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 99
await testRunner.ThenAsync("backend trả về kết quả thất bại và không phát sinh lỗi hệ thống", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("TC_ADMIN_QUANLYLOTHUOC_020 - Backend chặn tiêu hủy ID không tồn tại")]
        [global::NUnit.Framework.CategoryAttribute("LoThuoc")]
        [global::NUnit.Framework.CategoryAttribute("TC_ADMIN_QUANLYLOTHUOC_020")]
        [global::NUnit.Framework.CategoryAttribute("Severity_HIGH")]
        [global::NUnit.Framework.CategoryAttribute("Priority_HIGH")]
        public async global::System.Threading.Tasks.Task TC_ADMIN_QUANLYLOTHUOC_020_BackendChặnTieuHủyIDKhongTồnTại()
        {
            string[] tagsOfScenario = new string[] {
                    "LoThuoc",
                    "TC_ADMIN_QUANLYLOTHUOC_020",
                    "Severity_HIGH",
                    "Priority_HIGH"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "19";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("TC_ADMIN_QUANLYLOTHUOC_020 - Backend chặn tiêu hủy ID không tồn tại", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 102
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 103
await testRunner.WhenAsync("Admin gửi request tiêu hủy lô thuốc với ID không tồn tại", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 104
await testRunner.ThenAsync("backend trả về kết quả thất bại và không phát sinh lỗi hệ thống", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("TC_ADMIN_QUANLYLOTHUOC_021 - Kiểm tra ảnh lô thuốc có src")]
        [global::NUnit.Framework.CategoryAttribute("LoThuoc")]
        [global::NUnit.Framework.CategoryAttribute("TC_ADMIN_QUANLYLOTHUOC_021")]
        [global::NUnit.Framework.CategoryAttribute("Severity_LOW")]
        [global::NUnit.Framework.CategoryAttribute("Priority_LOW")]
        public async global::System.Threading.Tasks.Task TC_ADMIN_QUANLYLOTHUOC_021_KiểmTraẢnhLoThuốcCoSrc()
        {
            string[] tagsOfScenario = new string[] {
                    "LoThuoc",
                    "TC_ADMIN_QUANLYLOTHUOC_021",
                    "Severity_LOW",
                    "Priority_LOW"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "20";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("TC_ADMIN_QUANLYLOTHUOC_021 - Kiểm tra ảnh lô thuốc có src", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 107
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 108
await testRunner.WhenAsync("Admin truy cập trang Quản lý Lô thuốc", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 109
await testRunner.ThenAsync("ảnh thuốc trong bảng lô thuốc có đường dẫn src", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("TC_ADMIN_QUANLYLOTHUOC_022 - Kiểm tra ảnh lô thuốc tải được")]
        [global::NUnit.Framework.CategoryAttribute("LoThuoc")]
        [global::NUnit.Framework.CategoryAttribute("TC_ADMIN_QUANLYLOTHUOC_022")]
        [global::NUnit.Framework.CategoryAttribute("Severity_LOW")]
        [global::NUnit.Framework.CategoryAttribute("Priority_LOW")]
        public async global::System.Threading.Tasks.Task TC_ADMIN_QUANLYLOTHUOC_022_KiểmTraẢnhLoThuốcTảiDược()
        {
            string[] tagsOfScenario = new string[] {
                    "LoThuoc",
                    "TC_ADMIN_QUANLYLOTHUOC_022",
                    "Severity_LOW",
                    "Priority_LOW"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "21";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("TC_ADMIN_QUANLYLOTHUOC_022 - Kiểm tra ảnh lô thuốc tải được", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 112
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 113
await testRunner.WhenAsync("Admin truy cập trang Quản lý Lô thuốc", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 114
await testRunner.ThenAsync("không có ảnh thuốc bị vỡ trong bảng lô thuốc", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("TC_ADMIN_QUANLYLOTHUOC_023 - Kiểm tra không hiển thị số âm")]
        [global::NUnit.Framework.CategoryAttribute("LoThuoc")]
        [global::NUnit.Framework.CategoryAttribute("TC_ADMIN_QUANLYLOTHUOC_023")]
        [global::NUnit.Framework.CategoryAttribute("Severity_MEDIUM")]
        [global::NUnit.Framework.CategoryAttribute("Priority_MEDIUM")]
        public async global::System.Threading.Tasks.Task TC_ADMIN_QUANLYLOTHUOC_023_KiểmTraKhongHiểnThịSốAm()
        {
            string[] tagsOfScenario = new string[] {
                    "LoThuoc",
                    "TC_ADMIN_QUANLYLOTHUOC_023",
                    "Severity_MEDIUM",
                    "Priority_MEDIUM"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "22";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("TC_ADMIN_QUANLYLOTHUOC_023 - Kiểm tra không hiển thị số âm", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 117
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 118
await testRunner.WhenAsync("Admin truy cập trang Quản lý Lô thuốc", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 119
await testRunner.ThenAsync("trang Quản lý Lô thuốc không hiển thị số âm bất thường", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("TC_ADMIN_QUANLYLOTHUOC_024 - Responsive trang Quản lý Lô thuốc")]
        [global::NUnit.Framework.CategoryAttribute("LoThuoc")]
        [global::NUnit.Framework.CategoryAttribute("TC_ADMIN_QUANLYLOTHUOC_024")]
        [global::NUnit.Framework.CategoryAttribute("Severity_LOW")]
        [global::NUnit.Framework.CategoryAttribute("Priority_LOW")]
        public async global::System.Threading.Tasks.Task TC_ADMIN_QUANLYLOTHUOC_024_ResponsiveTrangQuảnLyLoThuốc()
        {
            string[] tagsOfScenario = new string[] {
                    "LoThuoc",
                    "TC_ADMIN_QUANLYLOTHUOC_024",
                    "Severity_LOW",
                    "Priority_LOW"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "23";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("TC_ADMIN_QUANLYLOTHUOC_024 - Responsive trang Quản lý Lô thuốc", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 122
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 123
await testRunner.WhenAsync("Admin mở trang Quản lý Lô thuốc trên màn hình mobile", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 124
await testRunner.ThenAsync("trang Quản lý Lô thuốc không bị tràn ngang nghiêm trọng", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("TC_ADMIN_QUANLYLOTHUOC_025 - Xóa lô thuốc thật")]
        [global::NUnit.Framework.CategoryAttribute("LoThuoc")]
        [global::NUnit.Framework.CategoryAttribute("TC_ADMIN_QUANLYLOTHUOC_025")]
        [global::NUnit.Framework.CategoryAttribute("Severity_HIGH")]
        [global::NUnit.Framework.CategoryAttribute("Priority_MEDIUM")]
        [global::NUnit.Framework.CategoryAttribute("Skip")]
        public async global::System.Threading.Tasks.Task TC_ADMIN_QUANLYLOTHUOC_025_XoaLoThuốcThật()
        {
            string[] tagsOfScenario = new string[] {
                    "LoThuoc",
                    "TC_ADMIN_QUANLYLOTHUOC_025",
                    "Severity_HIGH",
                    "Priority_MEDIUM",
                    "Skip"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "24";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("TC_ADMIN_QUANLYLOTHUOC_025 - Xóa lô thuốc thật", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 127
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 128
await testRunner.WhenAsync("Admin xác nhận xóa thật một lô thuốc", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 129
await testRunner.ThenAsync("lô thuốc bị xóa khỏi danh sách", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("TC_ADMIN_QUANLYLOTHUOC_026 - Tiêu hủy lô thuốc thật")]
        [global::NUnit.Framework.CategoryAttribute("LoThuoc")]
        [global::NUnit.Framework.CategoryAttribute("TC_ADMIN_QUANLYLOTHUOC_026")]
        [global::NUnit.Framework.CategoryAttribute("Severity_HIGH")]
        [global::NUnit.Framework.CategoryAttribute("Priority_MEDIUM")]
        [global::NUnit.Framework.CategoryAttribute("Skip")]
        public async global::System.Threading.Tasks.Task TC_ADMIN_QUANLYLOTHUOC_026_TieuHủyLoThuốcThật()
        {
            string[] tagsOfScenario = new string[] {
                    "LoThuoc",
                    "TC_ADMIN_QUANLYLOTHUOC_026",
                    "Severity_HIGH",
                    "Priority_MEDIUM",
                    "Skip"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "25";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("TC_ADMIN_QUANLYLOTHUOC_026 - Tiêu hủy lô thuốc thật", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 132
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 133
await testRunner.WhenAsync("Admin xác nhận tiêu hủy thật một lô thuốc", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 134
await testRunner.ThenAsync("lô thuốc chuyển tồn kho về 0, trạng thái Đã tiêu hủy và xuất hiện ở trang Quản lý" +
                        " lô tiêu hủy", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
    }
}
#pragma warning restore
#endregion
